# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addtquestions2.ui'
#
# Created: Mon Feb 15 10:02:28 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AdditionalQuestions2(object):
    def setupUi(self, AdditionalQuestions2):
        AdditionalQuestions2.setObjectName("AdditionalQuestions2")
        AdditionalQuestions2.setWindowModality(QtCore.Qt.WindowModal)
        AdditionalQuestions2.resize(432, 293)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(AdditionalQuestions2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_5 = QtGui.QGroupBox(AdditionalQuestions2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_63 = QtGui.QWidget(self.groupBox_5)
        self.widget_63.setObjectName("widget_63")
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.widget_63)
        self.verticalLayout_31.setSpacing(4)
        self.verticalLayout_31.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.widget_64 = QtGui.QWidget(self.widget_63)
        self.widget_64.setObjectName("widget_64")
        self.horizontalLayout_40 = QtGui.QHBoxLayout(self.widget_64)
        self.horizontalLayout_40.setSpacing(4)
        self.horizontalLayout_40.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_45 = QtGui.QLabel(self.widget_64)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_40.addWidget(self.label_45)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem)
        self.catch_personal = QtGui.QLineEdit(self.widget_64)
        self.catch_personal.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_personal.setFont(font)
        self.catch_personal.setObjectName("catch_personal")
        self.horizontalLayout_40.addWidget(self.catch_personal)
        self.verticalLayout_31.addWidget(self.widget_64)
        self.verticalLayout.addWidget(self.widget_63)
        self.widget_65 = QtGui.QWidget(self.groupBox_5)
        self.widget_65.setObjectName("widget_65")
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.widget_65)
        self.verticalLayout_32.setSpacing(4)
        self.verticalLayout_32.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.widget_66 = QtGui.QWidget(self.widget_65)
        self.widget_66.setObjectName("widget_66")
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.widget_66)
        self.horizontalLayout_41.setSpacing(4)
        self.horizontalLayout_41.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_46 = QtGui.QLabel(self.widget_66)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_41.addWidget(self.label_46)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem1)
        self.catch_customers = QtGui.QLineEdit(self.widget_66)
        self.catch_customers.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_customers.setFont(font)
        self.catch_customers.setObjectName("catch_customers")
        self.horizontalLayout_41.addWidget(self.catch_customers)
        self.verticalLayout_32.addWidget(self.widget_66)
        self.verticalLayout.addWidget(self.widget_65)
        self.widget_67 = QtGui.QWidget(self.groupBox_5)
        self.widget_67.setObjectName("widget_67")
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.widget_67)
        self.verticalLayout_33.setSpacing(4)
        self.verticalLayout_33.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.widget_68 = QtGui.QWidget(self.widget_67)
        self.widget_68.setObjectName("widget_68")
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.widget_68)
        self.horizontalLayout_42.setSpacing(4)
        self.horizontalLayout_42.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_47 = QtGui.QLabel(self.widget_68)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_42.addWidget(self.label_47)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem2)
        self.catch_hotel = QtGui.QLineEdit(self.widget_68)
        self.catch_hotel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_hotel.setFont(font)
        self.catch_hotel.setObjectName("catch_hotel")
        self.horizontalLayout_42.addWidget(self.catch_hotel)
        self.verticalLayout_33.addWidget(self.widget_68)
        self.verticalLayout.addWidget(self.widget_67)
        self.widget_25 = QtGui.QWidget(self.groupBox_5)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.widget_25)
        self.verticalLayout_34.setSpacing(4)
        self.verticalLayout_34.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.widget_27 = QtGui.QWidget(self.widget_25)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.widget_27)
        self.horizontalLayout_43.setSpacing(4)
        self.horizontalLayout_43.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_48 = QtGui.QLabel(self.widget_27)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_43.addWidget(self.label_48)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem3)
        self.catch_agency = QtGui.QLineEdit(self.widget_27)
        self.catch_agency.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_agency.setFont(font)
        self.catch_agency.setObjectName("catch_agency")
        self.horizontalLayout_43.addWidget(self.catch_agency)
        self.verticalLayout_34.addWidget(self.widget_27)
        self.verticalLayout.addWidget(self.widget_25)
        self.widget_33 = QtGui.QWidget(self.groupBox_5)
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.widget_33)
        self.verticalLayout_35.setSpacing(4)
        self.verticalLayout_35.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.widget_69 = QtGui.QWidget(self.widget_33)
        self.widget_69.setObjectName("widget_69")
        self.horizontalLayout_44 = QtGui.QHBoxLayout(self.widget_69)
        self.horizontalLayout_44.setSpacing(4)
        self.horizontalLayout_44.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_49 = QtGui.QLabel(self.widget_69)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_44.addWidget(self.label_49)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem4)
        self.catch_other = QtGui.QLineEdit(self.widget_69)
        self.catch_other.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_other.setFont(font)
        self.catch_other.setObjectName("catch_other")
        self.horizontalLayout_44.addWidget(self.catch_other)
        self.verticalLayout_35.addWidget(self.widget_69)
        self.verticalLayout.addWidget(self.widget_33)
        self.widget_70 = QtGui.QWidget(self.groupBox_5)
        self.widget_70.setObjectName("widget_70")
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.widget_70)
        self.verticalLayout_36.setSpacing(4)
        self.verticalLayout_36.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.widget_71 = QtGui.QWidget(self.widget_70)
        self.widget_71.setObjectName("widget_71")
        self.horizontalLayout_45 = QtGui.QHBoxLayout(self.widget_71)
        self.horizontalLayout_45.setSpacing(4)
        self.horizontalLayout_45.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_50 = QtGui.QLabel(self.widget_71)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_45.addWidget(self.label_50)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem5)
        self.catch_other_type = QtGui.QLineEdit(self.widget_71)
        self.catch_other_type.setMinimumSize(QtCore.QSize(200, 0))
        self.catch_other_type.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_other_type.setFont(font)
        self.catch_other_type.setObjectName("catch_other_type")
        self.horizontalLayout_45.addWidget(self.catch_other_type)
        self.verticalLayout_36.addWidget(self.widget_71)
        self.verticalLayout.addWidget(self.widget_70)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.widget_84 = QtGui.QWidget(self.groupBox_5)
        self.widget_84.setObjectName("widget_84")
        self.verticalLayout_43 = QtGui.QVBoxLayout(self.widget_84)
        self.verticalLayout_43.setSpacing(4)
        self.verticalLayout_43.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.button_box = QtGui.QWidget(self.widget_84)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout = QtGui.QHBoxLayout(self.button_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self.horizontalLayout.addWidget(self.pbnCancel)
        spacerItem8 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.pbnFinished = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFinished.setFont(font)
        self.pbnFinished.setObjectName("pbnFinished")
        self.horizontalLayout.addWidget(self.pbnFinished)
        self.verticalLayout_43.addWidget(self.button_box)
        self.verticalLayout.addWidget(self.widget_84)
        self.horizontalLayout_3.addWidget(self.groupBox_5)

        self.retranslateUi(AdditionalQuestions2)
        QtCore.QMetaObject.connectSlotsByName(AdditionalQuestions2)
        AdditionalQuestions2.setTabOrder(self.catch_personal, self.catch_customers)
        AdditionalQuestions2.setTabOrder(self.catch_customers, self.catch_hotel)
        AdditionalQuestions2.setTabOrder(self.catch_hotel, self.catch_agency)
        AdditionalQuestions2.setTabOrder(self.catch_agency, self.catch_other)
        AdditionalQuestions2.setTabOrder(self.catch_other, self.catch_other_type)
        AdditionalQuestions2.setTabOrder(self.catch_other_type, self.pbnFinished)
        AdditionalQuestions2.setTabOrder(self.pbnFinished, self.pbnCancel)

    def retranslateUi(self, AdditionalQuestions2):
        AdditionalQuestions2.setWindowTitle(QtGui.QApplication.translate("AdditionalQuestions2", "OpenOceanMap - Additional Questions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("AdditionalQuestions2", "% catch to individual or household (personal):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("AdditionalQuestions2", "% catch to housewives/customers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("AdditionalQuestions2", "% catch to hotels/restaurants:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("AdditionalQuestions2", "% catch to fish agency facility (processor):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("AdditionalQuestions2", "% catch to other (including direct export):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("AdditionalQuestions2", "Define \"other\" above:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("AdditionalQuestions2", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFinished.setText(QtGui.QApplication.translate("AdditionalQuestions2", "Continue", None, QtGui.QApplication.UnicodeUTF8))

