# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addtquestions.ui'
#
# Created: Fri Feb 05 18:01:15 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AdditionalQuestions(object):
    def setupUi(self, AdditionalQuestions):
        AdditionalQuestions.setObjectName("AdditionalQuestions")
        AdditionalQuestions.setWindowModality(QtCore.Qt.WindowModal)
        AdditionalQuestions.resize(800, 322)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(AdditionalQuestions)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtGui.QGroupBox(AdditionalQuestions)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_57 = QtGui.QWidget(self.groupBox_4)
        self.widget_57.setObjectName("widget_57")
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.widget_57)
        self.verticalLayout_28.setSpacing(4)
        self.verticalLayout_28.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.widget_58 = QtGui.QWidget(self.widget_57)
        self.widget_58.setObjectName("widget_58")
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.widget_58)
        self.horizontalLayout_37.setSpacing(4)
        self.horizontalLayout_37.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_42 = QtGui.QLabel(self.widget_58)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_37.addWidget(self.label_42)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem)
        self.pct_house_inc = QtGui.QLineEdit(self.widget_58)
        self.pct_house_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pct_house_inc.setFont(font)
        self.pct_house_inc.setObjectName("pct_house_inc")
        self.horizontalLayout_37.addWidget(self.pct_house_inc)
        self.verticalLayout_28.addWidget(self.widget_58)
        self.verticalLayout_2.addWidget(self.widget_57)
        self.widget_59 = QtGui.QWidget(self.groupBox_4)
        self.widget_59.setObjectName("widget_59")
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.widget_59)
        self.verticalLayout_29.setSpacing(4)
        self.verticalLayout_29.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.widget_60 = QtGui.QWidget(self.widget_59)
        self.widget_60.setObjectName("widget_60")
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.widget_60)
        self.horizontalLayout_38.setSpacing(4)
        self.horizontalLayout_38.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_43 = QtGui.QLabel(self.widget_60)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_38.addWidget(self.label_43)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem1)
        self.num_dependents = QtGui.QLineEdit(self.widget_60)
        self.num_dependents.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_dependents.setFont(font)
        self.num_dependents.setObjectName("num_dependents")
        self.horizontalLayout_38.addWidget(self.num_dependents)
        self.verticalLayout_29.addWidget(self.widget_60)
        self.verticalLayout_2.addWidget(self.widget_59)
        self.widget_61 = QtGui.QWidget(self.groupBox_4)
        self.widget_61.setObjectName("widget_61")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.widget_61)
        self.verticalLayout_30.setSpacing(4)
        self.verticalLayout_30.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.widget_62 = QtGui.QWidget(self.widget_61)
        self.widget_62.setObjectName("widget_62")
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.widget_62)
        self.horizontalLayout_39.setSpacing(4)
        self.horizontalLayout_39.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_44 = QtGui.QLabel(self.widget_62)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_39.addWidget(self.label_44)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem2)
        self.num_crew = QtGui.QLineEdit(self.widget_62)
        self.num_crew.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.num_crew.setFont(font)
        self.num_crew.setObjectName("num_crew")
        self.horizontalLayout_39.addWidget(self.num_crew)
        self.verticalLayout_30.addWidget(self.widget_62)
        self.verticalLayout_2.addWidget(self.widget_61)
        self.widget_24 = QtGui.QWidget(self.groupBox_4)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.widget_24)
        self.verticalLayout_14.setSpacing(4)
        self.verticalLayout_14.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_26 = QtGui.QWidget(self.widget_24)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_26)
        self.horizontalLayout_23.setSpacing(4)
        self.horizontalLayout_23.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtGui.QLabel(self.widget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem3)
        self.crew_shares = QtGui.QLineEdit(self.widget_26)
        self.crew_shares.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.crew_shares.setFont(font)
        self.crew_shares.setObjectName("crew_shares")
        self.horizontalLayout_23.addWidget(self.crew_shares)
        self.verticalLayout_14.addWidget(self.widget_26)
        self.verticalLayout_2.addWidget(self.widget_24)
        self.widget_32 = QtGui.QWidget(self.groupBox_4)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.widget_32)
        self.verticalLayout_16.setSpacing(4)
        self.verticalLayout_16.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_34 = QtGui.QWidget(self.widget_32)
        self.widget_34.setObjectName("widget_34")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.widget_34)
        self.horizontalLayout_25.setSpacing(4)
        self.horizontalLayout_25.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_30 = QtGui.QLabel(self.widget_34)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem4)
        self.boat_shares = QtGui.QLineEdit(self.widget_34)
        self.boat_shares.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boat_shares.setFont(font)
        self.boat_shares.setObjectName("boat_shares")
        self.horizontalLayout_25.addWidget(self.boat_shares)
        self.verticalLayout_16.addWidget(self.widget_34)
        self.verticalLayout_2.addWidget(self.widget_32)
        self.widget_35 = QtGui.QWidget(self.groupBox_4)
        self.widget_35.setObjectName("widget_35")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.widget_35)
        self.verticalLayout_17.setSpacing(4)
        self.verticalLayout_17.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_36 = QtGui.QWidget(self.widget_35)
        self.widget_36.setObjectName("widget_36")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.widget_36)
        self.horizontalLayout_26.setSpacing(4)
        self.horizontalLayout_26.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_31 = QtGui.QLabel(self.widget_36)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_26.addWidget(self.label_31)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.captain_shares = QtGui.QLineEdit(self.widget_36)
        self.captain_shares.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.captain_shares.setFont(font)
        self.captain_shares.setObjectName("captain_shares")
        self.horizontalLayout_26.addWidget(self.captain_shares)
        self.verticalLayout_17.addWidget(self.widget_36)
        self.verticalLayout_2.addWidget(self.widget_35)
        self.widget_37 = QtGui.QWidget(self.groupBox_4)
        self.widget_37.setObjectName("widget_37")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.widget_37)
        self.verticalLayout_18.setSpacing(4)
        self.verticalLayout_18.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_38 = QtGui.QWidget(self.widget_37)
        self.widget_38.setObjectName("widget_38")
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.widget_38)
        self.horizontalLayout_27.setSpacing(4)
        self.horizontalLayout_27.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_32 = QtGui.QLabel(self.widget_38)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_27.addWidget(self.label_32)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem6)
        self.owner_shares = QtGui.QLineEdit(self.widget_38)
        self.owner_shares.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.owner_shares.setFont(font)
        self.owner_shares.setObjectName("owner_shares")
        self.horizontalLayout_27.addWidget(self.owner_shares)
        self.verticalLayout_18.addWidget(self.widget_38)
        self.verticalLayout_2.addWidget(self.widget_37)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(AdditionalQuestions)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_63 = QtGui.QWidget(self.groupBox_5)
        self.widget_63.setObjectName("widget_63")
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.widget_63)
        self.verticalLayout_31.setSpacing(4)
        self.verticalLayout_31.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.widget_64 = QtGui.QWidget(self.widget_63)
        self.widget_64.setObjectName("widget_64")
        self.horizontalLayout_40 = QtGui.QHBoxLayout(self.widget_64)
        self.horizontalLayout_40.setSpacing(4)
        self.horizontalLayout_40.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_45 = QtGui.QLabel(self.widget_64)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_40.addWidget(self.label_45)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem8)
        self.catch_personal = QtGui.QLineEdit(self.widget_64)
        self.catch_personal.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_personal.setFont(font)
        self.catch_personal.setObjectName("catch_personal")
        self.horizontalLayout_40.addWidget(self.catch_personal)
        self.verticalLayout_31.addWidget(self.widget_64)
        self.verticalLayout.addWidget(self.widget_63)
        self.widget_65 = QtGui.QWidget(self.groupBox_5)
        self.widget_65.setObjectName("widget_65")
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.widget_65)
        self.verticalLayout_32.setSpacing(4)
        self.verticalLayout_32.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.widget_66 = QtGui.QWidget(self.widget_65)
        self.widget_66.setObjectName("widget_66")
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.widget_66)
        self.horizontalLayout_41.setSpacing(4)
        self.horizontalLayout_41.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_46 = QtGui.QLabel(self.widget_66)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_41.addWidget(self.label_46)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem9)
        self.catch_customers = QtGui.QLineEdit(self.widget_66)
        self.catch_customers.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_customers.setFont(font)
        self.catch_customers.setObjectName("catch_customers")
        self.horizontalLayout_41.addWidget(self.catch_customers)
        self.verticalLayout_32.addWidget(self.widget_66)
        self.verticalLayout.addWidget(self.widget_65)
        self.widget_67 = QtGui.QWidget(self.groupBox_5)
        self.widget_67.setObjectName("widget_67")
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.widget_67)
        self.verticalLayout_33.setSpacing(4)
        self.verticalLayout_33.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.widget_68 = QtGui.QWidget(self.widget_67)
        self.widget_68.setObjectName("widget_68")
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.widget_68)
        self.horizontalLayout_42.setSpacing(4)
        self.horizontalLayout_42.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_47 = QtGui.QLabel(self.widget_68)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_42.addWidget(self.label_47)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem10)
        self.catch_hotel = QtGui.QLineEdit(self.widget_68)
        self.catch_hotel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_hotel.setFont(font)
        self.catch_hotel.setObjectName("catch_hotel")
        self.horizontalLayout_42.addWidget(self.catch_hotel)
        self.verticalLayout_33.addWidget(self.widget_68)
        self.verticalLayout.addWidget(self.widget_67)
        self.widget_25 = QtGui.QWidget(self.groupBox_5)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.widget_25)
        self.verticalLayout_34.setSpacing(4)
        self.verticalLayout_34.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.widget_27 = QtGui.QWidget(self.widget_25)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.widget_27)
        self.horizontalLayout_43.setSpacing(4)
        self.horizontalLayout_43.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_48 = QtGui.QLabel(self.widget_27)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_43.addWidget(self.label_48)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem11)
        self.catch_agency = QtGui.QLineEdit(self.widget_27)
        self.catch_agency.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_agency.setFont(font)
        self.catch_agency.setObjectName("catch_agency")
        self.horizontalLayout_43.addWidget(self.catch_agency)
        self.verticalLayout_34.addWidget(self.widget_27)
        self.verticalLayout.addWidget(self.widget_25)
        self.widget_33 = QtGui.QWidget(self.groupBox_5)
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.widget_33)
        self.verticalLayout_35.setSpacing(4)
        self.verticalLayout_35.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.widget_69 = QtGui.QWidget(self.widget_33)
        self.widget_69.setObjectName("widget_69")
        self.horizontalLayout_44 = QtGui.QHBoxLayout(self.widget_69)
        self.horizontalLayout_44.setSpacing(4)
        self.horizontalLayout_44.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_49 = QtGui.QLabel(self.widget_69)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_44.addWidget(self.label_49)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem12)
        self.catch_other = QtGui.QLineEdit(self.widget_69)
        self.catch_other.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_other.setFont(font)
        self.catch_other.setObjectName("catch_other")
        self.horizontalLayout_44.addWidget(self.catch_other)
        self.verticalLayout_35.addWidget(self.widget_69)
        self.verticalLayout.addWidget(self.widget_33)
        self.widget_70 = QtGui.QWidget(self.groupBox_5)
        self.widget_70.setObjectName("widget_70")
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.widget_70)
        self.verticalLayout_36.setSpacing(4)
        self.verticalLayout_36.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.widget_71 = QtGui.QWidget(self.widget_70)
        self.widget_71.setObjectName("widget_71")
        self.horizontalLayout_45 = QtGui.QHBoxLayout(self.widget_71)
        self.horizontalLayout_45.setSpacing(4)
        self.horizontalLayout_45.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_50 = QtGui.QLabel(self.widget_71)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_45.addWidget(self.label_50)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem13)
        self.catch_other_type = QtGui.QLineEdit(self.widget_71)
        self.catch_other_type.setMinimumSize(QtCore.QSize(200, 0))
        self.catch_other_type.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.catch_other_type.setFont(font)
        self.catch_other_type.setObjectName("catch_other_type")
        self.horizontalLayout_45.addWidget(self.catch_other_type)
        self.verticalLayout_36.addWidget(self.widget_71)
        self.verticalLayout.addWidget(self.widget_70)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.widget_84 = QtGui.QWidget(self.groupBox_5)
        self.widget_84.setObjectName("widget_84")
        self.verticalLayout_43 = QtGui.QVBoxLayout(self.widget_84)
        self.verticalLayout_43.setSpacing(4)
        self.verticalLayout_43.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.button_box = QtGui.QWidget(self.widget_84)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout = QtGui.QHBoxLayout(self.button_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self.horizontalLayout.addWidget(self.pbnCancel)
        spacerItem16 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.pbnFinished = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFinished.setFont(font)
        self.pbnFinished.setObjectName("pbnFinished")
        self.horizontalLayout.addWidget(self.pbnFinished)
        self.verticalLayout_43.addWidget(self.button_box)
        self.verticalLayout.addWidget(self.widget_84)
        self.horizontalLayout_3.addWidget(self.groupBox_5)

        self.retranslateUi(AdditionalQuestions)
        QtCore.QMetaObject.connectSlotsByName(AdditionalQuestions)
        AdditionalQuestions.setTabOrder(self.pct_house_inc, self.num_dependents)
        AdditionalQuestions.setTabOrder(self.num_dependents, self.num_crew)
        AdditionalQuestions.setTabOrder(self.num_crew, self.crew_shares)
        AdditionalQuestions.setTabOrder(self.crew_shares, self.boat_shares)
        AdditionalQuestions.setTabOrder(self.boat_shares, self.captain_shares)
        AdditionalQuestions.setTabOrder(self.captain_shares, self.owner_shares)
        AdditionalQuestions.setTabOrder(self.owner_shares, self.catch_personal)
        AdditionalQuestions.setTabOrder(self.catch_personal, self.catch_customers)
        AdditionalQuestions.setTabOrder(self.catch_customers, self.catch_hotel)
        AdditionalQuestions.setTabOrder(self.catch_hotel, self.catch_agency)
        AdditionalQuestions.setTabOrder(self.catch_agency, self.catch_other)
        AdditionalQuestions.setTabOrder(self.catch_other, self.catch_other_type)
        AdditionalQuestions.setTabOrder(self.catch_other_type, self.pbnFinished)
        AdditionalQuestions.setTabOrder(self.pbnFinished, self.pbnCancel)

    def retranslateUi(self, AdditionalQuestions):
        AdditionalQuestions.setWindowTitle(QtGui.QApplication.translate("AdditionalQuestions", "OpenOceanMap - Additional Questions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("AdditionalQuestions", "% of total household income from fishing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("AdditionalQuestions", "Number of household members (dependents):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("AdditionalQuestions", "Number of crew (not including self):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("AdditionalQuestions", "% or # shares to each crew member:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("AdditionalQuestions", "% or # shares to boat (include trip costs):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("AdditionalQuestions", "% or # shares to captain:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("AdditionalQuestions", "% or # shares to boat owner (if not captain):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("AdditionalQuestions", "% catch to individual or household (personal):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("AdditionalQuestions", "% catch to housewives/customers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("AdditionalQuestions", "% catch to hotels/restaurants:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("AdditionalQuestions", "% catch to fish agency facility (processor):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("AdditionalQuestions", "% catch to other (including direct export):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("AdditionalQuestions", "Define \"other\" above:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("AdditionalQuestions", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFinished.setText(QtGui.QApplication.translate("AdditionalQuestions", "Continue", None, QtGui.QApplication.UnicodeUTF8))

