# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interviewstart.ui'
#
# Created: Fri Feb 05 10:37:44 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_InterviewStart(object):
    def setupUi(self, InterviewStart):
        InterviewStart.setObjectName("InterviewStart")
        InterviewStart.resize(778, 616)
        self.verticalLayout_3 = QtGui.QVBoxLayout(InterviewStart)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.interviewee = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.interviewee.setFont(font)
        self.interviewee.setObjectName("interviewee")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.interviewee)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.interviewee_first_name = QtGui.QWidget(self.interviewee)
        self.interviewee_first_name.setObjectName("interviewee_first_name")
        self.hboxlayout = QtGui.QHBoxLayout(self.interviewee_first_name)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(4)
        self.hboxlayout.setObjectName("hboxlayout")
        self.interviewee_first_name_text = QtGui.QLabel(self.interviewee_first_name)
        self.interviewee_first_name_text.setMinimumSize(QtCore.QSize(100, 0))
        self.interviewee_first_name_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.interviewee_first_name_text.setObjectName("interviewee_first_name_text")
        self.hboxlayout.addWidget(self.interviewee_first_name_text)
        self.interviewee_first_name_line = QtGui.QLineEdit(self.interviewee_first_name)
        self.interviewee_first_name_line.setEnabled(True)
        self.interviewee_first_name_line.setMinimumSize(QtCore.QSize(200, 0))
        self.interviewee_first_name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.interviewee_first_name_line.setObjectName("interviewee_first_name_line")
        self.hboxlayout.addWidget(self.interviewee_first_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name)
        self.interviewee_last_name = QtGui.QWidget(self.interviewee)
        self.interviewee_last_name.setObjectName("interviewee_last_name")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.interviewee_last_name)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(4)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.interviewee_last_name_text = QtGui.QLabel(self.interviewee_last_name)
        self.interviewee_last_name_text.setMinimumSize(QtCore.QSize(100, 0))
        self.interviewee_last_name_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.interviewee_last_name_text.setObjectName("interviewee_last_name_text")
        self.hboxlayout1.addWidget(self.interviewee_last_name_text)
        self.interviewee_last_name_line = QtGui.QLineEdit(self.interviewee_last_name)
        self.interviewee_last_name_line.setEnabled(True)
        self.interviewee_last_name_line.setMinimumSize(QtCore.QSize(200, 0))
        self.interviewee_last_name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.interviewee_last_name_line.setObjectName("interviewee_last_name_line")
        self.hboxlayout1.addWidget(self.interviewee_last_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_last_name)
        self.address = QtGui.QWidget(self.interviewee)
        self.address.setObjectName("address")
        self._6 = QtGui.QHBoxLayout(self.address)
        self._6.setSpacing(4)
        self._6.setMargin(4)
        self._6.setObjectName("_6")
        self.city_text_3 = QtGui.QLabel(self.address)
        self.city_text_3.setMinimumSize(QtCore.QSize(100, 0))
        self.city_text_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.city_text_3.setObjectName("city_text_3")
        self._6.addWidget(self.city_text_3)
        self.address_line = QtGui.QLineEdit(self.address)
        self.address_line.setEnabled(True)
        self.address_line.setMinimumSize(QtCore.QSize(200, 0))
        self.address_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.address_line.setObjectName("address_line")
        self._6.addWidget(self.address_line)
        self.verticalLayout_2.addWidget(self.address)
        self.phone = QtGui.QWidget(self.interviewee)
        self.phone.setObjectName("phone")
        self._5 = QtGui.QHBoxLayout(self.phone)
        self._5.setSpacing(4)
        self._5.setMargin(4)
        self._5.setObjectName("_5")
        self.city_text_2 = QtGui.QLabel(self.phone)
        self.city_text_2.setMinimumSize(QtCore.QSize(100, 0))
        self.city_text_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.city_text_2.setObjectName("city_text_2")
        self._5.addWidget(self.city_text_2)
        self.phone_line = QtGui.QLineEdit(self.phone)
        self.phone_line.setEnabled(True)
        self.phone_line.setMinimumSize(QtCore.QSize(200, 0))
        self.phone_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.phone_line.setObjectName("phone_line")
        self._5.addWidget(self.phone_line)
        self.verticalLayout_2.addWidget(self.phone)
        self.email = QtGui.QWidget(self.interviewee)
        self.email.setObjectName("email")
        self._2 = QtGui.QHBoxLayout(self.email)
        self._2.setSpacing(4)
        self._2.setMargin(4)
        self._2.setObjectName("_2")
        self.city_text = QtGui.QLabel(self.email)
        self.city_text.setMinimumSize(QtCore.QSize(100, 0))
        self.city_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.city_text.setObjectName("city_text")
        self._2.addWidget(self.city_text)
        self.email_line = QtGui.QLineEdit(self.email)
        self.email_line.setEnabled(True)
        self.email_line.setMinimumSize(QtCore.QSize(200, 0))
        self.email_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.email_line.setObjectName("email_line")
        self._2.addWidget(self.email_line)
        self.verticalLayout_2.addWidget(self.email)
        self.gender = QtGui.QWidget(self.interviewee)
        self.gender.setObjectName("gender")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.gender)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.gender_text = QtGui.QLabel(self.gender)
        self.gender_text.setMinimumSize(QtCore.QSize(100, 0))
        self.gender_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gender_text.setObjectName("gender_text")
        self.hboxlayout2.addWidget(self.gender_text)
        self.gender_comboBox = QtGui.QComboBox(self.gender)
        self.gender_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.gender_comboBox.addItem(QtCore.QString())
        self.gender_comboBox.setItemText(0, "")
        self.gender_comboBox.addItem(QtCore.QString())
        self.gender_comboBox.addItem(QtCore.QString())
        self.hboxlayout2.addWidget(self.gender_comboBox)
        self.verticalLayout_2.addWidget(self.gender)
        self.age = QtGui.QWidget(self.interviewee)
        self.age.setObjectName("age")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.age)
        self.hboxlayout3.setSpacing(4)
        self.hboxlayout3.setMargin(4)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.age_text = QtGui.QLabel(self.age)
        self.age_text.setMinimumSize(QtCore.QSize(100, 0))
        self.age_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.age_text.setObjectName("age_text")
        self.hboxlayout3.addWidget(self.age_text)
        self.age_line = QtGui.QLineEdit(self.age)
        self.age_line.setEnabled(True)
        self.age_line.setMinimumSize(QtCore.QSize(200, 0))
        self.age_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.age_line.setObjectName("age_line")
        self.hboxlayout3.addWidget(self.age_line)
        self.verticalLayout_2.addWidget(self.age)
        self.verticalLayout_4.addWidget(self.interviewee)
        self.interviewee_2 = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.interviewee_2.setFont(font)
        self.interviewee_2.setObjectName("interviewee_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.interviewee_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.interviewee_first_name_2 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_2.setObjectName("interviewee_first_name_2")
        self._3 = QtGui.QHBoxLayout(self.interviewee_first_name_2)
        self._3.setSpacing(4)
        self._3.setMargin(4)
        self._3.setObjectName("_3")
        self.date_text = QtGui.QLabel(self.interviewee_first_name_2)
        self.date_text.setMinimumSize(QtCore.QSize(180, 0))
        self.date_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.date_text.setObjectName("date_text")
        self._3.addWidget(self.date_text)
        self.date_line = QtGui.QLineEdit(self.interviewee_first_name_2)
        self.date_line.setEnabled(True)
        self.date_line.setMinimumSize(QtCore.QSize(150, 0))
        self.date_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.date_line.setObjectName("date_line")
        self._3.addWidget(self.date_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_2)
        self.interviewee_first_name_3 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_3.setObjectName("interviewee_first_name_3")
        self._8 = QtGui.QHBoxLayout(self.interviewee_first_name_3)
        self._8.setSpacing(4)
        self._8.setMargin(4)
        self._8.setObjectName("_8")
        self.interviewer1_first_name_text = QtGui.QLabel(self.interviewee_first_name_3)
        self.interviewer1_first_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_first_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_first_name_text.setObjectName("interviewer1_first_name_text")
        self._8.addWidget(self.interviewer1_first_name_text)
        self.interviewer1_first_name_line = QtGui.QLineEdit(self.interviewee_first_name_3)
        self.interviewer1_first_name_line.setEnabled(True)
        self.interviewer1_first_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_first_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer1_first_name_line.setObjectName("interviewer1_first_name_line")
        self._8.addWidget(self.interviewer1_first_name_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_3)
        self.interviewee_first_name_4 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_4.setObjectName("interviewee_first_name_4")
        self._9 = QtGui.QHBoxLayout(self.interviewee_first_name_4)
        self._9.setSpacing(4)
        self._9.setMargin(4)
        self._9.setObjectName("_9")
        self.interviewer1_last_name_text = QtGui.QLabel(self.interviewee_first_name_4)
        self.interviewer1_last_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_last_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_last_name_text.setObjectName("interviewer1_last_name_text")
        self._9.addWidget(self.interviewer1_last_name_text)
        self.interviewer1_last_name_line = QtGui.QLineEdit(self.interviewee_first_name_4)
        self.interviewer1_last_name_line.setEnabled(True)
        self.interviewer1_last_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_last_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer1_last_name_line.setObjectName("interviewer1_last_name_line")
        self._9.addWidget(self.interviewer1_last_name_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_4)
        self.interviewee_first_name_5 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_5.setObjectName("interviewee_first_name_5")
        self._10 = QtGui.QHBoxLayout(self.interviewee_first_name_5)
        self._10.setSpacing(4)
        self._10.setMargin(4)
        self._10.setObjectName("_10")
        self.mood_text = QtGui.QLabel(self.interviewee_first_name_5)
        self.mood_text.setMinimumSize(QtCore.QSize(180, 0))
        self.mood_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.mood_text.setObjectName("mood_text")
        self._10.addWidget(self.mood_text)
        self.mood_line = QtGui.QLineEdit(self.interviewee_first_name_5)
        self.mood_line.setEnabled(True)
        self.mood_line.setMinimumSize(QtCore.QSize(150, 0))
        self.mood_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.mood_line.setObjectName("mood_line")
        self._10.addWidget(self.mood_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_5)
        self.interviewee_first_name_7 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_7.setObjectName("interviewee_first_name_7")
        self._13 = QtGui.QHBoxLayout(self.interviewee_first_name_7)
        self._13.setSpacing(4)
        self._13.setMargin(4)
        self._13.setObjectName("_13")
        self.mood_text_3 = QtGui.QLabel(self.interviewee_first_name_7)
        self.mood_text_3.setMinimumSize(QtCore.QSize(180, 0))
        self.mood_text_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.mood_text_3.setObjectName("mood_text_3")
        self._13.addWidget(self.mood_text_3)
        self.location_line = QtGui.QLineEdit(self.interviewee_first_name_7)
        self.location_line.setEnabled(True)
        self.location_line.setMinimumSize(QtCore.QSize(150, 0))
        self.location_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_line.setObjectName("location_line")
        self._13.addWidget(self.location_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_7)
        self.interviewee_first_name_6 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_6.setObjectName("interviewee_first_name_6")
        self._12 = QtGui.QHBoxLayout(self.interviewee_first_name_6)
        self._12.setSpacing(4)
        self._12.setMargin(4)
        self._12.setObjectName("_12")
        self.mood_text_2 = QtGui.QLabel(self.interviewee_first_name_6)
        self.mood_text_2.setMinimumSize(QtCore.QSize(180, 0))
        self.mood_text_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.mood_text_2.setObjectName("mood_text_2")
        self._12.addWidget(self.mood_text_2)
        self.dataMethod_comboBox = QtGui.QComboBox(self.interviewee_first_name_6)
        self.dataMethod_comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dataMethod_comboBox.setObjectName("dataMethod_comboBox")
        self.dataMethod_comboBox.addItem(QtCore.QString())
        self.dataMethod_comboBox.setItemText(0, "")
        self.dataMethod_comboBox.addItem(QtCore.QString())
        self.dataMethod_comboBox.addItem(QtCore.QString())
        self._12.addWidget(self.dataMethod_comboBox)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_6)
        self.verticalLayout_4.addWidget(self.interviewee_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.vessel_info = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_port_5 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_5.setFont(font)
        self.home_port_5.setObjectName("home_port_5")
        self._11 = QtGui.QHBoxLayout(self.home_port_5)
        self._11.setSpacing(4)
        self._11.setMargin(4)
        self._11.setObjectName("_11")
        self.years_text = QtGui.QLabel(self.home_port_5)
        self.years_text.setMinimumSize(QtCore.QSize(150, 0))
        self.years_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_text.setFont(font)
        self.years_text.setObjectName("years_text")
        self._11.addWidget(self.years_text)
        self.years_line = QtGui.QLineEdit(self.home_port_5)
        self.years_line.setEnabled(True)
        self.years_line.setMinimumSize(QtCore.QSize(100, 0))
        self.years_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_line.setFont(font)
        self.years_line.setObjectName("years_line")
        self._11.addWidget(self.years_line)
        self.verticalLayout.addWidget(self.home_port_5)
        self.home_port_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_2.setFont(font)
        self.home_port_2.setObjectName("home_port_2")
        self._4 = QtGui.QHBoxLayout(self.home_port_2)
        self._4.setSpacing(4)
        self._4.setMargin(4)
        self._4.setObjectName("_4")
        self.perc_income_text = QtGui.QLabel(self.home_port_2)
        self.perc_income_text.setMinimumSize(QtCore.QSize(150, 0))
        self.perc_income_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perc_income_text.setFont(font)
        self.perc_income_text.setObjectName("perc_income_text")
        self._4.addWidget(self.perc_income_text)
        self.perc_income_line = QtGui.QLineEdit(self.home_port_2)
        self.perc_income_line.setEnabled(True)
        self.perc_income_line.setMinimumSize(QtCore.QSize(100, 0))
        self.perc_income_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perc_income_line.setFont(font)
        self.perc_income_line.setObjectName("perc_income_line")
        self._4.addWidget(self.perc_income_line)
        self.verticalLayout.addWidget(self.home_port_2)
        self.home_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port.setFont(font)
        self.home_port.setObjectName("home_port")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.home_port)
        self.hboxlayout4.setSpacing(4)
        self.hboxlayout4.setMargin(4)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.home_port_text = QtGui.QLabel(self.home_port)
        self.home_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.home_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_text.setFont(font)
        self.home_port_text.setObjectName("home_port_text")
        self.hboxlayout4.addWidget(self.home_port_text)
        self.home_port_line = QtGui.QLineEdit(self.home_port)
        self.home_port_line.setEnabled(True)
        self.home_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.home_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_line.setFont(font)
        self.home_port_line.setObjectName("home_port_line")
        self.hboxlayout4.addWidget(self.home_port_line)
        self.verticalLayout.addWidget(self.home_port)
        self.home_port_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_4.setFont(font)
        self.home_port_4.setObjectName("home_port_4")
        self._7 = QtGui.QHBoxLayout(self.home_port_4)
        self._7.setSpacing(4)
        self._7.setMargin(4)
        self._7.setObjectName("_7")
        self.landing_port_text = QtGui.QLabel(self.home_port_4)
        self.landing_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text.setFont(font)
        self.landing_port_text.setObjectName("landing_port_text")
        self._7.addWidget(self.landing_port_text)
        self.landing_port_line = QtGui.QLineEdit(self.home_port_4)
        self.landing_port_line.setEnabled(True)
        self.landing_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line.setFont(font)
        self.landing_port_line.setObjectName("landing_port_line")
        self._7.addWidget(self.landing_port_line)
        self.verticalLayout.addWidget(self.home_port_4)
        self.home_port_7 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_7.setFont(font)
        self.home_port_7.setObjectName("home_port_7")
        self._16 = QtGui.QHBoxLayout(self.home_port_7)
        self._16.setSpacing(4)
        self._16.setMargin(4)
        self._16.setObjectName("_16")
        self.landing_port_text_2 = QtGui.QLabel(self.home_port_7)
        self.landing_port_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_2.setFont(font)
        self.landing_port_text_2.setObjectName("landing_port_text_2")
        self._16.addWidget(self.landing_port_text_2)
        self.landing_port_line_2 = QtGui.QLineEdit(self.home_port_7)
        self.landing_port_line_2.setEnabled(True)
        self.landing_port_line_2.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_2.setFont(font)
        self.landing_port_line_2.setObjectName("landing_port_line_2")
        self._16.addWidget(self.landing_port_line_2)
        self.verticalLayout.addWidget(self.home_port_7)
        self.home_port_8 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_8.setFont(font)
        self.home_port_8.setObjectName("home_port_8")
        self._17 = QtGui.QHBoxLayout(self.home_port_8)
        self._17.setSpacing(4)
        self._17.setMargin(4)
        self._17.setObjectName("_17")
        self.landing_port_text_3 = QtGui.QLabel(self.home_port_8)
        self.landing_port_text_3.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_3.setFont(font)
        self.landing_port_text_3.setObjectName("landing_port_text_3")
        self._17.addWidget(self.landing_port_text_3)
        self.landing_port_line_3 = QtGui.QLineEdit(self.home_port_8)
        self.landing_port_line_3.setEnabled(True)
        self.landing_port_line_3.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_3.setFont(font)
        self.landing_port_line_3.setObjectName("landing_port_line_3")
        self._17.addWidget(self.landing_port_line_3)
        self.verticalLayout.addWidget(self.home_port_8)
        self.home_port_9 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_9.setFont(font)
        self.home_port_9.setObjectName("home_port_9")
        self._18 = QtGui.QHBoxLayout(self.home_port_9)
        self._18.setSpacing(4)
        self._18.setMargin(4)
        self._18.setObjectName("_18")
        self.landing_port_text_4 = QtGui.QLabel(self.home_port_9)
        self.landing_port_text_4.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_4.setFont(font)
        self.landing_port_text_4.setObjectName("landing_port_text_4")
        self._18.addWidget(self.landing_port_text_4)
        self.landing_port_line_4 = QtGui.QLineEdit(self.home_port_9)
        self.landing_port_line_4.setEnabled(True)
        self.landing_port_line_4.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_4.setFont(font)
        self.landing_port_line_4.setObjectName("landing_port_line_4")
        self._18.addWidget(self.landing_port_line_4)
        self.verticalLayout.addWidget(self.home_port_9)
        self.horizontalLayout.addWidget(self.vessel_info)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.button_box = QtGui.QWidget(InterviewStart)
        self.button_box.setObjectName("button_box")
        self._19 = QtGui.QHBoxLayout(self.button_box)
        self._19.setSpacing(2)
        self._19.setMargin(2)
        self._19.setObjectName("_19")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._19.addItem(spacerItem)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self._19.addWidget(self.pbnCancel)
        self.pbnSelectFishery = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnSelectFishery.setFont(font)
        self.pbnSelectFishery.setObjectName("pbnSelectFishery")
        self._19.addWidget(self.pbnSelectFishery)
        self.verticalLayout_3.addWidget(self.button_box)

        self.retranslateUi(InterviewStart)
        QtCore.QMetaObject.connectSlotsByName(InterviewStart)
        InterviewStart.setTabOrder(self.interviewee_first_name_line, self.interviewee_last_name_line)
        InterviewStart.setTabOrder(self.interviewee_last_name_line, self.age_line)
        InterviewStart.setTabOrder(self.age_line, self.gender_comboBox)
        InterviewStart.setTabOrder(self.gender_comboBox, self.email_line)
        InterviewStart.setTabOrder(self.email_line, self.date_line)
        InterviewStart.setTabOrder(self.date_line, self.interviewer1_first_name_line)
        InterviewStart.setTabOrder(self.interviewer1_first_name_line, self.interviewer1_last_name_line)
        InterviewStart.setTabOrder(self.interviewer1_last_name_line, self.mood_line)
        InterviewStart.setTabOrder(self.mood_line, self.years_line)
        InterviewStart.setTabOrder(self.years_line, self.perc_income_line)
        InterviewStart.setTabOrder(self.perc_income_line, self.home_port_line)
        InterviewStart.setTabOrder(self.home_port_line, self.landing_port_line)
        InterviewStart.setTabOrder(self.landing_port_line, self.landing_port_line_2)
        InterviewStart.setTabOrder(self.landing_port_line_2, self.landing_port_line_3)
        InterviewStart.setTabOrder(self.landing_port_line_3, self.landing_port_line_4)
        InterviewStart.setTabOrder(self.landing_port_line_4, self.pbnSelectFishery)
        InterviewStart.setTabOrder(self.pbnSelectFishery, self.pbnCancel)

    def retranslateUi(self, InterviewStart):
        InterviewStart.setWindowTitle(QtGui.QApplication.translate("InterviewStart", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee.setTitle(QtGui.QApplication.translate("InterviewStart", "Interviewee", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_first_name_text.setText(QtGui.QApplication.translate("InterviewStart", "First Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_last_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Last Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.city_text_3.setText(QtGui.QApplication.translate("InterviewStart", "Mailing address:", None, QtGui.QApplication.UnicodeUTF8))
        self.city_text_2.setText(QtGui.QApplication.translate("InterviewStart", "Phone:", None, QtGui.QApplication.UnicodeUTF8))
        self.city_text.setText(QtGui.QApplication.translate("InterviewStart", "Email:", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_text.setText(QtGui.QApplication.translate("InterviewStart", "Gender:", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_comboBox.setItemText(1, QtGui.QApplication.translate("InterviewStart", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_comboBox.setItemText(2, QtGui.QApplication.translate("InterviewStart", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.age_text.setText(QtGui.QApplication.translate("InterviewStart", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_2.setTitle(QtGui.QApplication.translate("InterviewStart", "Interviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.date_text.setText(QtGui.QApplication.translate("InterviewStart", "Interview Date (mm/dd/yyyy):", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_first_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Interviewer First Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_last_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Interviewer Last Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.mood_text.setText(QtGui.QApplication.translate("InterviewStart", "Interviewer Mood:", None, QtGui.QApplication.UnicodeUTF8))
        self.mood_text_3.setText(QtGui.QApplication.translate("InterviewStart", "Interviewer Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.mood_text_2.setText(QtGui.QApplication.translate("InterviewStart", "Data collection method:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataMethod_comboBox.setItemText(1, QtGui.QApplication.translate("InterviewStart", "electronic", None, QtGui.QApplication.UnicodeUTF8))
        self.dataMethod_comboBox.setItemText(2, QtGui.QApplication.translate("InterviewStart", "hard copy", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("InterviewStart", "Commercial Fishing Information", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text.setText(QtGui.QApplication.translate("InterviewStart", "Years experience:", None, QtGui.QApplication.UnicodeUTF8))
        self.perc_income_text.setText(QtGui.QApplication.translate("InterviewStart", "% income from fishing:", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text.setText(QtGui.QApplication.translate("InterviewStart", "Home Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_2.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_3.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_4.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("InterviewStart", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectFishery.setText(QtGui.QApplication.translate("InterviewStart", "Select Fishery", None, QtGui.QApplication.UnicodeUTF8))

