# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interviewstart.ui'
#
# Created: Mon Apr 26 11:40:57 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_InterviewStart(object):
    def setupUi(self, InterviewStart):
        InterviewStart.setObjectName("InterviewStart")
        InterviewStart.resize(388, 375)
        self.verticalLayout_3 = QtGui.QVBoxLayout(InterviewStart)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.interviewee_2 = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.interviewee_2.setFont(font)
        self.interviewee_2.setObjectName("interviewee_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.interviewee_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.interviewee_first_name_2 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_2.setObjectName("interviewee_first_name_2")
        self._3 = QtGui.QHBoxLayout(self.interviewee_first_name_2)
        self._3.setSpacing(4)
        self._3.setMargin(4)
        self._3.setObjectName("_3")
        self.date_text = QtGui.QLabel(self.interviewee_first_name_2)
        self.date_text.setMinimumSize(QtCore.QSize(180, 0))
        self.date_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.date_text.setObjectName("date_text")
        self._3.addWidget(self.date_text)
        self.date_line = QtGui.QLineEdit(self.interviewee_first_name_2)
        self.date_line.setEnabled(True)
        self.date_line.setMinimumSize(QtCore.QSize(150, 0))
        self.date_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.date_line.setObjectName("date_line")
        self._3.addWidget(self.date_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name_2)
        self.interviewee_first_name_8 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_8.setObjectName("interviewee_first_name_8")
        self._23 = QtGui.QHBoxLayout(self.interviewee_first_name_8)
        self._23.setSpacing(4)
        self._23.setMargin(4)
        self._23.setObjectName("_23")
        self.interviewer1_first_name_text_2 = QtGui.QLabel(self.interviewee_first_name_8)
        self.interviewer1_first_name_text_2.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_first_name_text_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_first_name_text_2.setObjectName("interviewer1_first_name_text_2")
        self._23.addWidget(self.interviewer1_first_name_text_2)
        self.interviewer1_first_name_line = QtGui.QLineEdit(self.interviewee_first_name_8)
        self.interviewer1_first_name_line.setEnabled(True)
        self.interviewer1_first_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_first_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer1_first_name_line.setObjectName("interviewer1_first_name_line")
        self._23.addWidget(self.interviewer1_first_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name_8)
        self.interviewee_first_name_9 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_9.setObjectName("interviewee_first_name_9")
        self._24 = QtGui.QHBoxLayout(self.interviewee_first_name_9)
        self._24.setSpacing(4)
        self._24.setMargin(4)
        self._24.setObjectName("_24")
        self.interviewer1_first_name_text_3 = QtGui.QLabel(self.interviewee_first_name_9)
        self.interviewer1_first_name_text_3.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_first_name_text_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_first_name_text_3.setObjectName("interviewer1_first_name_text_3")
        self._24.addWidget(self.interviewer1_first_name_text_3)
        self.interviewer1_last_name_line = QtGui.QLineEdit(self.interviewee_first_name_9)
        self.interviewer1_last_name_line.setEnabled(True)
        self.interviewer1_last_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_last_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer1_last_name_line.setObjectName("interviewer1_last_name_line")
        self._24.addWidget(self.interviewer1_last_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name_9)
        self.interviewee_first_name_3 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_3.setObjectName("interviewee_first_name_3")
        self._8 = QtGui.QHBoxLayout(self.interviewee_first_name_3)
        self._8.setSpacing(4)
        self._8.setMargin(4)
        self._8.setObjectName("_8")
        self.interviewer1_first_name_text = QtGui.QLabel(self.interviewee_first_name_3)
        self.interviewer1_first_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_first_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_first_name_text.setObjectName("interviewer1_first_name_text")
        self._8.addWidget(self.interviewer1_first_name_text)
        self.interviewer2_first_name_line = QtGui.QLineEdit(self.interviewee_first_name_3)
        self.interviewer2_first_name_line.setEnabled(True)
        self.interviewer2_first_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer2_first_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer2_first_name_line.setObjectName("interviewer2_first_name_line")
        self._8.addWidget(self.interviewer2_first_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name_3)
        self.interviewee_first_name_4 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_4.setObjectName("interviewee_first_name_4")
        self._9 = QtGui.QHBoxLayout(self.interviewee_first_name_4)
        self._9.setSpacing(4)
        self._9.setMargin(4)
        self._9.setObjectName("_9")
        self.interviewer1_last_name_text = QtGui.QLabel(self.interviewee_first_name_4)
        self.interviewer1_last_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_last_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_last_name_text.setObjectName("interviewer1_last_name_text")
        self._9.addWidget(self.interviewer1_last_name_text)
        self.interviewer2_last_name_line = QtGui.QLineEdit(self.interviewee_first_name_4)
        self.interviewer2_last_name_line.setEnabled(True)
        self.interviewer2_last_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer2_last_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer2_last_name_line.setObjectName("interviewer2_last_name_line")
        self._9.addWidget(self.interviewer2_last_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name_4)
        self.interviewee_first_name_7 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_7.setObjectName("interviewee_first_name_7")
        self._13 = QtGui.QHBoxLayout(self.interviewee_first_name_7)
        self._13.setSpacing(4)
        self._13.setMargin(4)
        self._13.setObjectName("_13")
        self.mood_text_3 = QtGui.QLabel(self.interviewee_first_name_7)
        self.mood_text_3.setMinimumSize(QtCore.QSize(180, 0))
        self.mood_text_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.mood_text_3.setObjectName("mood_text_3")
        self._13.addWidget(self.mood_text_3)
        self.location_line = QtGui.QLineEdit(self.interviewee_first_name_7)
        self.location_line.setEnabled(True)
        self.location_line.setMinimumSize(QtCore.QSize(150, 0))
        self.location_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_line.setObjectName("location_line")
        self._13.addWidget(self.location_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name_7)
        self.interviewee_first_name_6 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_6.setObjectName("interviewee_first_name_6")
        self._12 = QtGui.QHBoxLayout(self.interviewee_first_name_6)
        self._12.setSpacing(4)
        self._12.setMargin(4)
        self._12.setObjectName("_12")
        self.mood_text_2 = QtGui.QLabel(self.interviewee_first_name_6)
        self.mood_text_2.setMinimumSize(QtCore.QSize(180, 0))
        self.mood_text_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.mood_text_2.setObjectName("mood_text_2")
        self._12.addWidget(self.mood_text_2)
        self.dataMethod_comboBox = QtGui.QComboBox(self.interviewee_first_name_6)
        self.dataMethod_comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dataMethod_comboBox.setObjectName("dataMethod_comboBox")
        self.dataMethod_comboBox.addItem(QtCore.QString())
        self.dataMethod_comboBox.setItemText(0, "")
        self.dataMethod_comboBox.addItem(QtCore.QString())
        self.dataMethod_comboBox.addItem(QtCore.QString())
        self._12.addWidget(self.dataMethod_comboBox)
        self.verticalLayout_2.addWidget(self.interviewee_first_name_6)
        self.home_port_13 = QtGui.QWidget(self.interviewee_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_13.setFont(font)
        self.home_port_13.setObjectName("home_port_13")
        self._22 = QtGui.QHBoxLayout(self.home_port_13)
        self._22.setSpacing(4)
        self._22.setMargin(4)
        self._22.setObjectName("_22")
        self.years_text_6 = QtGui.QLabel(self.home_port_13)
        self.years_text_6.setMinimumSize(QtCore.QSize(170, 0))
        self.years_text_6.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_text_6.setFont(font)
        self.years_text_6.setObjectName("years_text_6")
        self._22.addWidget(self.years_text_6)
        self.fish_regis_line = QtGui.QLineEdit(self.home_port_13)
        self.fish_regis_line.setEnabled(True)
        self.fish_regis_line.setMinimumSize(QtCore.QSize(150, 0))
        self.fish_regis_line.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_regis_line.setFont(font)
        self.fish_regis_line.setObjectName("fish_regis_line")
        self._22.addWidget(self.fish_regis_line)
        self.verticalLayout_2.addWidget(self.home_port_13)
        self.button_box = QtGui.QWidget(self.interviewee_2)
        self.button_box.setObjectName("button_box")
        self._19 = QtGui.QHBoxLayout(self.button_box)
        self._19.setSpacing(2)
        self._19.setMargin(2)
        self._19.setObjectName("_19")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._19.addItem(spacerItem)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self._19.addWidget(self.pbnCancel)
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._19.addItem(spacerItem1)
        self.pbnSelectFishery = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnSelectFishery.setFont(font)
        self.pbnSelectFishery.setObjectName("pbnSelectFishery")
        self._19.addWidget(self.pbnSelectFishery)
        self.verticalLayout_2.addWidget(self.button_box)
        self.verticalLayout_4.addWidget(self.interviewee_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(InterviewStart)
        QtCore.QMetaObject.connectSlotsByName(InterviewStart)
        InterviewStart.setTabOrder(self.date_line, self.interviewer1_first_name_line)
        InterviewStart.setTabOrder(self.interviewer1_first_name_line, self.interviewer1_last_name_line)
        InterviewStart.setTabOrder(self.interviewer1_last_name_line, self.interviewer2_first_name_line)
        InterviewStart.setTabOrder(self.interviewer2_first_name_line, self.interviewer2_last_name_line)
        InterviewStart.setTabOrder(self.interviewer2_last_name_line, self.location_line)
        InterviewStart.setTabOrder(self.location_line, self.dataMethod_comboBox)
        InterviewStart.setTabOrder(self.dataMethod_comboBox, self.fish_regis_line)
        InterviewStart.setTabOrder(self.fish_regis_line, self.pbnSelectFishery)
        InterviewStart.setTabOrder(self.pbnSelectFishery, self.pbnCancel)

    def retranslateUi(self, InterviewStart):
        InterviewStart.setWindowTitle(QtGui.QApplication.translate("InterviewStart", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.date_text.setText(QtGui.QApplication.translate("InterviewStart", "1. Interview date (dd/mm/yyyy):", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_first_name_text_2.setText(QtGui.QApplication.translate("InterviewStart", "2. Interviewer 1 first name:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_first_name_text_3.setText(QtGui.QApplication.translate("InterviewStart", "3. Interviewer 1 last name:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_first_name_text.setText(QtGui.QApplication.translate("InterviewStart", "4. Interviewer 2 first name:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_last_name_text.setText(QtGui.QApplication.translate("InterviewStart", "5. Interviewer 2 last name:", None, QtGui.QApplication.UnicodeUTF8))
        self.mood_text_3.setText(QtGui.QApplication.translate("InterviewStart", "6. Interview location:", None, QtGui.QApplication.UnicodeUTF8))
        self.mood_text_2.setText(QtGui.QApplication.translate("InterviewStart", "7. Data collection method:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataMethod_comboBox.setItemText(1, QtGui.QApplication.translate("InterviewStart", "electronic", None, QtGui.QApplication.UnicodeUTF8))
        self.dataMethod_comboBox.setItemText(2, QtGui.QApplication.translate("InterviewStart", "hard copy", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text_6.setText(QtGui.QApplication.translate("InterviewStart", "8. Fisher registration #:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("InterviewStart", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectFishery.setText(QtGui.QApplication.translate("InterviewStart", "Continue", None, QtGui.QApplication.UnicodeUTF8))

