# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rec_cpfv.ui'
#
# Created: Thu Apr 22 10:10:55 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RecCpfv(object):
    def setupUi(self, RecCpfv):
        RecCpfv.setObjectName("RecCpfv")
        RecCpfv.setWindowModality(QtCore.Qt.WindowModal)
        RecCpfv.resize(752, 453)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(RecCpfv)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtGui.QGroupBox(RecCpfv)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_57 = QtGui.QWidget(self.groupBox_4)
        self.widget_57.setObjectName("widget_57")
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.widget_57)
        self.verticalLayout_28.setSpacing(4)
        self.verticalLayout_28.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.widget_58 = QtGui.QWidget(self.widget_57)
        self.widget_58.setObjectName("widget_58")
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.widget_58)
        self.horizontalLayout_37.setSpacing(4)
        self.horizontalLayout_37.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_42 = QtGui.QLabel(self.widget_58)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_37.addWidget(self.label_42)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem)
        self.fish_pct_1 = QtGui.QLineEdit(self.widget_58)
        self.fish_pct_1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_1.setFont(font)
        self.fish_pct_1.setObjectName("fish_pct_1")
        self.horizontalLayout_37.addWidget(self.fish_pct_1)
        self.verticalLayout_28.addWidget(self.widget_58)
        self.verticalLayout_2.addWidget(self.widget_57)
        self.widget_59 = QtGui.QWidget(self.groupBox_4)
        self.widget_59.setObjectName("widget_59")
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.widget_59)
        self.verticalLayout_29.setSpacing(4)
        self.verticalLayout_29.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.widget_60 = QtGui.QWidget(self.widget_59)
        self.widget_60.setObjectName("widget_60")
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.widget_60)
        self.horizontalLayout_38.setSpacing(4)
        self.horizontalLayout_38.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_43 = QtGui.QLabel(self.widget_60)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_38.addWidget(self.label_43)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem1)
        self.fish_pct_2 = QtGui.QLineEdit(self.widget_60)
        self.fish_pct_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_2.setFont(font)
        self.fish_pct_2.setObjectName("fish_pct_2")
        self.horizontalLayout_38.addWidget(self.fish_pct_2)
        self.verticalLayout_29.addWidget(self.widget_60)
        self.verticalLayout_2.addWidget(self.widget_59)
        self.widget_61 = QtGui.QWidget(self.groupBox_4)
        self.widget_61.setObjectName("widget_61")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.widget_61)
        self.verticalLayout_30.setSpacing(4)
        self.verticalLayout_30.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.widget_62 = QtGui.QWidget(self.widget_61)
        self.widget_62.setObjectName("widget_62")
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.widget_62)
        self.horizontalLayout_39.setSpacing(4)
        self.horizontalLayout_39.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_44 = QtGui.QLabel(self.widget_62)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_39.addWidget(self.label_44)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem2)
        self.fish_pct_3 = QtGui.QLineEdit(self.widget_62)
        self.fish_pct_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_3.setFont(font)
        self.fish_pct_3.setObjectName("fish_pct_3")
        self.horizontalLayout_39.addWidget(self.fish_pct_3)
        self.verticalLayout_30.addWidget(self.widget_62)
        self.verticalLayout_2.addWidget(self.widget_61)
        self.widget_24 = QtGui.QWidget(self.groupBox_4)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.widget_24)
        self.verticalLayout_14.setSpacing(4)
        self.verticalLayout_14.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_26 = QtGui.QWidget(self.widget_24)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_26)
        self.horizontalLayout_23.setSpacing(4)
        self.horizontalLayout_23.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtGui.QLabel(self.widget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        spacerItem3 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem3)
        self.fish_pct_4 = QtGui.QLineEdit(self.widget_26)
        self.fish_pct_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_4.setFont(font)
        self.fish_pct_4.setObjectName("fish_pct_4")
        self.horizontalLayout_23.addWidget(self.fish_pct_4)
        self.verticalLayout_14.addWidget(self.widget_26)
        self.verticalLayout_2.addWidget(self.widget_24)
        self.widget_32 = QtGui.QWidget(self.groupBox_4)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.widget_32)
        self.verticalLayout_16.setSpacing(4)
        self.verticalLayout_16.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_34 = QtGui.QWidget(self.widget_32)
        self.widget_34.setObjectName("widget_34")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.widget_34)
        self.horizontalLayout_25.setSpacing(4)
        self.horizontalLayout_25.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_30 = QtGui.QLabel(self.widget_34)
        self.label_30.setMinimumSize(QtCore.QSize(250, 0))
        self.label_30.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem4)
        self.fish_pct_5 = QtGui.QLineEdit(self.widget_34)
        self.fish_pct_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_5.setFont(font)
        self.fish_pct_5.setObjectName("fish_pct_5")
        self.horizontalLayout_25.addWidget(self.fish_pct_5)
        self.verticalLayout_16.addWidget(self.widget_34)
        self.verticalLayout_2.addWidget(self.widget_32)
        self.widget_35 = QtGui.QWidget(self.groupBox_4)
        self.widget_35.setObjectName("widget_35")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.widget_35)
        self.verticalLayout_17.setSpacing(4)
        self.verticalLayout_17.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_36 = QtGui.QWidget(self.widget_35)
        self.widget_36.setObjectName("widget_36")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.widget_36)
        self.horizontalLayout_26.setSpacing(4)
        self.horizontalLayout_26.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_31 = QtGui.QLabel(self.widget_36)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_26.addWidget(self.label_31)
        spacerItem5 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem5)
        self.fish_pct_6 = QtGui.QLineEdit(self.widget_36)
        self.fish_pct_6.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_6.setFont(font)
        self.fish_pct_6.setObjectName("fish_pct_6")
        self.horizontalLayout_26.addWidget(self.fish_pct_6)
        self.verticalLayout_17.addWidget(self.widget_36)
        self.verticalLayout_2.addWidget(self.widget_35)
        self.widget_37 = QtGui.QWidget(self.groupBox_4)
        self.widget_37.setObjectName("widget_37")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.widget_37)
        self.verticalLayout_18.setSpacing(4)
        self.verticalLayout_18.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_38 = QtGui.QWidget(self.widget_37)
        self.widget_38.setObjectName("widget_38")
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.widget_38)
        self.horizontalLayout_27.setSpacing(4)
        self.horizontalLayout_27.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_32 = QtGui.QLabel(self.widget_38)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_27.addWidget(self.label_32)
        spacerItem6 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem6)
        self.fish_pct_7 = QtGui.QLineEdit(self.widget_38)
        self.fish_pct_7.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_7.setFont(font)
        self.fish_pct_7.setObjectName("fish_pct_7")
        self.horizontalLayout_27.addWidget(self.fish_pct_7)
        self.verticalLayout_18.addWidget(self.widget_38)
        self.verticalLayout_2.addWidget(self.widget_37)
        self.widget_39 = QtGui.QWidget(self.groupBox_4)
        self.widget_39.setObjectName("widget_39")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.widget_39)
        self.verticalLayout_19.setSpacing(4)
        self.verticalLayout_19.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_40 = QtGui.QWidget(self.widget_39)
        self.widget_40.setObjectName("widget_40")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.widget_40)
        self.horizontalLayout_28.setSpacing(4)
        self.horizontalLayout_28.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_33 = QtGui.QLabel(self.widget_40)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_28.addWidget(self.label_33)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem7)
        self.fish_pct_8 = QtGui.QLineEdit(self.widget_40)
        self.fish_pct_8.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_8.setFont(font)
        self.fish_pct_8.setObjectName("fish_pct_8")
        self.horizontalLayout_28.addWidget(self.fish_pct_8)
        self.verticalLayout_19.addWidget(self.widget_40)
        self.verticalLayout_2.addWidget(self.widget_39)
        self.widget_41 = QtGui.QWidget(self.groupBox_4)
        self.widget_41.setObjectName("widget_41")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.widget_41)
        self.verticalLayout_20.setSpacing(4)
        self.verticalLayout_20.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_42 = QtGui.QWidget(self.widget_41)
        self.widget_42.setObjectName("widget_42")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.widget_42)
        self.horizontalLayout_29.setSpacing(4)
        self.horizontalLayout_29.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_34 = QtGui.QLabel(self.widget_42)
        self.label_34.setMinimumSize(QtCore.QSize(270, 0))
        self.label_34.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_29.addWidget(self.label_34)
        spacerItem8 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem8)
        self.fish_pct_9 = QtGui.QLineEdit(self.widget_42)
        self.fish_pct_9.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_9.setFont(font)
        self.fish_pct_9.setObjectName("fish_pct_9")
        self.horizontalLayout_29.addWidget(self.fish_pct_9)
        self.verticalLayout_20.addWidget(self.widget_42)
        self.verticalLayout_2.addWidget(self.widget_41)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(RecCpfv)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_63 = QtGui.QWidget(self.groupBox_5)
        self.widget_63.setObjectName("widget_63")
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.widget_63)
        self.verticalLayout_31.setSpacing(4)
        self.verticalLayout_31.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.widget_64 = QtGui.QWidget(self.widget_63)
        self.widget_64.setObjectName("widget_64")
        self.horizontalLayout_40 = QtGui.QHBoxLayout(self.widget_64)
        self.horizontalLayout_40.setSpacing(4)
        self.horizontalLayout_40.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_45 = QtGui.QLabel(self.widget_64)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_40.addWidget(self.label_45)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem10)
        self.fish_pct_10 = QtGui.QLineEdit(self.widget_64)
        self.fish_pct_10.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_10.setFont(font)
        self.fish_pct_10.setObjectName("fish_pct_10")
        self.horizontalLayout_40.addWidget(self.fish_pct_10)
        self.verticalLayout_31.addWidget(self.widget_64)
        self.verticalLayout.addWidget(self.widget_63)
        self.widget_65 = QtGui.QWidget(self.groupBox_5)
        self.widget_65.setObjectName("widget_65")
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.widget_65)
        self.verticalLayout_32.setSpacing(4)
        self.verticalLayout_32.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.widget_66 = QtGui.QWidget(self.widget_65)
        self.widget_66.setObjectName("widget_66")
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.widget_66)
        self.horizontalLayout_41.setSpacing(4)
        self.horizontalLayout_41.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_46 = QtGui.QLabel(self.widget_66)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_41.addWidget(self.label_46)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem11)
        self.fish_pct_11 = QtGui.QLineEdit(self.widget_66)
        self.fish_pct_11.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_11.setFont(font)
        self.fish_pct_11.setObjectName("fish_pct_11")
        self.horizontalLayout_41.addWidget(self.fish_pct_11)
        self.verticalLayout_32.addWidget(self.widget_66)
        self.verticalLayout.addWidget(self.widget_65)
        self.widget_67 = QtGui.QWidget(self.groupBox_5)
        self.widget_67.setObjectName("widget_67")
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.widget_67)
        self.verticalLayout_33.setSpacing(4)
        self.verticalLayout_33.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.widget_68 = QtGui.QWidget(self.widget_67)
        self.widget_68.setObjectName("widget_68")
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.widget_68)
        self.horizontalLayout_42.setSpacing(4)
        self.horizontalLayout_42.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_47 = QtGui.QLabel(self.widget_68)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_42.addWidget(self.label_47)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem12)
        self.fish_pct_12 = QtGui.QLineEdit(self.widget_68)
        self.fish_pct_12.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_12.setFont(font)
        self.fish_pct_12.setObjectName("fish_pct_12")
        self.horizontalLayout_42.addWidget(self.fish_pct_12)
        self.verticalLayout_33.addWidget(self.widget_68)
        self.verticalLayout.addWidget(self.widget_67)
        self.widget_25 = QtGui.QWidget(self.groupBox_5)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.widget_25)
        self.verticalLayout_34.setSpacing(4)
        self.verticalLayout_34.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.widget_27 = QtGui.QWidget(self.widget_25)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.widget_27)
        self.horizontalLayout_43.setSpacing(4)
        self.horizontalLayout_43.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_48 = QtGui.QLabel(self.widget_27)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_43.addWidget(self.label_48)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem13)
        self.fish_pct_13 = QtGui.QLineEdit(self.widget_27)
        self.fish_pct_13.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_13.setFont(font)
        self.fish_pct_13.setObjectName("fish_pct_13")
        self.horizontalLayout_43.addWidget(self.fish_pct_13)
        self.verticalLayout_34.addWidget(self.widget_27)
        self.verticalLayout.addWidget(self.widget_25)
        self.widget_33 = QtGui.QWidget(self.groupBox_5)
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.widget_33)
        self.verticalLayout_35.setSpacing(4)
        self.verticalLayout_35.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.widget_69 = QtGui.QWidget(self.widget_33)
        self.widget_69.setObjectName("widget_69")
        self.horizontalLayout_44 = QtGui.QHBoxLayout(self.widget_69)
        self.horizontalLayout_44.setSpacing(4)
        self.horizontalLayout_44.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_49 = QtGui.QLabel(self.widget_69)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_44.addWidget(self.label_49)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem14)
        self.fish_pct_14 = QtGui.QLineEdit(self.widget_69)
        self.fish_pct_14.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_14.setFont(font)
        self.fish_pct_14.setObjectName("fish_pct_14")
        self.horizontalLayout_44.addWidget(self.fish_pct_14)
        self.verticalLayout_35.addWidget(self.widget_69)
        self.verticalLayout.addWidget(self.widget_33)
        self.widget_70 = QtGui.QWidget(self.groupBox_5)
        self.widget_70.setObjectName("widget_70")
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.widget_70)
        self.verticalLayout_36.setSpacing(4)
        self.verticalLayout_36.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.widget_71 = QtGui.QWidget(self.widget_70)
        self.widget_71.setObjectName("widget_71")
        self.horizontalLayout_45 = QtGui.QHBoxLayout(self.widget_71)
        self.horizontalLayout_45.setSpacing(4)
        self.horizontalLayout_45.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_50 = QtGui.QLabel(self.widget_71)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_45.addWidget(self.label_50)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem15)
        self.fish_pct_15 = QtGui.QLineEdit(self.widget_71)
        self.fish_pct_15.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_15.setFont(font)
        self.fish_pct_15.setObjectName("fish_pct_15")
        self.horizontalLayout_45.addWidget(self.fish_pct_15)
        self.verticalLayout_36.addWidget(self.widget_71)
        self.verticalLayout.addWidget(self.widget_70)
        self.widget_72 = QtGui.QWidget(self.groupBox_5)
        self.widget_72.setObjectName("widget_72")
        self.verticalLayout_37 = QtGui.QVBoxLayout(self.widget_72)
        self.verticalLayout_37.setSpacing(4)
        self.verticalLayout_37.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.widget_73 = QtGui.QWidget(self.widget_72)
        self.widget_73.setObjectName("widget_73")
        self.horizontalLayout_46 = QtGui.QHBoxLayout(self.widget_73)
        self.horizontalLayout_46.setSpacing(4)
        self.horizontalLayout_46.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_51 = QtGui.QLabel(self.widget_73)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_46.addWidget(self.label_51)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem16)
        self.fish_pct_16 = QtGui.QLineEdit(self.widget_73)
        self.fish_pct_16.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_16.setFont(font)
        self.fish_pct_16.setObjectName("fish_pct_16")
        self.horizontalLayout_46.addWidget(self.fish_pct_16)
        self.verticalLayout_37.addWidget(self.widget_73)
        self.verticalLayout.addWidget(self.widget_72)
        self.widget_74 = QtGui.QWidget(self.groupBox_5)
        self.widget_74.setObjectName("widget_74")
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.widget_74)
        self.verticalLayout_38.setSpacing(4)
        self.verticalLayout_38.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.widget_75 = QtGui.QWidget(self.widget_74)
        self.widget_75.setObjectName("widget_75")
        self.horizontalLayout_47 = QtGui.QHBoxLayout(self.widget_75)
        self.horizontalLayout_47.setSpacing(4)
        self.horizontalLayout_47.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_52 = QtGui.QLabel(self.widget_75)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setWordWrap(False)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_47.addWidget(self.label_52)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem17)
        self.fish_pct_17 = QtGui.QLineEdit(self.widget_75)
        self.fish_pct_17.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_17.setFont(font)
        self.fish_pct_17.setObjectName("fish_pct_17")
        self.horizontalLayout_47.addWidget(self.fish_pct_17)
        self.verticalLayout_38.addWidget(self.widget_75)
        self.verticalLayout.addWidget(self.widget_74)
        self.widget_76 = QtGui.QWidget(self.groupBox_5)
        self.widget_76.setObjectName("widget_76")
        self.verticalLayout_39 = QtGui.QVBoxLayout(self.widget_76)
        self.verticalLayout_39.setSpacing(4)
        self.verticalLayout_39.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.widget_77 = QtGui.QWidget(self.widget_76)
        self.widget_77.setObjectName("widget_77")
        self.horizontalLayout_48 = QtGui.QHBoxLayout(self.widget_77)
        self.horizontalLayout_48.setSpacing(4)
        self.horizontalLayout_48.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_53 = QtGui.QLabel(self.widget_77)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_48.addWidget(self.label_53)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem18)
        self.fish_pct_18 = QtGui.QLineEdit(self.widget_77)
        self.fish_pct_18.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_18.setFont(font)
        self.fish_pct_18.setObjectName("fish_pct_18")
        self.horizontalLayout_48.addWidget(self.fish_pct_18)
        self.verticalLayout_39.addWidget(self.widget_77)
        self.verticalLayout.addWidget(self.widget_76)
        self.widget_80 = QtGui.QWidget(self.groupBox_5)
        self.widget_80.setObjectName("widget_80")
        self.verticalLayout_41 = QtGui.QVBoxLayout(self.widget_80)
        self.verticalLayout_41.setSpacing(4)
        self.verticalLayout_41.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.widget_81 = QtGui.QWidget(self.widget_80)
        self.widget_81.setObjectName("widget_81")
        self.horizontalLayout_50 = QtGui.QHBoxLayout(self.widget_81)
        self.horizontalLayout_50.setSpacing(4)
        self.horizontalLayout_50.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_55 = QtGui.QLabel(self.widget_81)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_50.addWidget(self.label_55)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem19)
        self.fish_pct_19 = QtGui.QLineEdit(self.widget_81)
        self.fish_pct_19.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_19.setFont(font)
        self.fish_pct_19.setObjectName("fish_pct_19")
        self.horizontalLayout_50.addWidget(self.fish_pct_19)
        self.verticalLayout_41.addWidget(self.widget_81)
        self.verticalLayout.addWidget(self.widget_80)
        self.widget_78 = QtGui.QWidget(self.groupBox_5)
        self.widget_78.setObjectName("widget_78")
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.widget_78)
        self.verticalLayout_40.setSpacing(4)
        self.verticalLayout_40.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.widget_79 = QtGui.QWidget(self.widget_78)
        self.widget_79.setObjectName("widget_79")
        self.horizontalLayout_49 = QtGui.QHBoxLayout(self.widget_79)
        self.horizontalLayout_49.setSpacing(4)
        self.horizontalLayout_49.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_54 = QtGui.QLabel(self.widget_79)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_49.addWidget(self.label_54)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem20)
        self.fish_pct_20 = QtGui.QLineEdit(self.widget_79)
        self.fish_pct_20.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_20.setFont(font)
        self.fish_pct_20.setObjectName("fish_pct_20")
        self.horizontalLayout_49.addWidget(self.fish_pct_20)
        self.verticalLayout_40.addWidget(self.widget_79)
        self.verticalLayout.addWidget(self.widget_78)
        self.widget_84 = QtGui.QWidget(self.groupBox_5)
        self.widget_84.setObjectName("widget_84")
        self.verticalLayout_43 = QtGui.QVBoxLayout(self.widget_84)
        self.verticalLayout_43.setSpacing(4)
        self.verticalLayout_43.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.button_box = QtGui.QWidget(self.widget_84)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout = QtGui.QHBoxLayout(self.button_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self.horizontalLayout.addWidget(self.pbnCancel)
        spacerItem22 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.pbnFinished = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFinished.setFont(font)
        self.pbnFinished.setObjectName("pbnFinished")
        self.horizontalLayout.addWidget(self.pbnFinished)
        self.verticalLayout_43.addWidget(self.button_box)
        self.verticalLayout.addWidget(self.widget_84)
        self.horizontalLayout_3.addWidget(self.groupBox_5)

        self.retranslateUi(RecCpfv)
        QtCore.QMetaObject.connectSlotsByName(RecCpfv)
        RecCpfv.setTabOrder(self.fish_pct_1, self.fish_pct_2)
        RecCpfv.setTabOrder(self.fish_pct_2, self.fish_pct_3)
        RecCpfv.setTabOrder(self.fish_pct_3, self.fish_pct_4)
        RecCpfv.setTabOrder(self.fish_pct_4, self.fish_pct_5)
        RecCpfv.setTabOrder(self.fish_pct_5, self.fish_pct_6)
        RecCpfv.setTabOrder(self.fish_pct_6, self.fish_pct_7)
        RecCpfv.setTabOrder(self.fish_pct_7, self.fish_pct_8)
        RecCpfv.setTabOrder(self.fish_pct_8, self.fish_pct_9)
        RecCpfv.setTabOrder(self.fish_pct_9, self.fish_pct_10)
        RecCpfv.setTabOrder(self.fish_pct_10, self.fish_pct_11)
        RecCpfv.setTabOrder(self.fish_pct_11, self.fish_pct_12)
        RecCpfv.setTabOrder(self.fish_pct_12, self.fish_pct_13)
        RecCpfv.setTabOrder(self.fish_pct_13, self.fish_pct_14)
        RecCpfv.setTabOrder(self.fish_pct_14, self.fish_pct_15)
        RecCpfv.setTabOrder(self.fish_pct_15, self.fish_pct_16)
        RecCpfv.setTabOrder(self.fish_pct_16, self.fish_pct_17)
        RecCpfv.setTabOrder(self.fish_pct_17, self.fish_pct_18)
        RecCpfv.setTabOrder(self.fish_pct_18, self.fish_pct_19)
        RecCpfv.setTabOrder(self.fish_pct_19, self.fish_pct_20)
        RecCpfv.setTabOrder(self.fish_pct_20, self.pbnFinished)
        RecCpfv.setTabOrder(self.pbnFinished, self.pbnCancel)

    def retranslateUi(self, RecCpfv):
        RecCpfv.setWindowTitle(QtGui.QApplication.translate("RecCpfv", "OpenOceanMap - Fishery Participation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("RecCpfv", "Enter % of income derived from current fisheries", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("RecCpfv", "Coastal Pelagics or Net Fishery     (Coastal Pelagics - Beach Seine)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("RecCpfv", "Tuna & Bonito with Handline           (Coastal Pelagics - Troll/Handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("RecCpfv", "Large Offshore Pelagics                    (Ocean Pelagics - Troll/Handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("RecCpfv", "Nearshore Trap/Pot (Coastal Demersals - Trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("RecCpfv", "Nearshore Handline/Banking           (Coastal Demersals - Rod & Reel/Handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("RecCpfv", "Nearshore Spear (Coastal Demersals - Spear Gun)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("RecCpfv", "Nearshore Gillnets (Coastal Demersals - Gillnets)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("RecCpfv", "Deep Slope/Bank Trap/Pot Fishery (Demersal Shelf/Deep Slope - Trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("RecCpfv", "Deep Slope/Bank Handline/Banking (Demersal Shelf/Deep Slope - Rod & Reel/Handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("RecCpfv", "Lobster - Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("RecCpfv", "Lobster - Dive (SCUBA)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("RecCpfv", "Lobster - Dive (Free)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("RecCpfv", "Conch - Dive (SCUBA)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("RecCpfv", "Conch - Dive (Free)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("RecCpfv", "Shark", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("RecCpfv", "Shark - Gillnets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("RecCpfv", "Diamondback Squid - Light Stick ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("RecCpfv", "Turtle - Turtle Net", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("RecCpfv", "Bait (Ballyhoo - Net)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("RecCpfv", "Bait (Anchovy/Sardines - Cast Net)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("RecCpfv", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFinished.setText(QtGui.QApplication.translate("RecCpfv", "Continue", None, QtGui.QApplication.UnicodeUTF8))

