# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rec_cpfv.ui'
#
# Created: Fri Feb 05 13:17:43 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RecCpfv(object):
    def setupUi(self, RecCpfv):
        RecCpfv.setObjectName("RecCpfv")
        RecCpfv.setWindowModality(QtCore.Qt.WindowModal)
        RecCpfv.resize(479, 607)
        self.verticalLayout = QtGui.QVBoxLayout(RecCpfv)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtGui.QGroupBox(RecCpfv)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_24 = QtGui.QWidget(self.groupBox_4)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.widget_24)
        self.verticalLayout_14.setSpacing(4)
        self.verticalLayout_14.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_26 = QtGui.QWidget(self.widget_24)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_26)
        self.horizontalLayout_23.setSpacing(4)
        self.horizontalLayout_23.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtGui.QLabel(self.widget_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.fish_pct_1 = QtGui.QLineEdit(self.widget_26)
        self.fish_pct_1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_1.setFont(font)
        self.fish_pct_1.setObjectName("fish_pct_1")
        self.horizontalLayout_23.addWidget(self.fish_pct_1)
        self.verticalLayout_14.addWidget(self.widget_26)
        self.verticalLayout_2.addWidget(self.widget_24)
        self.widget_32 = QtGui.QWidget(self.groupBox_4)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.widget_32)
        self.verticalLayout_16.setSpacing(4)
        self.verticalLayout_16.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_34 = QtGui.QWidget(self.widget_32)
        self.widget_34.setObjectName("widget_34")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.widget_34)
        self.horizontalLayout_25.setSpacing(4)
        self.horizontalLayout_25.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_30 = QtGui.QLabel(self.widget_34)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)
        self.fish_pct_2 = QtGui.QLineEdit(self.widget_34)
        self.fish_pct_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_2.setFont(font)
        self.fish_pct_2.setObjectName("fish_pct_2")
        self.horizontalLayout_25.addWidget(self.fish_pct_2)
        self.verticalLayout_16.addWidget(self.widget_34)
        self.verticalLayout_2.addWidget(self.widget_32)
        self.widget_35 = QtGui.QWidget(self.groupBox_4)
        self.widget_35.setObjectName("widget_35")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.widget_35)
        self.verticalLayout_17.setSpacing(4)
        self.verticalLayout_17.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_36 = QtGui.QWidget(self.widget_35)
        self.widget_36.setObjectName("widget_36")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.widget_36)
        self.horizontalLayout_26.setSpacing(4)
        self.horizontalLayout_26.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_31 = QtGui.QLabel(self.widget_36)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_26.addWidget(self.label_31)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem2)
        self.fish_pct_3 = QtGui.QLineEdit(self.widget_36)
        self.fish_pct_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_3.setFont(font)
        self.fish_pct_3.setObjectName("fish_pct_3")
        self.horizontalLayout_26.addWidget(self.fish_pct_3)
        self.verticalLayout_17.addWidget(self.widget_36)
        self.verticalLayout_2.addWidget(self.widget_35)
        self.widget_37 = QtGui.QWidget(self.groupBox_4)
        self.widget_37.setObjectName("widget_37")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.widget_37)
        self.verticalLayout_18.setSpacing(4)
        self.verticalLayout_18.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_38 = QtGui.QWidget(self.widget_37)
        self.widget_38.setObjectName("widget_38")
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.widget_38)
        self.horizontalLayout_27.setSpacing(4)
        self.horizontalLayout_27.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_32 = QtGui.QLabel(self.widget_38)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_27.addWidget(self.label_32)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem3)
        self.fish_pct_4 = QtGui.QLineEdit(self.widget_38)
        self.fish_pct_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_4.setFont(font)
        self.fish_pct_4.setObjectName("fish_pct_4")
        self.horizontalLayout_27.addWidget(self.fish_pct_4)
        self.verticalLayout_18.addWidget(self.widget_38)
        self.verticalLayout_2.addWidget(self.widget_37)
        self.widget_39 = QtGui.QWidget(self.groupBox_4)
        self.widget_39.setObjectName("widget_39")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.widget_39)
        self.verticalLayout_19.setSpacing(4)
        self.verticalLayout_19.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_40 = QtGui.QWidget(self.widget_39)
        self.widget_40.setObjectName("widget_40")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.widget_40)
        self.horizontalLayout_28.setSpacing(4)
        self.horizontalLayout_28.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_33 = QtGui.QLabel(self.widget_40)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_28.addWidget(self.label_33)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem4)
        self.fish_pct_5 = QtGui.QLineEdit(self.widget_40)
        self.fish_pct_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_5.setFont(font)
        self.fish_pct_5.setObjectName("fish_pct_5")
        self.horizontalLayout_28.addWidget(self.fish_pct_5)
        self.verticalLayout_19.addWidget(self.widget_40)
        self.verticalLayout_2.addWidget(self.widget_39)
        self.widget_41 = QtGui.QWidget(self.groupBox_4)
        self.widget_41.setObjectName("widget_41")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.widget_41)
        self.verticalLayout_20.setSpacing(4)
        self.verticalLayout_20.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_42 = QtGui.QWidget(self.widget_41)
        self.widget_42.setObjectName("widget_42")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.widget_42)
        self.horizontalLayout_29.setSpacing(4)
        self.horizontalLayout_29.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_34 = QtGui.QLabel(self.widget_42)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_29.addWidget(self.label_34)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem5)
        self.fish_pct_6 = QtGui.QLineEdit(self.widget_42)
        self.fish_pct_6.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_6.setFont(font)
        self.fish_pct_6.setObjectName("fish_pct_6")
        self.horizontalLayout_29.addWidget(self.fish_pct_6)
        self.verticalLayout_20.addWidget(self.widget_42)
        self.verticalLayout_2.addWidget(self.widget_41)
        self.widget_43 = QtGui.QWidget(self.groupBox_4)
        self.widget_43.setObjectName("widget_43")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.widget_43)
        self.verticalLayout_21.setSpacing(4)
        self.verticalLayout_21.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_44 = QtGui.QWidget(self.widget_43)
        self.widget_44.setObjectName("widget_44")
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.widget_44)
        self.horizontalLayout_30.setSpacing(4)
        self.horizontalLayout_30.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_35 = QtGui.QLabel(self.widget_44)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_30.addWidget(self.label_35)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem6)
        self.fish_pct_7 = QtGui.QLineEdit(self.widget_44)
        self.fish_pct_7.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_7.setFont(font)
        self.fish_pct_7.setObjectName("fish_pct_7")
        self.horizontalLayout_30.addWidget(self.fish_pct_7)
        self.verticalLayout_21.addWidget(self.widget_44)
        self.verticalLayout_2.addWidget(self.widget_43)
        self.widget_45 = QtGui.QWidget(self.groupBox_4)
        self.widget_45.setObjectName("widget_45")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.widget_45)
        self.verticalLayout_22.setSpacing(4)
        self.verticalLayout_22.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget_46 = QtGui.QWidget(self.widget_45)
        self.widget_46.setObjectName("widget_46")
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.widget_46)
        self.horizontalLayout_31.setSpacing(4)
        self.horizontalLayout_31.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_36 = QtGui.QLabel(self.widget_46)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_31.addWidget(self.label_36)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem7)
        self.fish_pct_8 = QtGui.QLineEdit(self.widget_46)
        self.fish_pct_8.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_8.setFont(font)
        self.fish_pct_8.setObjectName("fish_pct_8")
        self.horizontalLayout_31.addWidget(self.fish_pct_8)
        self.verticalLayout_22.addWidget(self.widget_46)
        self.verticalLayout_2.addWidget(self.widget_45)
        self.widget_47 = QtGui.QWidget(self.groupBox_4)
        self.widget_47.setObjectName("widget_47")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.widget_47)
        self.verticalLayout_23.setSpacing(4)
        self.verticalLayout_23.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.widget_48 = QtGui.QWidget(self.widget_47)
        self.widget_48.setObjectName("widget_48")
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.widget_48)
        self.horizontalLayout_32.setSpacing(4)
        self.horizontalLayout_32.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_37 = QtGui.QLabel(self.widget_48)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_32.addWidget(self.label_37)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem8)
        self.fish_pct_9 = QtGui.QLineEdit(self.widget_48)
        self.fish_pct_9.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_9.setFont(font)
        self.fish_pct_9.setObjectName("fish_pct_9")
        self.horizontalLayout_32.addWidget(self.fish_pct_9)
        self.verticalLayout_23.addWidget(self.widget_48)
        self.verticalLayout_2.addWidget(self.widget_47)
        self.widget_49 = QtGui.QWidget(self.groupBox_4)
        self.widget_49.setObjectName("widget_49")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.widget_49)
        self.verticalLayout_24.setSpacing(4)
        self.verticalLayout_24.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_50 = QtGui.QWidget(self.widget_49)
        self.widget_50.setObjectName("widget_50")
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.widget_50)
        self.horizontalLayout_33.setSpacing(4)
        self.horizontalLayout_33.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_38 = QtGui.QLabel(self.widget_50)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_33.addWidget(self.label_38)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem9)
        self.fish_pct_10 = QtGui.QLineEdit(self.widget_50)
        self.fish_pct_10.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_10.setFont(font)
        self.fish_pct_10.setObjectName("fish_pct_10")
        self.horizontalLayout_33.addWidget(self.fish_pct_10)
        self.verticalLayout_24.addWidget(self.widget_50)
        self.verticalLayout_2.addWidget(self.widget_49)
        self.widget_51 = QtGui.QWidget(self.groupBox_4)
        self.widget_51.setObjectName("widget_51")
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.widget_51)
        self.verticalLayout_25.setSpacing(4)
        self.verticalLayout_25.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_52 = QtGui.QWidget(self.widget_51)
        self.widget_52.setObjectName("widget_52")
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.widget_52)
        self.horizontalLayout_34.setSpacing(4)
        self.horizontalLayout_34.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_39 = QtGui.QLabel(self.widget_52)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_34.addWidget(self.label_39)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem10)
        self.fish_pct_11 = QtGui.QLineEdit(self.widget_52)
        self.fish_pct_11.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_11.setFont(font)
        self.fish_pct_11.setObjectName("fish_pct_11")
        self.horizontalLayout_34.addWidget(self.fish_pct_11)
        self.verticalLayout_25.addWidget(self.widget_52)
        self.verticalLayout_2.addWidget(self.widget_51)
        self.widget_53 = QtGui.QWidget(self.groupBox_4)
        self.widget_53.setObjectName("widget_53")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.widget_53)
        self.verticalLayout_26.setSpacing(4)
        self.verticalLayout_26.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.widget_54 = QtGui.QWidget(self.widget_53)
        self.widget_54.setObjectName("widget_54")
        self.horizontalLayout_35 = QtGui.QHBoxLayout(self.widget_54)
        self.horizontalLayout_35.setSpacing(4)
        self.horizontalLayout_35.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_40 = QtGui.QLabel(self.widget_54)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_35.addWidget(self.label_40)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem11)
        self.fish_pct_12 = QtGui.QLineEdit(self.widget_54)
        self.fish_pct_12.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_12.setFont(font)
        self.fish_pct_12.setObjectName("fish_pct_12")
        self.horizontalLayout_35.addWidget(self.fish_pct_12)
        self.verticalLayout_26.addWidget(self.widget_54)
        self.verticalLayout_2.addWidget(self.widget_53)
        self.widget_55 = QtGui.QWidget(self.groupBox_4)
        self.widget_55.setObjectName("widget_55")
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.widget_55)
        self.verticalLayout_27.setSpacing(4)
        self.verticalLayout_27.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.widget_56 = QtGui.QWidget(self.widget_55)
        self.widget_56.setObjectName("widget_56")
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.widget_56)
        self.horizontalLayout_36.setSpacing(4)
        self.horizontalLayout_36.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_41 = QtGui.QLabel(self.widget_56)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_36.addWidget(self.label_41)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem12)
        self.fish_pct_13 = QtGui.QLineEdit(self.widget_56)
        self.fish_pct_13.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_13.setFont(font)
        self.fish_pct_13.setObjectName("fish_pct_13")
        self.horizontalLayout_36.addWidget(self.fish_pct_13)
        self.verticalLayout_27.addWidget(self.widget_56)
        self.verticalLayout_2.addWidget(self.widget_55)
        self.widget_28 = QtGui.QWidget(self.groupBox_4)
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget_28)
        self.verticalLayout_15.setSpacing(4)
        self.verticalLayout_15.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_30 = QtGui.QWidget(self.widget_28)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widget_30)
        self.horizontalLayout_24.setSpacing(4)
        self.horizontalLayout_24.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_29 = QtGui.QLabel(self.widget_30)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_24.addWidget(self.label_29)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem13)
        self.fish_pct_14 = QtGui.QLineEdit(self.widget_30)
        self.fish_pct_14.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_14.setFont(font)
        self.fish_pct_14.setObjectName("fish_pct_14")
        self.horizontalLayout_24.addWidget(self.fish_pct_14)
        self.verticalLayout_15.addWidget(self.widget_30)
        self.verticalLayout_2.addWidget(self.widget_28)
        self.widget_22 = QtGui.QWidget(self.groupBox_4)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_22)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setContentsMargins(4, 2, 4, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_23 = QtGui.QWidget(self.widget_22)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widget_23)
        self.horizontalLayout_17.setSpacing(4)
        self.horizontalLayout_17.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtGui.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem14)
        self.fish_pct_15 = QtGui.QLineEdit(self.widget_23)
        self.fish_pct_15.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fish_pct_15.setFont(font)
        self.fish_pct_15.setObjectName("fish_pct_15")
        self.horizontalLayout_17.addWidget(self.fish_pct_15)
        self.verticalLayout_8.addWidget(self.widget_23)
        self.verticalLayout_2.addWidget(self.widget_22)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.button_box = QtGui.QWidget(RecCpfv)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout = QtGui.QHBoxLayout(self.button_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self.horizontalLayout.addWidget(self.pbnCancel)
        spacerItem16 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.pbnFinished = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFinished.setFont(font)
        self.pbnFinished.setObjectName("pbnFinished")
        self.horizontalLayout.addWidget(self.pbnFinished)
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(RecCpfv)
        QtCore.QMetaObject.connectSlotsByName(RecCpfv)
        RecCpfv.setTabOrder(self.fish_pct_1, self.fish_pct_2)
        RecCpfv.setTabOrder(self.fish_pct_2, self.fish_pct_3)
        RecCpfv.setTabOrder(self.fish_pct_3, self.fish_pct_4)
        RecCpfv.setTabOrder(self.fish_pct_4, self.fish_pct_5)
        RecCpfv.setTabOrder(self.fish_pct_5, self.fish_pct_6)
        RecCpfv.setTabOrder(self.fish_pct_6, self.fish_pct_7)
        RecCpfv.setTabOrder(self.fish_pct_7, self.fish_pct_8)
        RecCpfv.setTabOrder(self.fish_pct_8, self.fish_pct_9)
        RecCpfv.setTabOrder(self.fish_pct_9, self.fish_pct_10)
        RecCpfv.setTabOrder(self.fish_pct_10, self.fish_pct_11)
        RecCpfv.setTabOrder(self.fish_pct_11, self.fish_pct_12)
        RecCpfv.setTabOrder(self.fish_pct_12, self.fish_pct_13)
        RecCpfv.setTabOrder(self.fish_pct_13, self.fish_pct_14)
        RecCpfv.setTabOrder(self.fish_pct_14, self.fish_pct_15)
        RecCpfv.setTabOrder(self.fish_pct_15, self.pbnFinished)
        RecCpfv.setTabOrder(self.pbnFinished, self.pbnCancel)

    def retranslateUi(self, RecCpfv):
        RecCpfv.setWindowTitle(QtGui.QApplication.translate("RecCpfv", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("RecCpfv", "Fishery Participation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("RecCpfv", "Fishery % of income", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("RecCpfv", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFinished.setText(QtGui.QApplication.translate("RecCpfv", "Continue", None, QtGui.QApplication.UnicodeUTF8))

