# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectfishery.ui'
#
# Created: Thu Apr 29 11:08:00 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SelectFishery(object):
    def setupUi(self, SelectFishery):
        SelectFishery.setObjectName("SelectFishery")
        SelectFishery.resize(691, 411)
        self.verticalLayout = QtGui.QVBoxLayout(SelectFishery)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtGui.QWidget(SelectFishery)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setContentsMargins(9, 9, 9, 0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.fishery_text = QtGui.QLabel(self.widget)
        self.fishery_text.setMinimumSize(QtCore.QSize(110, 0))
        self.fishery_text.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fishery_text.setFont(font)
        self.fishery_text.setObjectName("fishery_text")
        self.hboxlayout.addWidget(self.fishery_text)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.fishery_comboBox = QtGui.QComboBox(self.widget)
        self.fishery_comboBox.setMinimumSize(QtCore.QSize(450, 0))
        self.fishery_comboBox.setMaximumSize(QtCore.QSize(450, 16777215))
        self.fishery_comboBox.setObjectName("fishery_comboBox")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.setItemText(0, "")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.hboxlayout.addWidget(self.fishery_comboBox)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_4 = QtGui.QWidget(SelectFishery)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setMinimumSize(QtCore.QSize(210, 0))
        self.label_3.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.fish_yrs_partic = QtGui.QLineEdit(self.widget_4)
        self.fish_yrs_partic.setMinimumSize(QtCore.QSize(100, 0))
        self.fish_yrs_partic.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fish_yrs_partic.setObjectName("fish_yrs_partic")
        self.horizontalLayout_8.addWidget(self.fish_yrs_partic)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtGui.QWidget(SelectFishery)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.fishery_season_start = QtGui.QComboBox(self.widget_3)
        self.fishery_season_start.setMinimumSize(QtCore.QSize(200, 0))
        self.fishery_season_start.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fishery_season_start.setObjectName("fishery_season_start")
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.setItemText(0, "")
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.fishery_season_start.addItem(QtCore.QString())
        self.horizontalLayout_4.addWidget(self.fishery_season_start)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.fishery_season_end = QtGui.QComboBox(self.widget_3)
        self.fishery_season_end.setMinimumSize(QtCore.QSize(200, 0))
        self.fishery_season_end.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fishery_season_end.setObjectName("fishery_season_end")
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.setItemText(0, "")
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.fishery_season_end.addItem(QtCore.QString())
        self.horizontalLayout_4.addWidget(self.fishery_season_end)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_6 = QtGui.QWidget(SelectFishery)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtGui.QLabel(self.widget_6)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.fishery_season_start_2 = QtGui.QComboBox(self.widget_6)
        self.fishery_season_start_2.setMinimumSize(QtCore.QSize(200, 0))
        self.fishery_season_start_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fishery_season_start_2.setObjectName("fishery_season_start_2")
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.setItemText(0, "")
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.fishery_season_start_2.addItem(QtCore.QString())
        self.horizontalLayout_11.addWidget(self.fishery_season_start_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.label_7 = QtGui.QLabel(self.widget_6)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.fishery_season_end_2 = QtGui.QComboBox(self.widget_6)
        self.fishery_season_end_2.setMinimumSize(QtCore.QSize(200, 0))
        self.fishery_season_end_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fishery_season_end_2.setObjectName("fishery_season_end_2")
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.setItemText(0, "")
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.fishery_season_end_2.addItem(QtCore.QString())
        self.horizontalLayout_11.addWidget(self.fishery_season_end_2)
        self.horizontalLayout_6.addWidget(self.widget_6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_7 = QtGui.QWidget(SelectFishery)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtGui.QLabel(self.widget_7)
        self.label_6.setMinimumSize(QtCore.QSize(390, 0))
        self.label_6.setMaximumSize(QtCore.QSize(390, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.fish_num_gear = QtGui.QLineEdit(self.widget_7)
        self.fish_num_gear.setMinimumSize(QtCore.QSize(100, 0))
        self.fish_num_gear.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fish_num_gear.setObjectName("fish_num_gear")
        self.horizontalLayout_14.addWidget(self.fish_num_gear)
        self.horizontalLayout_13.addWidget(self.widget_7)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_5 = QtGui.QWidget(SelectFishery)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtGui.QLabel(self.widget_5)
        self.label_4.setMinimumSize(QtCore.QSize(300, 0))
        self.label_4.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.fish_gear_length = QtGui.QLineEdit(self.widget_5)
        self.fish_gear_length.setMinimumSize(QtCore.QSize(100, 0))
        self.fish_gear_length.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fish_gear_length.setObjectName("fish_gear_length")
        self.horizontalLayout_10.addWidget(self.fish_gear_length)
        self.horizontalLayout_9.addWidget(self.widget_5)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_9 = QtGui.QWidget(SelectFishery)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtGui.QLabel(self.widget_9)
        self.label_8.setMinimumSize(QtCore.QSize(200, 0))
        self.label_8.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.fish_port = QtGui.QComboBox(self.widget_9)
        self.fish_port.setMinimumSize(QtCore.QSize(250, 0))
        self.fish_port.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fish_port.setObjectName("fish_port")
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.setItemText(0, "")
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.fish_port.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.fish_port)
        self.horizontalLayout_17.addWidget(self.widget_9)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtGui.QWidget(SelectFishery)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget_2)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(9)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem7)
        self.pbnFisheryFinished = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFisheryFinished.setFont(font)
        self.pbnFisheryFinished.setObjectName("pbnFisheryFinished")
        self.hboxlayout1.addWidget(self.pbnFisheryFinished)
        self.pbnStartShapes = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnStartShapes.setFont(font)
        self.pbnStartShapes.setObjectName("pbnStartShapes")
        self.hboxlayout1.addWidget(self.pbnStartShapes)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SelectFishery)
        QtCore.QMetaObject.connectSlotsByName(SelectFishery)
        SelectFishery.setTabOrder(self.fishery_comboBox, self.fish_yrs_partic)
        SelectFishery.setTabOrder(self.fish_yrs_partic, self.fishery_season_start)
        SelectFishery.setTabOrder(self.fishery_season_start, self.fishery_season_end)
        SelectFishery.setTabOrder(self.fishery_season_end, self.fishery_season_start_2)
        SelectFishery.setTabOrder(self.fishery_season_start_2, self.fishery_season_end_2)
        SelectFishery.setTabOrder(self.fishery_season_end_2, self.fish_num_gear)
        SelectFishery.setTabOrder(self.fish_num_gear, self.fish_gear_length)
        SelectFishery.setTabOrder(self.fish_gear_length, self.fish_port)
        SelectFishery.setTabOrder(self.fish_port, self.pbnStartShapes)
        SelectFishery.setTabOrder(self.pbnStartShapes, self.pbnFisheryFinished)

    def retranslateUi(self, SelectFishery):
        SelectFishery.setWindowTitle(QtGui.QApplication.translate("SelectFishery", "OpenOceanMap - Select Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_text.setText(QtGui.QApplication.translate("SelectFishery", "16. Select fishery:", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(1, QtGui.QApplication.translate("SelectFishery", "Coastal pelagics or net fishery (Coastal pelagics - beach seine)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(2, QtGui.QApplication.translate("SelectFishery", "Tuna & bonito with handline (Coastal pelagics - troll/handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(3, QtGui.QApplication.translate("SelectFishery", "Large offshore pelagics (Ocean pelagics - troll/handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(4, QtGui.QApplication.translate("SelectFishery", "Nearshore trap/pot (Coastal demersals - trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(5, QtGui.QApplication.translate("SelectFishery", "Nearshore handline/banking (Coastal demersals - rod and reel/handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(6, QtGui.QApplication.translate("SelectFishery", "Nearshore spear (Coastal demersals - spear gun)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(7, QtGui.QApplication.translate("SelectFishery", "Nearshore gillnet (Coastal demersals - gillnet)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(8, QtGui.QApplication.translate("SelectFishery", "Deep slope/bank trap/pot fishery (Demersal shelf/deep slope - trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(9, QtGui.QApplication.translate("SelectFishery", "Deep slope/bank handline/banking fishery (Demersal shelf/deep slope - rod and reel/handline)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(10, QtGui.QApplication.translate("SelectFishery", "Lobster - trap", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(11, QtGui.QApplication.translate("SelectFishery", "Lobster - dive (SCUBA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(12, QtGui.QApplication.translate("SelectFishery", "Lobster - dive (free)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(13, QtGui.QApplication.translate("SelectFishery", "Conch - dive (SCUBA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(14, QtGui.QApplication.translate("SelectFishery", "Conch - dive (free)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(15, QtGui.QApplication.translate("SelectFishery", "Shark - hook and line", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(16, QtGui.QApplication.translate("SelectFishery", "Shark - gillnet", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(17, QtGui.QApplication.translate("SelectFishery", "Diamondback squid - light stick/hook and line", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(18, QtGui.QApplication.translate("SelectFishery", "Turtle - turtle net", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(19, QtGui.QApplication.translate("SelectFishery", "Bait - Ballyhoo - net", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(20, QtGui.QApplication.translate("SelectFishery", "Bait - Anchovy/sardine - cast net", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(21, QtGui.QApplication.translate("SelectFishery", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SelectFishery", "17. Years experience in this fishery:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SelectFishery", "18. Season start:", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(1, QtGui.QApplication.translate("SelectFishery", "January", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(2, QtGui.QApplication.translate("SelectFishery", "February", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(3, QtGui.QApplication.translate("SelectFishery", "March", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(4, QtGui.QApplication.translate("SelectFishery", "April", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(5, QtGui.QApplication.translate("SelectFishery", "May", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(6, QtGui.QApplication.translate("SelectFishery", "June", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(7, QtGui.QApplication.translate("SelectFishery", "July", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(8, QtGui.QApplication.translate("SelectFishery", "August", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(9, QtGui.QApplication.translate("SelectFishery", "September", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(10, QtGui.QApplication.translate("SelectFishery", "October", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(11, QtGui.QApplication.translate("SelectFishery", "November", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start.setItemText(12, QtGui.QApplication.translate("SelectFishery", "December", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SelectFishery", "Season end:", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(1, QtGui.QApplication.translate("SelectFishery", "January", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(2, QtGui.QApplication.translate("SelectFishery", "February", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(3, QtGui.QApplication.translate("SelectFishery", "March", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(4, QtGui.QApplication.translate("SelectFishery", "April", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(5, QtGui.QApplication.translate("SelectFishery", "May", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(6, QtGui.QApplication.translate("SelectFishery", "June", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(7, QtGui.QApplication.translate("SelectFishery", "July", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(8, QtGui.QApplication.translate("SelectFishery", "August", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(9, QtGui.QApplication.translate("SelectFishery", "September", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(10, QtGui.QApplication.translate("SelectFishery", "October", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(11, QtGui.QApplication.translate("SelectFishery", "November", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end.setItemText(12, QtGui.QApplication.translate("SelectFishery", "December", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SelectFishery", "     Season start:", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(1, QtGui.QApplication.translate("SelectFishery", "January", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(2, QtGui.QApplication.translate("SelectFishery", "February", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(3, QtGui.QApplication.translate("SelectFishery", "March", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(4, QtGui.QApplication.translate("SelectFishery", "April", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(5, QtGui.QApplication.translate("SelectFishery", "May", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(6, QtGui.QApplication.translate("SelectFishery", "June", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(7, QtGui.QApplication.translate("SelectFishery", "July", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(8, QtGui.QApplication.translate("SelectFishery", "August", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(9, QtGui.QApplication.translate("SelectFishery", "September", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(10, QtGui.QApplication.translate("SelectFishery", "October", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(11, QtGui.QApplication.translate("SelectFishery", "November", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_start_2.setItemText(12, QtGui.QApplication.translate("SelectFishery", "December", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SelectFishery", "Season end:", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(1, QtGui.QApplication.translate("SelectFishery", "January", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(2, QtGui.QApplication.translate("SelectFishery", "February", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(3, QtGui.QApplication.translate("SelectFishery", "March", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(4, QtGui.QApplication.translate("SelectFishery", "April", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(5, QtGui.QApplication.translate("SelectFishery", "May", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(6, QtGui.QApplication.translate("SelectFishery", "June", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(7, QtGui.QApplication.translate("SelectFishery", "July", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(8, QtGui.QApplication.translate("SelectFishery", "August", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(9, QtGui.QApplication.translate("SelectFishery", "September", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(10, QtGui.QApplication.translate("SelectFishery", "October", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(11, QtGui.QApplication.translate("SelectFishery", "November", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_season_end_2.setItemText(12, QtGui.QApplication.translate("SelectFishery", "December", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SelectFishery", "19. Trap fisheries only - Average number of traps fished per week:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SelectFishery", "20. Trap fisheries only - Average trap soak time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("SelectFishery", "21. Fishery-specific landing site:", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(1, QtGui.QApplication.translate("SelectFishery", "Basseterre E", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(2, QtGui.QApplication.translate("SelectFishery", "Basseterre W", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(3, QtGui.QApplication.translate("SelectFishery", "Old Road", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(4, QtGui.QApplication.translate("SelectFishery", "Sandy Point", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(5, QtGui.QApplication.translate("SelectFishery", "Conaree", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(6, QtGui.QApplication.translate("SelectFishery", "Dieppe Bay", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(7, QtGui.QApplication.translate("SelectFishery", "Charlestown", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(8, QtGui.QApplication.translate("SelectFishery", "Jessups", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(9, QtGui.QApplication.translate("SelectFishery", "Cotton Ground", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(10, QtGui.QApplication.translate("SelectFishery", "Jones Bay", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(11, QtGui.QApplication.translate("SelectFishery", "New Castle", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(12, QtGui.QApplication.translate("SelectFishery", "Long Haul", None, QtGui.QApplication.UnicodeUTF8))
        self.fish_port.setItemText(13, QtGui.QApplication.translate("SelectFishery", "Indian Castle", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFisheryFinished.setText(QtGui.QApplication.translate("SelectFishery", "Finished With Fisheries", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnStartShapes.setText(QtGui.QApplication.translate("SelectFishery", "Start Drawing Shapes", None, QtGui.QApplication.UnicodeUTF8))

