# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rec_all.ui'
#
# Created: Wed Jul 08 14:25:13 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RecAll(object):
    def setupUi(self, RecAll):
        RecAll.setObjectName("RecAll")
        RecAll.resize(811, 605)
        self.button_box = QtGui.QWidget(RecAll)
        self.button_box.setGeometry(QtCore.QRect(420, 560, 380, 36))
        self.button_box.setObjectName("button_box")
        self._19 = QtGui.QHBoxLayout(self.button_box)
        self._19.setSpacing(2)
        self._19.setMargin(2)
        self._19.setObjectName("_19")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._19.addItem(spacerItem)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self._19.addWidget(self.pbnCancel)
        self.pbnSelectFishery = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnSelectFishery.setFont(font)
        self.pbnSelectFishery.setObjectName("pbnSelectFishery")
        self._19.addWidget(self.pbnSelectFishery)
        self.vessel_info = QtGui.QGroupBox(RecAll)
        self.vessel_info.setGeometry(QtCore.QRect(10, 10, 400, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_port_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_2.setFont(font)
        self.home_port_2.setObjectName("home_port_2")
        self._4 = QtGui.QHBoxLayout(self.home_port_2)
        self._4.setSpacing(4)
        self._4.setMargin(4)
        self._4.setObjectName("_4")
        self.perc_income_text = QtGui.QLabel(self.home_port_2)
        self.perc_income_text.setMinimumSize(QtCore.QSize(150, 0))
        self.perc_income_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perc_income_text.setFont(font)
        self.perc_income_text.setObjectName("perc_income_text")
        self._4.addWidget(self.perc_income_text)
        self.type_boat_line = QtGui.QLineEdit(self.home_port_2)
        self.type_boat_line.setEnabled(True)
        self.type_boat_line.setMinimumSize(QtCore.QSize(100, 0))
        self.type_boat_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.type_boat_line.setFont(font)
        self.type_boat_line.setObjectName("type_boat_line")
        self._4.addWidget(self.type_boat_line)
        self.verticalLayout.addWidget(self.home_port_2)
        self.home_port_3 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_3.setFont(font)
        self.home_port_3.setObjectName("home_port_3")
        self._5 = QtGui.QHBoxLayout(self.home_port_3)
        self._5.setSpacing(4)
        self._5.setMargin(4)
        self._5.setObjectName("_5")
        self.boat_license_text = QtGui.QLabel(self.home_port_3)
        self.boat_license_text.setMinimumSize(QtCore.QSize(150, 0))
        self.boat_license_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boat_license_text.setFont(font)
        self.boat_license_text.setObjectName("boat_license_text")
        self._5.addWidget(self.boat_license_text)
        self.boat_license_line = QtGui.QLineEdit(self.home_port_3)
        self.boat_license_line.setEnabled(True)
        self.boat_license_line.setMinimumSize(QtCore.QSize(200, 0))
        self.boat_license_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boat_license_line.setFont(font)
        self.boat_license_line.setObjectName("boat_license_line")
        self._5.addWidget(self.boat_license_line)
        self.verticalLayout.addWidget(self.home_port_3)
        self.ves_license = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license.setFont(font)
        self.ves_license.setObjectName("ves_license")
        self.hboxlayout = QtGui.QHBoxLayout(self.ves_license)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(4)
        self.hboxlayout.setObjectName("hboxlayout")
        self.yrs_operating_text = QtGui.QLabel(self.ves_license)
        self.yrs_operating_text.setMinimumSize(QtCore.QSize(150, 0))
        self.yrs_operating_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yrs_operating_text.setFont(font)
        self.yrs_operating_text.setObjectName("yrs_operating_text")
        self.hboxlayout.addWidget(self.yrs_operating_text)
        self.yrs_operating_line = QtGui.QLineEdit(self.ves_license)
        self.yrs_operating_line.setEnabled(True)
        self.yrs_operating_line.setMinimumSize(QtCore.QSize(200, 0))
        self.yrs_operating_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yrs_operating_line.setFont(font)
        self.yrs_operating_line.setObjectName("yrs_operating_line")
        self.hboxlayout.addWidget(self.yrs_operating_line)
        self.verticalLayout.addWidget(self.ves_license)
        self.ves_license_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license_2.setFont(font)
        self.ves_license_2.setObjectName("ves_license_2")
        self._13 = QtGui.QHBoxLayout(self.ves_license_2)
        self._13.setSpacing(4)
        self._13.setMargin(4)
        self._13.setObjectName("_13")
        self.yrs_owning_text = QtGui.QLabel(self.ves_license_2)
        self.yrs_owning_text.setMinimumSize(QtCore.QSize(150, 0))
        self.yrs_owning_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yrs_owning_text.setFont(font)
        self.yrs_owning_text.setObjectName("yrs_owning_text")
        self._13.addWidget(self.yrs_owning_text)
        self.yrs_owning_line = QtGui.QLineEdit(self.ves_license_2)
        self.yrs_owning_line.setEnabled(True)
        self.yrs_owning_line.setMinimumSize(QtCore.QSize(200, 0))
        self.yrs_owning_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yrs_owning_line.setFont(font)
        self.yrs_owning_line.setObjectName("yrs_owning_line")
        self._13.addWidget(self.yrs_owning_line)
        self.verticalLayout.addWidget(self.ves_license_2)
        self.vessel_length = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length.setFont(font)
        self.vessel_length.setObjectName("vessel_length")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.vessel_length)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(4)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vessel_length_text = QtGui.QLabel(self.vessel_length)
        self.vessel_length_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_length_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_text.setFont(font)
        self.vessel_length_text.setObjectName("vessel_length_text")
        self.hboxlayout1.addWidget(self.vessel_length_text)
        self.vessel_length_line = QtGui.QLineEdit(self.vessel_length)
        self.vessel_length_line.setEnabled(True)
        self.vessel_length_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_length_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_line.setFont(font)
        self.vessel_length_line.setObjectName("vessel_length_line")
        self.hboxlayout1.addWidget(self.vessel_length_line)
        self.verticalLayout.addWidget(self.vessel_length)
        self.vessel_length_3 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_3.setFont(font)
        self.vessel_length_3.setObjectName("vessel_length_3")
        self._15 = QtGui.QHBoxLayout(self.vessel_length_3)
        self._15.setSpacing(4)
        self._15.setMargin(4)
        self._15.setObjectName("_15")
        self.storage_loc_text = QtGui.QLabel(self.vessel_length_3)
        self.storage_loc_text.setMinimumSize(QtCore.QSize(150, 0))
        self.storage_loc_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.storage_loc_text.setFont(font)
        self.storage_loc_text.setObjectName("storage_loc_text")
        self._15.addWidget(self.storage_loc_text)
        self.storage_loc_line = QtGui.QLineEdit(self.vessel_length_3)
        self.storage_loc_line.setEnabled(True)
        self.storage_loc_line.setMinimumSize(QtCore.QSize(200, 0))
        self.storage_loc_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.storage_loc_line.setFont(font)
        self.storage_loc_line.setObjectName("storage_loc_line")
        self._15.addWidget(self.storage_loc_line)
        self.verticalLayout.addWidget(self.vessel_length_3)
        self.home_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port.setFont(font)
        self.home_port.setObjectName("home_port")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.home_port)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.home_port_text = QtGui.QLabel(self.home_port)
        self.home_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.home_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_text.setFont(font)
        self.home_port_text.setObjectName("home_port_text")
        self.hboxlayout2.addWidget(self.home_port_text)
        self.home_port_line = QtGui.QLineEdit(self.home_port)
        self.home_port_line.setEnabled(True)
        self.home_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.home_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_line.setFont(font)
        self.home_port_line.setObjectName("home_port_line")
        self.hboxlayout2.addWidget(self.home_port_line)
        self.verticalLayout.addWidget(self.home_port)
        self.home_port_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_4.setFont(font)
        self.home_port_4.setObjectName("home_port_4")
        self._7 = QtGui.QHBoxLayout(self.home_port_4)
        self._7.setSpacing(4)
        self._7.setMargin(4)
        self._7.setObjectName("_7")
        self.landing_port_text = QtGui.QLabel(self.home_port_4)
        self.landing_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text.setFont(font)
        self.landing_port_text.setObjectName("landing_port_text")
        self._7.addWidget(self.landing_port_text)
        self.landing_port_line = QtGui.QLineEdit(self.home_port_4)
        self.landing_port_line.setEnabled(True)
        self.landing_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line.setFont(font)
        self.landing_port_line.setObjectName("landing_port_line")
        self._7.addWidget(self.landing_port_line)
        self.verticalLayout.addWidget(self.home_port_4)
        self.home_port_7 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_7.setFont(font)
        self.home_port_7.setObjectName("home_port_7")
        self._16 = QtGui.QHBoxLayout(self.home_port_7)
        self._16.setSpacing(4)
        self._16.setMargin(4)
        self._16.setObjectName("_16")
        self.landing_port_text_2 = QtGui.QLabel(self.home_port_7)
        self.landing_port_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_2.setFont(font)
        self.landing_port_text_2.setObjectName("landing_port_text_2")
        self._16.addWidget(self.landing_port_text_2)
        self.landing_port_line_2 = QtGui.QLineEdit(self.home_port_7)
        self.landing_port_line_2.setEnabled(True)
        self.landing_port_line_2.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_2.setFont(font)
        self.landing_port_line_2.setObjectName("landing_port_line_2")
        self._16.addWidget(self.landing_port_line_2)
        self.verticalLayout.addWidget(self.home_port_7)
        self.home_port_8 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_8.setFont(font)
        self.home_port_8.setObjectName("home_port_8")
        self._17 = QtGui.QHBoxLayout(self.home_port_8)
        self._17.setSpacing(4)
        self._17.setMargin(4)
        self._17.setObjectName("_17")
        self.landing_port_text_3 = QtGui.QLabel(self.home_port_8)
        self.landing_port_text_3.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_3.setFont(font)
        self.landing_port_text_3.setObjectName("landing_port_text_3")
        self._17.addWidget(self.landing_port_text_3)
        self.landing_port_line_3 = QtGui.QLineEdit(self.home_port_8)
        self.landing_port_line_3.setEnabled(True)
        self.landing_port_line_3.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_3.setFont(font)
        self.landing_port_line_3.setObjectName("landing_port_line_3")
        self._17.addWidget(self.landing_port_line_3)
        self.verticalLayout.addWidget(self.home_port_8)
        self.home_port_9 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_9.setFont(font)
        self.home_port_9.setObjectName("home_port_9")
        self._18 = QtGui.QHBoxLayout(self.home_port_9)
        self._18.setSpacing(4)
        self._18.setMargin(4)
        self._18.setObjectName("_18")
        self.landing_port_text_4 = QtGui.QLabel(self.home_port_9)
        self.landing_port_text_4.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_4.setFont(font)
        self.landing_port_text_4.setObjectName("landing_port_text_4")
        self._18.addWidget(self.landing_port_text_4)
        self.landing_port_line_4 = QtGui.QLineEdit(self.home_port_9)
        self.landing_port_line_4.setEnabled(True)
        self.landing_port_line_4.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_4.setFont(font)
        self.landing_port_line_4.setObjectName("landing_port_line_4")
        self._18.addWidget(self.landing_port_line_4)
        self.verticalLayout.addWidget(self.home_port_9)
        self.home_port_5 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_5.setFont(font)
        self.home_port_5.setObjectName("home_port_5")
        self._11 = QtGui.QHBoxLayout(self.home_port_5)
        self._11.setSpacing(4)
        self._11.setMargin(4)
        self._11.setObjectName("_11")
        self.years_text = QtGui.QLabel(self.home_port_5)
        self.years_text.setMinimumSize(QtCore.QSize(150, 34))
        self.years_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_text.setFont(font)
        self.years_text.setWordWrap(True)
        self.years_text.setObjectName("years_text")
        self._11.addWidget(self.years_text)
        self.years_fishing_line = QtGui.QLineEdit(self.home_port_5)
        self.years_fishing_line.setEnabled(True)
        self.years_fishing_line.setMinimumSize(QtCore.QSize(100, 0))
        self.years_fishing_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_fishing_line.setFont(font)
        self.years_fishing_line.setObjectName("years_fishing_line")
        self._11.addWidget(self.years_fishing_line)
        self.verticalLayout.addWidget(self.home_port_5)
        self.vessel_length_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_2.setFont(font)
        self.vessel_length_2.setObjectName("vessel_length_2")
        self._14 = QtGui.QHBoxLayout(self.vessel_length_2)
        self._14.setSpacing(4)
        self._14.setMargin(4)
        self._14.setObjectName("_14")
        self.avg_people_text = QtGui.QLabel(self.vessel_length_2)
        self.avg_people_text.setMinimumSize(QtCore.QSize(150, 34))
        self.avg_people_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.avg_people_text.setFont(font)
        self.avg_people_text.setWordWrap(True)
        self.avg_people_text.setObjectName("avg_people_text")
        self._14.addWidget(self.avg_people_text)
        self.avg_people_line = QtGui.QLineEdit(self.vessel_length_2)
        self.avg_people_line.setEnabled(True)
        self.avg_people_line.setMinimumSize(QtCore.QSize(200, 0))
        self.avg_people_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.avg_people_line.setFont(font)
        self.avg_people_line.setObjectName("avg_people_line")
        self._14.addWidget(self.avg_people_line)
        self.verticalLayout.addWidget(self.vessel_length_2)
        self.vessel_length_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_4.setFont(font)
        self.vessel_length_4.setObjectName("vessel_length_4")
        self._20 = QtGui.QHBoxLayout(self.vessel_length_4)
        self._20.setSpacing(4)
        self._20.setMargin(4)
        self._20.setObjectName("_20")
        self.avg_days_per_year_text = QtGui.QLabel(self.vessel_length_4)
        self.avg_days_per_year_text.setMinimumSize(QtCore.QSize(150, 34))
        self.avg_days_per_year_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.avg_days_per_year_text.setFont(font)
        self.avg_days_per_year_text.setWordWrap(True)
        self.avg_days_per_year_text.setObjectName("avg_days_per_year_text")
        self._20.addWidget(self.avg_days_per_year_text)
        self.avg_days_per_year_line = QtGui.QLineEdit(self.vessel_length_4)
        self.avg_days_per_year_line.setEnabled(True)
        self.avg_days_per_year_line.setMinimumSize(QtCore.QSize(200, 0))
        self.avg_days_per_year_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.avg_days_per_year_line.setFont(font)
        self.avg_days_per_year_line.setObjectName("avg_days_per_year_line")
        self._20.addWidget(self.avg_days_per_year_line)
        self.verticalLayout.addWidget(self.vessel_length_4)
        self.layoutWidget = QtGui.QWidget(RecAll)
        self.layoutWidget.setGeometry(QtCore.QRect(420, 10, 384, 545))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DiveFishing = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DiveFishing.setFont(font)
        self.DiveFishing.setObjectName("DiveFishing")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.DiveFishing)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ves_license_3 = QtGui.QWidget(self.DiveFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license_3.setFont(font)
        self.ves_license_3.setObjectName("ves_license_3")
        self._6 = QtGui.QHBoxLayout(self.ves_license_3)
        self._6.setSpacing(4)
        self._6.setMargin(4)
        self._6.setObjectName("_6")
        self.yrs_operating_text_2 = QtGui.QLabel(self.ves_license_3)
        self.yrs_operating_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.yrs_operating_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yrs_operating_text_2.setFont(font)
        self.yrs_operating_text_2.setObjectName("yrs_operating_text_2")
        self._6.addWidget(self.yrs_operating_text_2)
        self.dive_avg_dives_per_trip = QtGui.QLineEdit(self.ves_license_3)
        self.dive_avg_dives_per_trip.setEnabled(True)
        self.dive_avg_dives_per_trip.setMinimumSize(QtCore.QSize(200, 0))
        self.dive_avg_dives_per_trip.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dive_avg_dives_per_trip.setFont(font)
        self.dive_avg_dives_per_trip.setObjectName("dive_avg_dives_per_trip")
        self._6.addWidget(self.dive_avg_dives_per_trip)
        self.verticalLayout_4.addWidget(self.ves_license_3)
        self.home_port_6 = QtGui.QWidget(self.DiveFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_6.setFont(font)
        self.home_port_6.setObjectName("home_port_6")
        self._12 = QtGui.QHBoxLayout(self.home_port_6)
        self._12.setSpacing(4)
        self._12.setMargin(4)
        self._12.setObjectName("_12")
        self.years_text_2 = QtGui.QLabel(self.home_port_6)
        self.years_text_2.setMinimumSize(QtCore.QSize(150, 34))
        self.years_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_text_2.setFont(font)
        self.years_text_2.setWordWrap(True)
        self.years_text_2.setObjectName("years_text_2")
        self._12.addWidget(self.years_text_2)
        self.dive_access_mode = QtGui.QLineEdit(self.home_port_6)
        self.dive_access_mode.setEnabled(True)
        self.dive_access_mode.setMinimumSize(QtCore.QSize(100, 0))
        self.dive_access_mode.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dive_access_mode.setFont(font)
        self.dive_access_mode.setObjectName("dive_access_mode")
        self._12.addWidget(self.dive_access_mode)
        self.verticalLayout_4.addWidget(self.home_port_6)
        self.home_port_12 = QtGui.QWidget(self.DiveFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_12.setFont(font)
        self.home_port_12.setObjectName("home_port_12")
        self._23 = QtGui.QHBoxLayout(self.home_port_12)
        self._23.setSpacing(4)
        self._23.setMargin(4)
        self._23.setObjectName("_23")
        self.landing_port_text_7 = QtGui.QLabel(self.home_port_12)
        self.landing_port_text_7.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_7.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_7.setFont(font)
        self.landing_port_text_7.setObjectName("landing_port_text_7")
        self._23.addWidget(self.landing_port_text_7)
        self.dive_percent_island = QtGui.QLineEdit(self.home_port_12)
        self.dive_percent_island.setEnabled(True)
        self.dive_percent_island.setMinimumSize(QtCore.QSize(200, 0))
        self.dive_percent_island.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dive_percent_island.setFont(font)
        self.dive_percent_island.setObjectName("dive_percent_island")
        self._23.addWidget(self.dive_percent_island)
        self.verticalLayout_4.addWidget(self.home_port_12)
        self.home_port_13 = QtGui.QWidget(self.DiveFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_13.setFont(font)
        self.home_port_13.setObjectName("home_port_13")
        self._25 = QtGui.QHBoxLayout(self.home_port_13)
        self._25.setSpacing(4)
        self._25.setMargin(4)
        self._25.setObjectName("_25")
        self.landing_port_text_8 = QtGui.QLabel(self.home_port_13)
        self.landing_port_text_8.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_8.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_8.setFont(font)
        self.landing_port_text_8.setObjectName("landing_port_text_8")
        self._25.addWidget(self.landing_port_text_8)
        self.dive_percent_shore = QtGui.QLineEdit(self.home_port_13)
        self.dive_percent_shore.setEnabled(True)
        self.dive_percent_shore.setMinimumSize(QtCore.QSize(200, 0))
        self.dive_percent_shore.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dive_percent_shore.setFont(font)
        self.dive_percent_shore.setObjectName("dive_percent_shore")
        self._25.addWidget(self.dive_percent_shore)
        self.verticalLayout_4.addWidget(self.home_port_13)
        self.home_port_11 = QtGui.QWidget(self.DiveFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_11.setFont(font)
        self.home_port_11.setObjectName("home_port_11")
        self._22 = QtGui.QHBoxLayout(self.home_port_11)
        self._22.setSpacing(4)
        self._22.setMargin(4)
        self._22.setObjectName("_22")
        self.landing_port_text_6 = QtGui.QLabel(self.home_port_11)
        self.landing_port_text_6.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_6.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_6.setFont(font)
        self.landing_port_text_6.setObjectName("landing_port_text_6")
        self._22.addWidget(self.landing_port_text_6)
        self.dive_primary_method = QtGui.QComboBox(self.home_port_11)
        self.dive_primary_method.setMinimumSize(QtCore.QSize(170, 0))
        self.dive_primary_method.setMaximumSize(QtCore.QSize(170, 16777215))
        self.dive_primary_method.setObjectName("dive_primary_method")
        self.dive_primary_method.addItem(QtCore.QString())
        self.dive_primary_method.setItemText(0, "")
        self.dive_primary_method.addItem(QtCore.QString())
        self.dive_primary_method.addItem(QtCore.QString())
        self.dive_primary_method.addItem(QtCore.QString())
        self._22.addWidget(self.dive_primary_method)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._22.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.home_port_11)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.DiveFishing)
        self.KayakFishing = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.KayakFishing.setFont(font)
        self.KayakFishing.setObjectName("KayakFishing")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.KayakFishing)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.home_port_17 = QtGui.QWidget(self.KayakFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_17.setFont(font)
        self.home_port_17.setObjectName("home_port_17")
        self._9 = QtGui.QHBoxLayout(self.home_port_17)
        self._9.setSpacing(4)
        self._9.setMargin(4)
        self._9.setObjectName("_9")
        self.landing_port_text_11 = QtGui.QLabel(self.home_port_17)
        self.landing_port_text_11.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_11.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_11.setFont(font)
        self.landing_port_text_11.setObjectName("landing_port_text_11")
        self._9.addWidget(self.landing_port_text_11)
        self.kyk_launch_port_1 = QtGui.QLineEdit(self.home_port_17)
        self.kyk_launch_port_1.setEnabled(True)
        self.kyk_launch_port_1.setMinimumSize(QtCore.QSize(200, 0))
        self.kyk_launch_port_1.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kyk_launch_port_1.setFont(font)
        self.kyk_launch_port_1.setObjectName("kyk_launch_port_1")
        self._9.addWidget(self.kyk_launch_port_1)
        self.verticalLayout_3.addWidget(self.home_port_17)
        self.home_port_15 = QtGui.QWidget(self.KayakFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_15.setFont(font)
        self.home_port_15.setObjectName("home_port_15")
        self._8 = QtGui.QHBoxLayout(self.home_port_15)
        self._8.setSpacing(4)
        self._8.setMargin(4)
        self._8.setObjectName("_8")
        self.landing_port_text_9 = QtGui.QLabel(self.home_port_15)
        self.landing_port_text_9.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_9.setFont(font)
        self.landing_port_text_9.setObjectName("landing_port_text_9")
        self._8.addWidget(self.landing_port_text_9)
        self.kyk_launch_port_2 = QtGui.QLineEdit(self.home_port_15)
        self.kyk_launch_port_2.setEnabled(True)
        self.kyk_launch_port_2.setMinimumSize(QtCore.QSize(200, 0))
        self.kyk_launch_port_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kyk_launch_port_2.setFont(font)
        self.kyk_launch_port_2.setObjectName("kyk_launch_port_2")
        self._8.addWidget(self.kyk_launch_port_2)
        self.verticalLayout_3.addWidget(self.home_port_15)
        self.home_port_16 = QtGui.QWidget(self.KayakFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_16.setFont(font)
        self.home_port_16.setObjectName("home_port_16")
        self._27 = QtGui.QHBoxLayout(self.home_port_16)
        self._27.setSpacing(4)
        self._27.setMargin(4)
        self._27.setObjectName("_27")
        self.landing_port_text_10 = QtGui.QLabel(self.home_port_16)
        self.landing_port_text_10.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_10.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_10.setFont(font)
        self.landing_port_text_10.setObjectName("landing_port_text_10")
        self._27.addWidget(self.landing_port_text_10)
        self.kyk_launch_port_3 = QtGui.QLineEdit(self.home_port_16)
        self.kyk_launch_port_3.setEnabled(True)
        self.kyk_launch_port_3.setMinimumSize(QtCore.QSize(200, 0))
        self.kyk_launch_port_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kyk_launch_port_3.setFont(font)
        self.kyk_launch_port_3.setObjectName("kyk_launch_port_3")
        self._27.addWidget(self.kyk_launch_port_3)
        self.verticalLayout_3.addWidget(self.home_port_16)
        self.home_port_14 = QtGui.QWidget(self.KayakFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_14.setFont(font)
        self.home_port_14.setObjectName("home_port_14")
        self._26 = QtGui.QHBoxLayout(self.home_port_14)
        self._26.setSpacing(4)
        self._26.setMargin(4)
        self._26.setObjectName("_26")
        self.landing_port_text_5 = QtGui.QLabel(self.home_port_14)
        self.landing_port_text_5.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_5.setFont(font)
        self.landing_port_text_5.setObjectName("landing_port_text_5")
        self._26.addWidget(self.landing_port_text_5)
        self.kyk_launch_port_4 = QtGui.QLineEdit(self.home_port_14)
        self.kyk_launch_port_4.setEnabled(True)
        self.kyk_launch_port_4.setMinimumSize(QtCore.QSize(200, 0))
        self.kyk_launch_port_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kyk_launch_port_4.setFont(font)
        self.kyk_launch_port_4.setObjectName("kyk_launch_port_4")
        self._26.addWidget(self.kyk_launch_port_4)
        self.verticalLayout_3.addWidget(self.home_port_14)
        self.ves_license_4 = QtGui.QWidget(self.KayakFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license_4.setFont(font)
        self.ves_license_4.setObjectName("ves_license_4")
        self._21 = QtGui.QHBoxLayout(self.ves_license_4)
        self._21.setSpacing(4)
        self._21.setMargin(4)
        self._21.setObjectName("_21")
        self.yrs_operating_text_3 = QtGui.QLabel(self.ves_license_4)
        self.yrs_operating_text_3.setMinimumSize(QtCore.QSize(150, 0))
        self.yrs_operating_text_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yrs_operating_text_3.setFont(font)
        self.yrs_operating_text_3.setObjectName("yrs_operating_text_3")
        self._21.addWidget(self.yrs_operating_text_3)
        self.kyk_years_experience = QtGui.QLineEdit(self.ves_license_4)
        self.kyk_years_experience.setEnabled(True)
        self.kyk_years_experience.setMinimumSize(QtCore.QSize(200, 0))
        self.kyk_years_experience.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kyk_years_experience.setFont(font)
        self.kyk_years_experience.setObjectName("kyk_years_experience")
        self._21.addWidget(self.kyk_years_experience)
        self.verticalLayout_3.addWidget(self.ves_license_4)
        self.home_port_10 = QtGui.QWidget(self.KayakFishing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_10.setFont(font)
        self.home_port_10.setObjectName("home_port_10")
        self._24 = QtGui.QHBoxLayout(self.home_port_10)
        self._24.setSpacing(4)
        self._24.setMargin(4)
        self._24.setObjectName("_24")
        self.years_text_3 = QtGui.QLabel(self.home_port_10)
        self.years_text_3.setMinimumSize(QtCore.QSize(150, 34))
        self.years_text_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_text_3.setFont(font)
        self.years_text_3.setWordWrap(True)
        self.years_text_3.setObjectName("years_text_3")
        self._24.addWidget(self.years_text_3)
        self.kyk_avg_days_per_year = QtGui.QLineEdit(self.home_port_10)
        self.kyk_avg_days_per_year.setEnabled(True)
        self.kyk_avg_days_per_year.setMinimumSize(QtCore.QSize(100, 0))
        self.kyk_avg_days_per_year.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kyk_avg_days_per_year.setFont(font)
        self.kyk_avg_days_per_year.setObjectName("kyk_avg_days_per_year")
        self._24.addWidget(self.kyk_avg_days_per_year)
        self.verticalLayout_3.addWidget(self.home_port_10)
        self.verticalLayout_2.addWidget(self.KayakFishing)

        self.retranslateUi(RecAll)
        QtCore.QMetaObject.connectSlotsByName(RecAll)
        RecAll.setTabOrder(self.type_boat_line, self.boat_license_line)
        RecAll.setTabOrder(self.boat_license_line, self.yrs_operating_line)
        RecAll.setTabOrder(self.yrs_operating_line, self.yrs_owning_line)
        RecAll.setTabOrder(self.yrs_owning_line, self.vessel_length_line)
        RecAll.setTabOrder(self.vessel_length_line, self.storage_loc_line)
        RecAll.setTabOrder(self.storage_loc_line, self.home_port_line)
        RecAll.setTabOrder(self.home_port_line, self.landing_port_line)
        RecAll.setTabOrder(self.landing_port_line, self.landing_port_line_2)
        RecAll.setTabOrder(self.landing_port_line_2, self.landing_port_line_3)
        RecAll.setTabOrder(self.landing_port_line_3, self.landing_port_line_4)
        RecAll.setTabOrder(self.landing_port_line_4, self.years_fishing_line)
        RecAll.setTabOrder(self.years_fishing_line, self.avg_people_line)
        RecAll.setTabOrder(self.avg_people_line, self.avg_days_per_year_line)
        RecAll.setTabOrder(self.avg_days_per_year_line, self.dive_avg_dives_per_trip)
        RecAll.setTabOrder(self.dive_avg_dives_per_trip, self.dive_access_mode)
        RecAll.setTabOrder(self.dive_access_mode, self.dive_percent_island)
        RecAll.setTabOrder(self.dive_percent_island, self.dive_percent_shore)
        RecAll.setTabOrder(self.dive_percent_shore, self.kyk_launch_port_1)
        RecAll.setTabOrder(self.kyk_launch_port_1, self.kyk_launch_port_2)
        RecAll.setTabOrder(self.kyk_launch_port_2, self.kyk_launch_port_3)
        RecAll.setTabOrder(self.kyk_launch_port_3, self.kyk_launch_port_4)
        RecAll.setTabOrder(self.kyk_launch_port_4, self.kyk_years_experience)
        RecAll.setTabOrder(self.kyk_years_experience, self.kyk_avg_days_per_year)
        RecAll.setTabOrder(self.kyk_avg_days_per_year, self.pbnSelectFishery)
        RecAll.setTabOrder(self.pbnSelectFishery, self.pbnCancel)

    def retranslateUi(self, RecAll):
        RecAll.setWindowTitle(QtGui.QApplication.translate("RecAll", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("RecAll", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectFishery.setText(QtGui.QApplication.translate("RecAll", "Select Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("RecAll", "Private Vessel Fishing Information", None, QtGui.QApplication.UnicodeUTF8))
        self.perc_income_text.setText(QtGui.QApplication.translate("RecAll", "Type of boat:", None, QtGui.QApplication.UnicodeUTF8))
        self.boat_license_text.setText(QtGui.QApplication.translate("RecAll", "Dept F&G boat number:", None, QtGui.QApplication.UnicodeUTF8))
        self.yrs_operating_text.setText(QtGui.QApplication.translate("RecAll", "Yrs operating sport boat:", None, QtGui.QApplication.UnicodeUTF8))
        self.yrs_owning_text.setText(QtGui.QApplication.translate("RecAll", "Years of ownership:", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text.setText(QtGui.QApplication.translate("RecAll", "Vessel length (feet) :", None, QtGui.QApplication.UnicodeUTF8))
        self.storage_loc_text.setText(QtGui.QApplication.translate("RecAll", "Storage location:", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text.setText(QtGui.QApplication.translate("RecAll", "Home Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text.setText(QtGui.QApplication.translate("RecAll", "Launching Port 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_2.setText(QtGui.QApplication.translate("RecAll", "Launching Port 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_3.setText(QtGui.QApplication.translate("RecAll", "Launching Port 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_4.setText(QtGui.QApplication.translate("RecAll", "Launching Port 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text.setText(QtGui.QApplication.translate("RecAll", "Years experience fishing from sport boat:", None, QtGui.QApplication.UnicodeUTF8))
        self.avg_people_text.setText(QtGui.QApplication.translate("RecAll", "Avg # individuals on boat per trip:", None, QtGui.QApplication.UnicodeUTF8))
        self.avg_days_per_year_text.setText(QtGui.QApplication.translate("RecAll", "Avg # days fishing from boat per year:", None, QtGui.QApplication.UnicodeUTF8))
        self.DiveFishing.setTitle(QtGui.QApplication.translate("RecAll", "Dive Fishing Information", None, QtGui.QApplication.UnicodeUTF8))
        self.yrs_operating_text_2.setText(QtGui.QApplication.translate("RecAll", "Avg # dives per trip:", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text_2.setText(QtGui.QApplication.translate("RecAll", "Primary access mode to dive locs:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_7.setText(QtGui.QApplication.translate("RecAll", "% island dives:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_8.setText(QtGui.QApplication.translate("RecAll", "% shore dives:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_6.setText(QtGui.QApplication.translate("RecAll", "Primary dive method:", None, QtGui.QApplication.UnicodeUTF8))
        self.dive_primary_method.setItemText(1, QtGui.QApplication.translate("RecAll", "Free dive", None, QtGui.QApplication.UnicodeUTF8))
        self.dive_primary_method.setItemText(2, QtGui.QApplication.translate("RecAll", "SCUBA", None, QtGui.QApplication.UnicodeUTF8))
        self.dive_primary_method.setItemText(3, QtGui.QApplication.translate("RecAll", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.KayakFishing.setTitle(QtGui.QApplication.translate("RecAll", "Kayak Fishing Information", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_11.setText(QtGui.QApplication.translate("RecAll", "Kayak Launching Port 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_9.setText(QtGui.QApplication.translate("RecAll", "Kayak Launching Port 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_10.setText(QtGui.QApplication.translate("RecAll", "Kayak Launching Port 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_5.setText(QtGui.QApplication.translate("RecAll", "Kayak Launching Port 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.yrs_operating_text_3.setText(QtGui.QApplication.translate("RecAll", "Years experience:", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text_3.setText(QtGui.QApplication.translate("RecAll", "Avg # days fishing from kayak per year:", None, QtGui.QApplication.UnicodeUTF8))

