# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecotourism.ui'
#
# Created: Tue Mar 31 15:43:27 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Ecotourism(object):
    def setupUi(self, Ecotourism):
        Ecotourism.setObjectName("Ecotourism")
        Ecotourism.resize(621, 446)
        self.verticalLayout_6 = QtGui.QVBoxLayout(Ecotourism)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vessel_info = QtGui.QGroupBox(Ecotourism)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_port_5 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_5.setFont(font)
        self.home_port_5.setObjectName("home_port_5")
        self.hboxlayout = QtGui.QHBoxLayout(self.home_port_5)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(4)
        self.hboxlayout.setObjectName("hboxlayout")
        self.employee_text = QtGui.QLabel(self.home_port_5)
        self.employee_text.setMinimumSize(QtCore.QSize(180, 0))
        self.employee_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employee_text.setFont(font)
        self.employee_text.setObjectName("employee_text")
        self.hboxlayout.addWidget(self.employee_text)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.comboEmpType = QtGui.QComboBox(self.home_port_5)
        self.comboEmpType.setMinimumSize(QtCore.QSize(120, 0))
        self.comboEmpType.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboEmpType.setObjectName("comboEmpType")
        self.comboEmpType.addItem(QtCore.QString())
        self.comboEmpType.setItemText(0, "")
        self.comboEmpType.addItem(QtCore.QString())
        self.comboEmpType.addItem(QtCore.QString())
        self.comboEmpType.addItem(QtCore.QString())
        self.comboEmpType.addItem(QtCore.QString())
        self.hboxlayout.addWidget(self.comboEmpType)
        self.verticalLayout.addWidget(self.home_port_5)
        self.vessel_length = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length.setFont(font)
        self.vessel_length.setObjectName("vessel_length")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.vessel_length)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(4)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vessel_length_text = QtGui.QLabel(self.vessel_length)
        self.vessel_length_text.setMinimumSize(QtCore.QSize(180, 0))
        self.vessel_length_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_text.setFont(font)
        self.vessel_length_text.setObjectName("vessel_length_text")
        self.hboxlayout1.addWidget(self.vessel_length_text)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.vessel_length_line = QtGui.QLineEdit(self.vessel_length)
        self.vessel_length_line.setEnabled(True)
        self.vessel_length_line.setMinimumSize(QtCore.QSize(50, 0))
        self.vessel_length_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_line.setFont(font)
        self.vessel_length_line.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.vessel_length_line.setObjectName("vessel_length_line")
        self.hboxlayout1.addWidget(self.vessel_length_line)
        self.verticalLayout.addWidget(self.vessel_length)
        self.vessel_length_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_2.setFont(font)
        self.vessel_length_2.setObjectName("vessel_length_2")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.vessel_length_2)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.vessel_motor_text = QtGui.QLabel(self.vessel_length_2)
        self.vessel_motor_text.setMinimumSize(QtCore.QSize(180, 0))
        self.vessel_motor_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_text.setFont(font)
        self.vessel_motor_text.setObjectName("vessel_motor_text")
        self.hboxlayout2.addWidget(self.vessel_motor_text)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.vessel_motor_line = QtGui.QLineEdit(self.vessel_length_2)
        self.vessel_motor_line.setEnabled(True)
        self.vessel_motor_line.setMinimumSize(QtCore.QSize(50, 0))
        self.vessel_motor_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_line.setFont(font)
        self.vessel_motor_line.setObjectName("vessel_motor_line")
        self.hboxlayout2.addWidget(self.vessel_motor_line)
        self.verticalLayout.addWidget(self.vessel_length_2)
        self.vessel_length_3 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_3.setFont(font)
        self.vessel_length_3.setObjectName("vessel_length_3")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.vessel_length_3)
        self.hboxlayout3.setSpacing(4)
        self.hboxlayout3.setMargin(4)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.haul_capacity_text = QtGui.QLabel(self.vessel_length_3)
        self.haul_capacity_text.setMinimumSize(QtCore.QSize(180, 0))
        self.haul_capacity_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_text.setFont(font)
        self.haul_capacity_text.setObjectName("haul_capacity_text")
        self.hboxlayout3.addWidget(self.haul_capacity_text)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem3)
        self.haul_capacity_line = QtGui.QLineEdit(self.vessel_length_3)
        self.haul_capacity_line.setEnabled(True)
        self.haul_capacity_line.setMinimumSize(QtCore.QSize(50, 0))
        self.haul_capacity_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_line.setFont(font)
        self.haul_capacity_line.setObjectName("haul_capacity_line")
        self.hboxlayout3.addWidget(self.haul_capacity_line)
        self.verticalLayout.addWidget(self.vessel_length_3)
        self.home_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port.setFont(font)
        self.home_port.setObjectName("home_port")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.home_port)
        self.hboxlayout4.setSpacing(4)
        self.hboxlayout4.setMargin(4)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.home_port_text = QtGui.QLabel(self.home_port)
        self.home_port_text.setMinimumSize(QtCore.QSize(180, 0))
        self.home_port_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_text.setFont(font)
        self.home_port_text.setObjectName("home_port_text")
        self.hboxlayout4.addWidget(self.home_port_text)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem4)
        self.home_port_line = QtGui.QLineEdit(self.home_port)
        self.home_port_line.setEnabled(True)
        self.home_port_line.setMinimumSize(QtCore.QSize(100, 0))
        self.home_port_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_line.setFont(font)
        self.home_port_line.setObjectName("home_port_line")
        self.hboxlayout4.addWidget(self.home_port_line)
        self.verticalLayout.addWidget(self.home_port)
        self.home_port_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_4.setFont(font)
        self.home_port_4.setObjectName("home_port_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.home_port_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.workers_text = QtGui.QLabel(self.home_port_4)
        self.workers_text.setMinimumSize(QtCore.QSize(150, 0))
        self.workers_text.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.workers_text.setFont(font)
        self.workers_text.setObjectName("workers_text")
        self.horizontalLayout.addWidget(self.workers_text)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.workers_line = QtGui.QLineEdit(self.home_port_4)
        self.workers_line.setEnabled(True)
        self.workers_line.setMinimumSize(QtCore.QSize(40, 25))
        self.workers_line.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.workers_line.setFont(font)
        self.workers_line.setObjectName("workers_line")
        self.horizontalLayout.addWidget(self.workers_line)
        self.verticalLayout.addWidget(self.home_port_4)
        self.verticalLayout_5.addWidget(self.vessel_info)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.groupBox = QtGui.QGroupBox(Ecotourism)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self._14 = QtGui.QHBoxLayout()
        self._14.setObjectName("_14")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setMinimumSize(QtCore.QSize(140, 0))
        self.label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self._14.addWidget(self.label_12)
        self.activity_diving = QtGui.QLineEdit(self.groupBox)
        self.activity_diving.setEnabled(True)
        self.activity_diving.setMinimumSize(QtCore.QSize(30, 0))
        self.activity_diving.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_diving.setFont(font)
        self.activity_diving.setObjectName("activity_diving")
        self._14.addWidget(self.activity_diving)
        self.verticalLayout_10.addLayout(self._14)
        self._15 = QtGui.QHBoxLayout()
        self._15.setObjectName("_15")
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setMinimumSize(QtCore.QSize(140, 0))
        self.label_13.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self._15.addWidget(self.label_13)
        self.activity_snorkeling = QtGui.QLineEdit(self.groupBox)
        self.activity_snorkeling.setEnabled(True)
        self.activity_snorkeling.setMinimumSize(QtCore.QSize(30, 0))
        self.activity_snorkeling.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_snorkeling.setFont(font)
        self.activity_snorkeling.setObjectName("activity_snorkeling")
        self._15.addWidget(self.activity_snorkeling)
        self.verticalLayout_10.addLayout(self._15)
        self._16 = QtGui.QHBoxLayout()
        self._16.setObjectName("_16")
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(140, 0))
        self.label_14.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self._16.addWidget(self.label_14)
        self.activity_kayaking = QtGui.QLineEdit(self.groupBox)
        self.activity_kayaking.setEnabled(True)
        self.activity_kayaking.setMinimumSize(QtCore.QSize(30, 0))
        self.activity_kayaking.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_kayaking.setFont(font)
        self.activity_kayaking.setObjectName("activity_kayaking")
        self._16.addWidget(self.activity_kayaking)
        self.verticalLayout_10.addLayout(self._16)
        self._17 = QtGui.QHBoxLayout()
        self._17.setObjectName("_17")
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setMinimumSize(QtCore.QSize(140, 0))
        self.label_15.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self._17.addWidget(self.label_15)
        self.activity_watching = QtGui.QLineEdit(self.groupBox)
        self.activity_watching.setEnabled(True)
        self.activity_watching.setMinimumSize(QtCore.QSize(30, 0))
        self.activity_watching.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_watching.setFont(font)
        self.activity_watching.setObjectName("activity_watching")
        self._17.addWidget(self.activity_watching)
        self.verticalLayout_10.addLayout(self._17)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        spacerItem8 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setMinimumSize(QtCore.QSize(80, 0))
        self.label_21.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setMinimumSize(QtCore.QSize(80, 0))
        self.label_23.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.activity_other_1_name = QtGui.QLineEdit(self.groupBox)
        self.activity_other_1_name.setEnabled(True)
        self.activity_other_1_name.setMinimumSize(QtCore.QSize(100, 0))
        self.activity_other_1_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_other_1_name.setFont(font)
        self.activity_other_1_name.setObjectName("activity_other_1_name")
        self.horizontalLayout_3.addWidget(self.activity_other_1_name)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setMinimumSize(QtCore.QSize(140, 0))
        self.label_22.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.activity_other_1_interest = QtGui.QLineEdit(self.groupBox)
        self.activity_other_1_interest.setEnabled(True)
        self.activity_other_1_interest.setMinimumSize(QtCore.QSize(30, 0))
        self.activity_other_1_interest.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_other_1_interest.setFont(font)
        self.activity_other_1_interest.setObjectName("activity_other_1_interest")
        self.horizontalLayout_4.addWidget(self.activity_other_1_interest)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setMinimumSize(QtCore.QSize(80, 0))
        self.label_24.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setMinimumSize(QtCore.QSize(80, 0))
        self.label_25.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.activity_other_2_name = QtGui.QLineEdit(self.groupBox)
        self.activity_other_2_name.setEnabled(True)
        self.activity_other_2_name.setMinimumSize(QtCore.QSize(100, 0))
        self.activity_other_2_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_other_2_name.setFont(font)
        self.activity_other_2_name.setObjectName("activity_other_2_name")
        self.horizontalLayout_5.addWidget(self.activity_other_2_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setMinimumSize(QtCore.QSize(140, 0))
        self.label_26.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        self.activity_other_2_interest = QtGui.QLineEdit(self.groupBox)
        self.activity_other_2_interest.setEnabled(True)
        self.activity_other_2_interest.setMinimumSize(QtCore.QSize(30, 0))
        self.activity_other_2_interest.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.activity_other_2_interest.setFont(font)
        self.activity_other_2_interest.setObjectName("activity_other_2_interest")
        self.horizontalLayout_6.addWidget(self.activity_other_2_interest)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.button_box = QtGui.QWidget(Ecotourism)
        self.button_box.setObjectName("button_box")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.button_box)
        self.hboxlayout5.setObjectName("hboxlayout5")
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem10)
        self.pbnExitEcoStep = QtGui.QPushButton(self.button_box)
        self.pbnExitEcoStep.setObjectName("pbnExitEcoStep")
        self.hboxlayout5.addWidget(self.pbnExitEcoStep)
        self.pbnSelectActivity = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbnSelectActivity.setFont(font)
        self.pbnSelectActivity.setObjectName("pbnSelectActivity")
        self.hboxlayout5.addWidget(self.pbnSelectActivity)
        self.verticalLayout_6.addWidget(self.button_box)

        self.retranslateUi(Ecotourism)
        QtCore.QMetaObject.connectSlotsByName(Ecotourism)

    def retranslateUi(self, Ecotourism):
        Ecotourism.setWindowTitle(QtGui.QApplication.translate("Ecotourism", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("Ecotourism", "Ecotourism Information", None, QtGui.QApplication.UnicodeUTF8))
        self.employee_text.setText(QtGui.QApplication.translate("Ecotourism", "Type of Employee:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEmpType.setItemText(1, QtGui.QApplication.translate("Ecotourism", "Captain of Boat", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEmpType.setItemText(2, QtGui.QApplication.translate("Ecotourism", "Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEmpType.setItemText(3, QtGui.QApplication.translate("Ecotourism", "Boat Owner", None, QtGui.QApplication.UnicodeUTF8))
        self.comboEmpType.setItemText(4, QtGui.QApplication.translate("Ecotourism", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text.setText(QtGui.QApplication.translate("Ecotourism", "Vessel length (meters) :", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_line.setText(QtGui.QApplication.translate("Ecotourism", "79", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_text.setText(QtGui.QApplication.translate("Ecotourism", "Vessel motor (hp):", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_line.setText(QtGui.QApplication.translate("Ecotourism", "179", None, QtGui.QApplication.UnicodeUTF8))
        self.haul_capacity_text.setText(QtGui.QApplication.translate("Ecotourism", "Haul Capacity (kg):", None, QtGui.QApplication.UnicodeUTF8))
        self.haul_capacity_line.setText(QtGui.QApplication.translate("Ecotourism", "4000", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text.setText(QtGui.QApplication.translate("Ecotourism", "Home Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_line.setText(QtGui.QApplication.translate("Ecotourism", "hp1", None, QtGui.QApplication.UnicodeUTF8))
        self.workers_text.setText(QtGui.QApplication.translate("Ecotourism", "How many people  work for the company?", None, QtGui.QApplication.UnicodeUTF8))
        self.workers_line.setText(QtGui.QApplication.translate("Ecotourism", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Ecotourism", "Ecotourism Activities", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Ecotourism", "What percent interest do you have in each activity? (Must add up to 100)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Ecotourism", "Diving:", None, QtGui.QApplication.UnicodeUTF8))
        self.activity_diving.setText(QtGui.QApplication.translate("Ecotourism", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Ecotourism", "Snorkeling:", None, QtGui.QApplication.UnicodeUTF8))
        self.activity_snorkeling.setText(QtGui.QApplication.translate("Ecotourism", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Ecotourism", "Kayaking:", None, QtGui.QApplication.UnicodeUTF8))
        self.activity_kayaking.setText(QtGui.QApplication.translate("Ecotourism", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Ecotourism", "Marine Fauna Watching", None, QtGui.QApplication.UnicodeUTF8))
        self.activity_watching.setText(QtGui.QApplication.translate("Ecotourism", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Ecotourism", "Other activity #1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Ecotourism", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Ecotourism", "% interest:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Ecotourism", "Other activity #2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Ecotourism", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Ecotourism", "% interest:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnExitEcoStep.setText(QtGui.QApplication.translate("Ecotourism", "Exit Ecotourism Step", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectActivity.setText(QtGui.QApplication.translate("Ecotourism", "Start Drawing Shapes", None, QtGui.QApplication.UnicodeUTF8))

