# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecotourism.ui'
#
# Created: Sun Mar 29 17:20:49 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Ecotourism(object):
    def setupUi(self, Ecotourism):
        Ecotourism.setObjectName("Ecotourism")
        Ecotourism.resize(478, 334)
        self.button_box = QtGui.QWidget(Ecotourism)
        self.button_box.setGeometry(QtCore.QRect(9, 261, 460, 101))
        self.button_box.setObjectName("button_box")
        self.hboxlayout = QtGui.QHBoxLayout(self.button_box)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.pbnExitEcoStep = QtGui.QPushButton(self.button_box)
        self.pbnExitEcoStep.setObjectName("pbnExitEcoStep")
        self.hboxlayout.addWidget(self.pbnExitEcoStep)
        self.pbnSelectActivity = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbnSelectActivity.setFont(font)
        self.pbnSelectActivity.setObjectName("pbnSelectActivity")
        self.hboxlayout.addWidget(self.pbnSelectActivity)
        self.widget = QtGui.QWidget(Ecotourism)
        self.widget.setGeometry(QtCore.QRect(9, 9, 454, 272))
        self.widget.setObjectName("widget")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vessel_info = QtGui.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_port_5 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_5.setFont(font)
        self.home_port_5.setObjectName("home_port_5")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.home_port_5)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.employee_text = QtGui.QLabel(self.home_port_5)
        self.employee_text.setMinimumSize(QtCore.QSize(220, 0))
        self.employee_text.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employee_text.setFont(font)
        self.employee_text.setObjectName("employee_text")
        self.hboxlayout2.addWidget(self.employee_text)
        self.comboBox = QtGui.QComboBox(self.home_port_5)
        self.comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.hboxlayout2.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.home_port_5)
        self.vessel_length = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length.setFont(font)
        self.vessel_length.setObjectName("vessel_length")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.vessel_length)
        self.hboxlayout3.setSpacing(4)
        self.hboxlayout3.setMargin(4)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.vessel_length_text = QtGui.QLabel(self.vessel_length)
        self.vessel_length_text.setMinimumSize(QtCore.QSize(220, 0))
        self.vessel_length_text.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_text.setFont(font)
        self.vessel_length_text.setObjectName("vessel_length_text")
        self.hboxlayout3.addWidget(self.vessel_length_text)
        self.vessel_length_line = QtGui.QLineEdit(self.vessel_length)
        self.vessel_length_line.setEnabled(True)
        self.vessel_length_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_length_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_line.setFont(font)
        self.vessel_length_line.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.vessel_length_line.setObjectName("vessel_length_line")
        self.hboxlayout3.addWidget(self.vessel_length_line)
        self.verticalLayout.addWidget(self.vessel_length)
        self.vessel_length_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_2.setFont(font)
        self.vessel_length_2.setObjectName("vessel_length_2")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.vessel_length_2)
        self.hboxlayout4.setSpacing(4)
        self.hboxlayout4.setMargin(4)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.vessel_motor_text = QtGui.QLabel(self.vessel_length_2)
        self.vessel_motor_text.setMinimumSize(QtCore.QSize(220, 0))
        self.vessel_motor_text.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_text.setFont(font)
        self.vessel_motor_text.setObjectName("vessel_motor_text")
        self.hboxlayout4.addWidget(self.vessel_motor_text)
        self.vessel_motor_line = QtGui.QLineEdit(self.vessel_length_2)
        self.vessel_motor_line.setEnabled(True)
        self.vessel_motor_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_motor_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_line.setFont(font)
        self.vessel_motor_line.setObjectName("vessel_motor_line")
        self.hboxlayout4.addWidget(self.vessel_motor_line)
        self.verticalLayout.addWidget(self.vessel_length_2)
        self.vessel_length_3 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_3.setFont(font)
        self.vessel_length_3.setObjectName("vessel_length_3")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.vessel_length_3)
        self.hboxlayout5.setSpacing(4)
        self.hboxlayout5.setMargin(4)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.haul_capacity_text = QtGui.QLabel(self.vessel_length_3)
        self.haul_capacity_text.setMinimumSize(QtCore.QSize(220, 0))
        self.haul_capacity_text.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_text.setFont(font)
        self.haul_capacity_text.setObjectName("haul_capacity_text")
        self.hboxlayout5.addWidget(self.haul_capacity_text)
        self.haul_capacity_line = QtGui.QLineEdit(self.vessel_length_3)
        self.haul_capacity_line.setEnabled(True)
        self.haul_capacity_line.setMinimumSize(QtCore.QSize(200, 0))
        self.haul_capacity_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_line.setFont(font)
        self.haul_capacity_line.setObjectName("haul_capacity_line")
        self.hboxlayout5.addWidget(self.haul_capacity_line)
        self.verticalLayout.addWidget(self.vessel_length_3)
        self.home_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port.setFont(font)
        self.home_port.setObjectName("home_port")
        self.hboxlayout6 = QtGui.QHBoxLayout(self.home_port)
        self.hboxlayout6.setSpacing(4)
        self.hboxlayout6.setMargin(4)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.home_port_text = QtGui.QLabel(self.home_port)
        self.home_port_text.setMinimumSize(QtCore.QSize(220, 0))
        self.home_port_text.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_text.setFont(font)
        self.home_port_text.setObjectName("home_port_text")
        self.hboxlayout6.addWidget(self.home_port_text)
        self.home_port_line = QtGui.QLineEdit(self.home_port)
        self.home_port_line.setEnabled(True)
        self.home_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.home_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_line.setFont(font)
        self.home_port_line.setObjectName("home_port_line")
        self.hboxlayout6.addWidget(self.home_port_line)
        self.verticalLayout.addWidget(self.home_port)
        self.home_port_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_4.setFont(font)
        self.home_port_4.setObjectName("home_port_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.home_port_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.workers_text = QtGui.QLabel(self.home_port_4)
        self.workers_text.setMinimumSize(QtCore.QSize(150, 0))
        self.workers_text.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.workers_text.setFont(font)
        self.workers_text.setObjectName("workers_text")
        self.horizontalLayout.addWidget(self.workers_text)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.workers_line = QtGui.QLineEdit(self.home_port_4)
        self.workers_line.setEnabled(True)
        self.workers_line.setMinimumSize(QtCore.QSize(40, 20))
        self.workers_line.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.workers_line.setFont(font)
        self.workers_line.setObjectName("workers_line")
        self.horizontalLayout.addWidget(self.workers_line)
        self.verticalLayout.addWidget(self.home_port_4)
        self.hboxlayout1.addWidget(self.vessel_info)

        self.retranslateUi(Ecotourism)
        QtCore.QMetaObject.connectSlotsByName(Ecotourism)

    def retranslateUi(self, Ecotourism):
        Ecotourism.setWindowTitle(QtGui.QApplication.translate("Ecotourism", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnExitEcoStep.setText(QtGui.QApplication.translate("Ecotourism", "Exit Ecotourism Step", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectActivity.setText(QtGui.QApplication.translate("Ecotourism", "Select Activity Type", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("Ecotourism", "Ecotourism Info", None, QtGui.QApplication.UnicodeUTF8))
        self.employee_text.setText(QtGui.QApplication.translate("Ecotourism", "Type of Employee:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Ecotourism", "Captain of Boat", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Ecotourism", "Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Ecotourism", "Boat Owner", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("Ecotourism", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text.setText(QtGui.QApplication.translate("Ecotourism", "Vessel length (meters) :", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_line.setText(QtGui.QApplication.translate("Ecotourism", "79", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_text.setText(QtGui.QApplication.translate("Ecotourism", "Vessel motor (horsepower):", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_line.setText(QtGui.QApplication.translate("Ecotourism", "179", None, QtGui.QApplication.UnicodeUTF8))
        self.haul_capacity_text.setText(QtGui.QApplication.translate("Ecotourism", "Haul Capacity (kilograms):", None, QtGui.QApplication.UnicodeUTF8))
        self.haul_capacity_line.setText(QtGui.QApplication.translate("Ecotourism", "4000", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text.setText(QtGui.QApplication.translate("Ecotourism", "Home Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_line.setText(QtGui.QApplication.translate("Ecotourism", "hp1", None, QtGui.QApplication.UnicodeUTF8))
        self.workers_text.setText(QtGui.QApplication.translate("Ecotourism", "How many people  work for the company?", None, QtGui.QApplication.UnicodeUTF8))
        self.workers_line.setText(QtGui.QApplication.translate("Ecotourism", "3", None, QtGui.QApplication.UnicodeUTF8))

