# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fishery.ui'
#
# Created: Sun Mar 29 17:09:13 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Fishery(object):
    def setupUi(self, Fishery):
        Fishery.setObjectName("Fishery")
        Fishery.resize(692, 550)
        self.verticalLayout_9 = QtGui.QVBoxLayout(Fishery)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtGui.QGroupBox(Fishery)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 63))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout.setObjectName("hboxlayout")
        self.fishery_sector_label = QtGui.QLabel(self.groupBox)
        self.fishery_sector_label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fishery_sector_label.setFont(font)
        self.fishery_sector_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fishery_sector_label.setObjectName("fishery_sector_label")
        self.hboxlayout.addWidget(self.fishery_sector_label)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.vessel_info = QtGui.QGroupBox(Fishery)
        self.vessel_info.setMinimumSize(QtCore.QSize(30, 0))
        self.vessel_info.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_port_5 = QtGui.QWidget(self.vessel_info)
        self.home_port_5.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_5.setFont(font)
        self.home_port_5.setObjectName("home_port_5")
        self.horizontalLayout = QtGui.QHBoxLayout(self.home_port_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.employee_text = QtGui.QLabel(self.home_port_5)
        self.employee_text.setMinimumSize(QtCore.QSize(150, 0))
        self.employee_text.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employee_text.setFont(font)
        self.employee_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.employee_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.employee_text.setObjectName("employee_text")
        self.horizontalLayout.addWidget(self.employee_text)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBox = QtGui.QComboBox(self.home_port_5)
        self.comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.home_port_5)
        self.vessel_length = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length.setFont(font)
        self.vessel_length.setObjectName("vessel_length")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.vessel_length)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(4)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vessel_length_text = QtGui.QLabel(self.vessel_length)
        self.vessel_length_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_length_text.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_text.setFont(font)
        self.vessel_length_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vessel_length_text.setObjectName("vessel_length_text")
        self.hboxlayout1.addWidget(self.vessel_length_text)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.vessel_length_line = QtGui.QLineEdit(self.vessel_length)
        self.vessel_length_line.setEnabled(True)
        self.vessel_length_line.setMinimumSize(QtCore.QSize(60, 0))
        self.vessel_length_line.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_line.setFont(font)
        self.vessel_length_line.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.vessel_length_line.setObjectName("vessel_length_line")
        self.hboxlayout1.addWidget(self.vessel_length_line)
        self.verticalLayout.addWidget(self.vessel_length)
        self.vessel_length_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_2.setFont(font)
        self.vessel_length_2.setObjectName("vessel_length_2")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.vessel_length_2)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.vessel_motor_text = QtGui.QLabel(self.vessel_length_2)
        self.vessel_motor_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_motor_text.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_text.setFont(font)
        self.vessel_motor_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vessel_motor_text.setObjectName("vessel_motor_text")
        self.hboxlayout2.addWidget(self.vessel_motor_text)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.vessel_motor_line = QtGui.QLineEdit(self.vessel_length_2)
        self.vessel_motor_line.setEnabled(True)
        self.vessel_motor_line.setMinimumSize(QtCore.QSize(60, 0))
        self.vessel_motor_line.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_line.setFont(font)
        self.vessel_motor_line.setObjectName("vessel_motor_line")
        self.hboxlayout2.addWidget(self.vessel_motor_line)
        self.verticalLayout.addWidget(self.vessel_length_2)
        self.vessel_length_3 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_3.setFont(font)
        self.vessel_length_3.setObjectName("vessel_length_3")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.vessel_length_3)
        self.hboxlayout3.setSpacing(4)
        self.hboxlayout3.setMargin(4)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.haul_capacity_text = QtGui.QLabel(self.vessel_length_3)
        self.haul_capacity_text.setMinimumSize(QtCore.QSize(150, 0))
        self.haul_capacity_text.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_text.setFont(font)
        self.haul_capacity_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.haul_capacity_text.setObjectName("haul_capacity_text")
        self.hboxlayout3.addWidget(self.haul_capacity_text)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem3)
        self.haul_capacity_line = QtGui.QLineEdit(self.vessel_length_3)
        self.haul_capacity_line.setEnabled(True)
        self.haul_capacity_line.setMinimumSize(QtCore.QSize(60, 0))
        self.haul_capacity_line.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_line.setFont(font)
        self.haul_capacity_line.setObjectName("haul_capacity_line")
        self.hboxlayout3.addWidget(self.haul_capacity_line)
        self.verticalLayout.addWidget(self.vessel_length_3)
        self.home_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port.setFont(font)
        self.home_port.setObjectName("home_port")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.home_port)
        self.hboxlayout4.setSpacing(4)
        self.hboxlayout4.setMargin(4)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.home_port_text = QtGui.QLabel(self.home_port)
        self.home_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.home_port_text.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_text.setFont(font)
        self.home_port_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.home_port_text.setObjectName("home_port_text")
        self.hboxlayout4.addWidget(self.home_port_text)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem4)
        self.home_port_line = QtGui.QLineEdit(self.home_port)
        self.home_port_line.setEnabled(True)
        self.home_port_line.setMinimumSize(QtCore.QSize(100, 0))
        self.home_port_line.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_line.setFont(font)
        self.home_port_line.setObjectName("home_port_line")
        self.hboxlayout4.addWidget(self.home_port_line)
        self.verticalLayout.addWidget(self.home_port)
        self.home_port_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_4.setFont(font)
        self.home_port_4.setObjectName("home_port_4")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.home_port_4)
        self.hboxlayout5.setSpacing(4)
        self.hboxlayout5.setMargin(4)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.landing_port_text = QtGui.QLabel(self.home_port_4)
        self.landing_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text.setFont(font)
        self.landing_port_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.landing_port_text.setObjectName("landing_port_text")
        self.hboxlayout5.addWidget(self.landing_port_text)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem5)
        self.landing_port_line = QtGui.QLineEdit(self.home_port_4)
        self.landing_port_line.setEnabled(True)
        self.landing_port_line.setMinimumSize(QtCore.QSize(100, 0))
        self.landing_port_line.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line.setFont(font)
        self.landing_port_line.setObjectName("landing_port_line")
        self.hboxlayout5.addWidget(self.landing_port_line)
        self.verticalLayout.addWidget(self.home_port_4)
        self.home_port_7 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_7.setFont(font)
        self.home_port_7.setObjectName("home_port_7")
        self.hboxlayout6 = QtGui.QHBoxLayout(self.home_port_7)
        self.hboxlayout6.setSpacing(4)
        self.hboxlayout6.setMargin(4)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.landing_port_text_2 = QtGui.QLabel(self.home_port_7)
        self.landing_port_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_2.setFont(font)
        self.landing_port_text_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.landing_port_text_2.setObjectName("landing_port_text_2")
        self.hboxlayout6.addWidget(self.landing_port_text_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem6)
        self.landing_port_line_2 = QtGui.QLineEdit(self.home_port_7)
        self.landing_port_line_2.setEnabled(True)
        self.landing_port_line_2.setMinimumSize(QtCore.QSize(100, 0))
        self.landing_port_line_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_2.setFont(font)
        self.landing_port_line_2.setObjectName("landing_port_line_2")
        self.hboxlayout6.addWidget(self.landing_port_line_2)
        self.verticalLayout.addWidget(self.home_port_7)
        self.home_port_8 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_8.setFont(font)
        self.home_port_8.setObjectName("home_port_8")
        self.hboxlayout7 = QtGui.QHBoxLayout(self.home_port_8)
        self.hboxlayout7.setSpacing(4)
        self.hboxlayout7.setMargin(4)
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.landing_port_text_3 = QtGui.QLabel(self.home_port_8)
        self.landing_port_text_3.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_3.setFont(font)
        self.landing_port_text_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.landing_port_text_3.setObjectName("landing_port_text_3")
        self.hboxlayout7.addWidget(self.landing_port_text_3)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem7)
        self.landing_port_line_3 = QtGui.QLineEdit(self.home_port_8)
        self.landing_port_line_3.setEnabled(True)
        self.landing_port_line_3.setMinimumSize(QtCore.QSize(100, 0))
        self.landing_port_line_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_3.setFont(font)
        self.landing_port_line_3.setObjectName("landing_port_line_3")
        self.hboxlayout7.addWidget(self.landing_port_line_3)
        self.verticalLayout.addWidget(self.home_port_8)
        self.home_port_9 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_9.setFont(font)
        self.home_port_9.setObjectName("home_port_9")
        self.hboxlayout8 = QtGui.QHBoxLayout(self.home_port_9)
        self.hboxlayout8.setSpacing(4)
        self.hboxlayout8.setMargin(4)
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.landing_port_text_4 = QtGui.QLabel(self.home_port_9)
        self.landing_port_text_4.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_4.setFont(font)
        self.landing_port_text_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.landing_port_text_4.setObjectName("landing_port_text_4")
        self.hboxlayout8.addWidget(self.landing_port_text_4)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem8)
        self.landing_port_line_4 = QtGui.QLineEdit(self.home_port_9)
        self.landing_port_line_4.setEnabled(True)
        self.landing_port_line_4.setMinimumSize(QtCore.QSize(100, 0))
        self.landing_port_line_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_4.setFont(font)
        self.landing_port_line_4.setObjectName("landing_port_line_4")
        self.hboxlayout8.addWidget(self.landing_port_line_4)
        self.verticalLayout.addWidget(self.home_port_9)
        self.horizontalLayout_11.addWidget(self.vessel_info)
        self.groupBox_3 = QtGui.QGroupBox(Fishery)
        self.groupBox_3.setMinimumSize(QtCore.QSize(400, 385))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 29, 382, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.layoutWidget = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 65, 382, 310))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName("_5")
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(140, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self._5.addWidget(self.label_7)
        self.target_coastal = QtGui.QLineEdit(self.layoutWidget)
        self.target_coastal.setEnabled(True)
        self.target_coastal.setMinimumSize(QtCore.QSize(30, 0))
        self.target_coastal.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_coastal.setFont(font)
        self.target_coastal.setObjectName("target_coastal")
        self._5.addWidget(self.target_coastal)
        self.verticalLayout_7.addLayout(self._5)
        self._6 = QtGui.QHBoxLayout()
        self._6.setObjectName("_6")
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(140, 0))
        self.label_8.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self._6.addWidget(self.label_8)
        self.target_deep = QtGui.QLineEdit(self.layoutWidget)
        self.target_deep.setEnabled(True)
        self.target_deep.setMinimumSize(QtCore.QSize(30, 0))
        self.target_deep.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_deep.setFont(font)
        self.target_deep.setObjectName("target_deep")
        self._6.addWidget(self.target_deep)
        self.verticalLayout_7.addLayout(self._6)
        self._7 = QtGui.QHBoxLayout()
        self._7.setObjectName("_7")
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(140, 0))
        self.label_9.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self._7.addWidget(self.label_9)
        self.target_migratory = QtGui.QLineEdit(self.layoutWidget)
        self.target_migratory.setEnabled(True)
        self.target_migratory.setMinimumSize(QtCore.QSize(30, 0))
        self.target_migratory.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_migratory.setFont(font)
        self.target_migratory.setObjectName("target_migratory")
        self._7.addWidget(self.target_migratory)
        self.verticalLayout_7.addLayout(self._7)
        self._8 = QtGui.QHBoxLayout()
        self._8.setObjectName("_8")
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(140, 0))
        self.label_10.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self._8.addWidget(self.label_10)
        self.target_cucumber = QtGui.QLineEdit(self.layoutWidget)
        self.target_cucumber.setEnabled(True)
        self.target_cucumber.setMinimumSize(QtCore.QSize(30, 0))
        self.target_cucumber.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_cucumber.setFont(font)
        self.target_cucumber.setObjectName("target_cucumber")
        self._8.addWidget(self.target_cucumber)
        self.verticalLayout_7.addLayout(self._8)
        self._9 = QtGui.QHBoxLayout()
        self._9.setObjectName("_9")
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(140, 0))
        self.label_11.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self._9.addWidget(self.label_11)
        self.target_chocolate = QtGui.QLineEdit(self.layoutWidget)
        self.target_chocolate.setEnabled(True)
        self.target_chocolate.setMinimumSize(QtCore.QSize(30, 0))
        self.target_chocolate.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_chocolate.setFont(font)
        self.target_chocolate.setObjectName("target_chocolate")
        self._9.addWidget(self.target_chocolate)
        self.verticalLayout_7.addLayout(self._9)
        self._10 = QtGui.QHBoxLayout()
        self._10.setObjectName("_10")
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(140, 0))
        self.label_18.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self._10.addWidget(self.label_18)
        self.target_squid = QtGui.QLineEdit(self.layoutWidget)
        self.target_squid.setEnabled(True)
        self.target_squid.setMinimumSize(QtCore.QSize(30, 0))
        self.target_squid.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_squid.setFont(font)
        self.target_squid.setObjectName("target_squid")
        self._10.addWidget(self.target_squid)
        self.verticalLayout_7.addLayout(self._10)
        self._11 = QtGui.QHBoxLayout()
        self._11.setObjectName("_11")
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(140, 0))
        self.label_16.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self._11.addWidget(self.label_16)
        self.target_sharks = QtGui.QLineEdit(self.layoutWidget)
        self.target_sharks.setEnabled(True)
        self.target_sharks.setMinimumSize(QtCore.QSize(30, 0))
        self.target_sharks.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_sharks.setFont(font)
        self.target_sharks.setObjectName("target_sharks")
        self._11.addWidget(self.target_sharks)
        self.verticalLayout_7.addLayout(self._11)
        self._12 = QtGui.QHBoxLayout()
        self._12.setObjectName("_12")
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(140, 0))
        self.label_17.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self._12.addWidget(self.label_17)
        self.target_octopus = QtGui.QLineEdit(self.layoutWidget)
        self.target_octopus.setEnabled(True)
        self.target_octopus.setMinimumSize(QtCore.QSize(30, 0))
        self.target_octopus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_octopus.setFont(font)
        self.target_octopus.setObjectName("target_octopus")
        self._12.addWidget(self.target_octopus)
        self.verticalLayout_7.addLayout(self._12)
        self._13 = QtGui.QHBoxLayout()
        self._13.setObjectName("_13")
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(140, 0))
        self.label_20.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self._13.addWidget(self.label_20)
        self.target_bait = QtGui.QLineEdit(self.layoutWidget)
        self.target_bait.setEnabled(True)
        self.target_bait.setMinimumSize(QtCore.QSize(30, 0))
        self.target_bait.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_bait.setFont(font)
        self.target_bait.setObjectName("target_bait")
        self._13.addWidget(self.target_bait)
        self.verticalLayout_7.addLayout(self._13)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setMinimumSize(QtCore.QSize(80, 0))
        self.label_21.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setMinimumSize(QtCore.QSize(80, 0))
        self.label_23.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.target_other_1_name = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_1_name.setEnabled(True)
        self.target_other_1_name.setMinimumSize(QtCore.QSize(100, 0))
        self.target_other_1_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_1_name.setFont(font)
        self.target_other_1_name.setObjectName("target_other_1_name")
        self.horizontalLayout_2.addWidget(self.target_other_1_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtGui.QLabel(self.layoutWidget)
        self.label_22.setMinimumSize(QtCore.QSize(140, 0))
        self.label_22.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.target_other_1_interest = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_1_interest.setEnabled(True)
        self.target_other_1_interest.setMinimumSize(QtCore.QSize(30, 0))
        self.target_other_1_interest.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_1_interest.setFont(font)
        self.target_other_1_interest.setObjectName("target_other_1_interest")
        self.horizontalLayout_3.addWidget(self.target_other_1_interest)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setMinimumSize(QtCore.QSize(80, 0))
        self.label_24.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setMinimumSize(QtCore.QSize(80, 0))
        self.label_25.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.target_other_2_name = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_2_name.setEnabled(True)
        self.target_other_2_name.setMinimumSize(QtCore.QSize(100, 0))
        self.target_other_2_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_2_name.setFont(font)
        self.target_other_2_name.setObjectName("target_other_2_name")
        self.horizontalLayout_4.addWidget(self.target_other_2_name)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setMinimumSize(QtCore.QSize(140, 0))
        self.label_26.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_5.addWidget(self.label_26)
        self.target_other_2_interest = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_2_interest.setEnabled(True)
        self.target_other_2_interest.setMinimumSize(QtCore.QSize(30, 0))
        self.target_other_2_interest.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_2_interest.setFont(font)
        self.target_other_2_interest.setObjectName("target_other_2_interest")
        self.horizontalLayout_5.addWidget(self.target_other_2_interest)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        self.label_27.setMinimumSize(QtCore.QSize(80, 0))
        self.label_27.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        self.label_28.setMinimumSize(QtCore.QSize(80, 0))
        self.label_28.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.target_other_3_name = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_3_name.setEnabled(True)
        self.target_other_3_name.setMinimumSize(QtCore.QSize(100, 0))
        self.target_other_3_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_3_name.setFont(font)
        self.target_other_3_name.setObjectName("target_other_3_name")
        self.horizontalLayout_6.addWidget(self.target_other_3_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_29 = QtGui.QLabel(self.layoutWidget)
        self.label_29.setMinimumSize(QtCore.QSize(140, 0))
        self.label_29.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_7.addWidget(self.label_29)
        self.target_other_3_interest = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_3_interest.setEnabled(True)
        self.target_other_3_interest.setMinimumSize(QtCore.QSize(30, 0))
        self.target_other_3_interest.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_3_interest.setFont(font)
        self.target_other_3_interest.setObjectName("target_other_3_interest")
        self.horizontalLayout_7.addWidget(self.target_other_3_interest)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_30 = QtGui.QLabel(self.layoutWidget)
        self.label_30.setMinimumSize(QtCore.QSize(80, 0))
        self.label_30.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_5.addWidget(self.label_30)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_31 = QtGui.QLabel(self.layoutWidget)
        self.label_31.setMinimumSize(QtCore.QSize(80, 0))
        self.label_31.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_8.addWidget(self.label_31)
        self.target_other_4_name = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_4_name.setEnabled(True)
        self.target_other_4_name.setMinimumSize(QtCore.QSize(100, 0))
        self.target_other_4_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_4_name.setFont(font)
        self.target_other_4_name.setObjectName("target_other_4_name")
        self.horizontalLayout_8.addWidget(self.target_other_4_name)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_32 = QtGui.QLabel(self.layoutWidget)
        self.label_32.setMinimumSize(QtCore.QSize(140, 0))
        self.label_32.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_9.addWidget(self.label_32)
        self.target_other_4_interest = QtGui.QLineEdit(self.layoutWidget)
        self.target_other_4_interest.setEnabled(True)
        self.target_other_4_interest.setMinimumSize(QtCore.QSize(30, 0))
        self.target_other_4_interest.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.target_other_4_interest.setFont(font)
        self.target_other_4_interest.setObjectName("target_other_4_interest")
        self.horizontalLayout_9.addWidget(self.target_other_4_interest)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.button_box = QtGui.QWidget(Fishery)
        self.button_box.setObjectName("button_box")
        self.hboxlayout9 = QtGui.QHBoxLayout(self.button_box)
        self.hboxlayout9.setObjectName("hboxlayout9")
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout9.addItem(spacerItem10)
        self.pbnStartGroups = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnStartGroups.setFont(font)
        self.pbnStartGroups.setObjectName("pbnStartGroups")
        self.hboxlayout9.addWidget(self.pbnStartGroups)
        self.verticalLayout_9.addWidget(self.button_box)

        self.retranslateUi(Fishery)
        QtCore.QMetaObject.connectSlotsByName(Fishery)

    def retranslateUi(self, Fishery):
        Fishery.setWindowTitle(QtGui.QApplication.translate("Fishery", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Fishery", "Fishery Sector", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_sector_label.setText(QtGui.QApplication.translate("Fishery", "Dynamic Fishery Sector Name", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("Fishery", "Fisher Information", None, QtGui.QApplication.UnicodeUTF8))
        self.employee_text.setText(QtGui.QApplication.translate("Fishery", "Type of Employee:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Fishery", "Captain of Boat", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Fishery", "Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Fishery", "Boat owner", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Fishery", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text.setText(QtGui.QApplication.translate("Fishery", "Vessel length (meters):", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_line.setText(QtGui.QApplication.translate("Fishery", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_text.setText(QtGui.QApplication.translate("Fishery", "Vessel motor (hp):", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_line.setText(QtGui.QApplication.translate("Fishery", "120", None, QtGui.QApplication.UnicodeUTF8))
        self.haul_capacity_text.setText(QtGui.QApplication.translate("Fishery", "Haul Capacity (kg):", None, QtGui.QApplication.UnicodeUTF8))
        self.haul_capacity_line.setText(QtGui.QApplication.translate("Fishery", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text.setText(QtGui.QApplication.translate("Fishery", "Home Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_line.setText(QtGui.QApplication.translate("Fishery", "home port", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text.setText(QtGui.QApplication.translate("Fishery", "Landing Port 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_line.setText(QtGui.QApplication.translate("Fishery", "lp1", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_2.setText(QtGui.QApplication.translate("Fishery", "Landing Port 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_line_2.setText(QtGui.QApplication.translate("Fishery", "lp2", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_3.setText(QtGui.QApplication.translate("Fishery", "Landing Port 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_line_3.setText(QtGui.QApplication.translate("Fishery", "lp3", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_4.setText(QtGui.QApplication.translate("Fishery", "Landing Port 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_line_4.setText(QtGui.QApplication.translate("Fishery", "lp4", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Fishery", "Targeted Resource Groups:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Fishery", "What percent interest do you have in each resource group? (Must add up to 100)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Fishery", "Coastal Reef Fish:", None, QtGui.QApplication.UnicodeUTF8))
        self.target_coastal.setText(QtGui.QApplication.translate("Fishery", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Fishery", "Deep Reef Fish:", None, QtGui.QApplication.UnicodeUTF8))
        self.target_deep.setText(QtGui.QApplication.translate("Fishery", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Fishery", "Migratory Fish", None, QtGui.QApplication.UnicodeUTF8))
        self.target_migratory.setText(QtGui.QApplication.translate("Fishery", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Fishery", "Sea Cucumber", None, QtGui.QApplication.UnicodeUTF8))
        self.target_cucumber.setText(QtGui.QApplication.translate("Fishery", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Fishery", "Chocolate Clam", None, QtGui.QApplication.UnicodeUTF8))
        self.target_chocolate.setText(QtGui.QApplication.translate("Fishery", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Fishery", "Squid", None, QtGui.QApplication.UnicodeUTF8))
        self.target_squid.setText(QtGui.QApplication.translate("Fishery", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Fishery", "Sharks and Skates", None, QtGui.QApplication.UnicodeUTF8))
        self.target_sharks.setText(QtGui.QApplication.translate("Fishery", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Fishery", "Octopus", None, QtGui.QApplication.UnicodeUTF8))
        self.target_octopus.setText(QtGui.QApplication.translate("Fishery", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Fishery", "Bait", None, QtGui.QApplication.UnicodeUTF8))
        self.target_bait.setText(QtGui.QApplication.translate("Fishery", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Fishery", "Other Resource Group #1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Fishery", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Fishery", "% interest:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Fishery", "Other Resource Group #2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Fishery", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Fishery", "% interest:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Fishery", "Other Resource Group #3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Fishery", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Fishery", "% interest:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Fishery", "Other Resource Group #4:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Fishery", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Fishery", "% interest:", None, QtGui.QApplication.UnicodeUTF8))
        self.target_other_4_interest.setText(QtGui.QApplication.translate("Fishery", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnStartGroups.setText(QtGui.QApplication.translate("Fishery", "Next", None, QtGui.QApplication.UnicodeUTF8))

