# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectgear.ui'
#
# Created: Fri Mar 27 11:00:35 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SelectGear(object):
    def setupUi(self, SelectGear):
        SelectGear.setObjectName("SelectGear")
        SelectGear.resize(523, 403)
        self.verticalLayout_8 = QtGui.QVBoxLayout(SelectGear)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_3 = QtGui.QWidget(SelectGear)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.fishery_sector_label = QtGui.QLabel(self.widget_3)
        self.fishery_sector_label.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.fishery_sector_label.setFont(font)
        self.fishery_sector_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fishery_sector_label.setObjectName("fishery_sector_label")
        self.horizontalLayout_2.addWidget(self.fishery_sector_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.resource_group_label = QtGui.QLabel(self.widget_3)
        self.resource_group_label.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.resource_group_label.setFont(font)
        self.resource_group_label.setAlignment(QtCore.Qt.AlignCenter)
        self.resource_group_label.setObjectName("resource_group_label")
        self.horizontalLayout.addWidget(self.resource_group_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addWidget(self.widget_3)
        self.groupBox_2 = QtGui.QGroupBox(SelectGear)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.editMainSpecies = QtGui.QTextEdit(self.groupBox_2)
        self.editMainSpecies.setObjectName("editMainSpecies")
        self.horizontalLayout_9.addWidget(self.editMainSpecies)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(SelectGear)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gear_hook_line = QtGui.QCheckBox(self.groupBox)
        self.gear_hook_line.setObjectName("gear_hook_line")
        self.verticalLayout_4.addWidget(self.gear_hook_line)
        self.gear_gillnet = QtGui.QCheckBox(self.groupBox)
        self.gear_gillnet.setObjectName("gear_gillnet")
        self.verticalLayout_4.addWidget(self.gear_gillnet)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gear_traps = QtGui.QCheckBox(self.groupBox)
        self.gear_traps.setObjectName("gear_traps")
        self.verticalLayout_5.addWidget(self.gear_traps)
        self.gear_trawling = QtGui.QCheckBox(self.groupBox)
        self.gear_trawling.setObjectName("gear_trawling")
        self.verticalLayout_5.addWidget(self.gear_trawling)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gear_purse_seine = QtGui.QCheckBox(self.groupBox)
        self.gear_purse_seine.setObjectName("gear_purse_seine")
        self.verticalLayout_6.addWidget(self.gear_purse_seine)
        self.gear_hooka = QtGui.QCheckBox(self.groupBox)
        self.gear_hooka.setObjectName("gear_hooka")
        self.verticalLayout_6.addWidget(self.gear_hooka)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gear_other_1 = QtGui.QLineEdit(self.groupBox)
        self.gear_other_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gear_other_1.setObjectName("gear_other_1")
        self.horizontalLayout_3.addWidget(self.gear_other_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.gear_other_2 = QtGui.QLineEdit(self.groupBox)
        self.gear_other_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gear_other_2.setObjectName("gear_other_2")
        self.horizontalLayout_4.addWidget(self.gear_other_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.gear_other_3 = QtGui.QLineEdit(self.groupBox)
        self.gear_other_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gear_other_3.setObjectName("gear_other_3")
        self.horizontalLayout_6.addWidget(self.gear_other_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.gear_other_4 = QtGui.QLineEdit(self.groupBox)
        self.gear_other_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gear_other_4.setObjectName("gear_other_4")
        self.horizontalLayout_5.addWidget(self.gear_other_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.widget_2 = QtGui.QWidget(SelectGear)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget_2)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem4)
        self.pbnStepFinished = QtGui.QPushButton(self.widget_2)
        self.pbnStepFinished.setMinimumSize(QtCore.QSize(200, 0))
        self.pbnStepFinished.setObjectName("pbnStepFinished")
        self.hboxlayout.addWidget(self.pbnStepFinished)
        self.pbnStartShapes = QtGui.QPushButton(self.widget_2)
        self.pbnStartShapes.setMinimumSize(QtCore.QSize(200, 0))
        self.pbnStartShapes.setObjectName("pbnStartShapes")
        self.hboxlayout.addWidget(self.pbnStartShapes)
        self.verticalLayout_8.addWidget(self.widget_2)

        self.retranslateUi(SelectGear)
        QtCore.QMetaObject.connectSlotsByName(SelectGear)

    def retranslateUi(self, SelectGear):
        SelectGear.setWindowTitle(QtGui.QApplication.translate("SelectGear", "OpenOceanMap - Resource Group Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SelectGear", "Current Fishery Sector: ", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_sector_label.setText(QtGui.QApplication.translate("SelectGear", "Fishery Sector Here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SelectGear", "Current Resource Group:", None, QtGui.QApplication.UnicodeUTF8))
        self.resource_group_label.setText(QtGui.QApplication.translate("SelectGear", "Resource Group Here", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SelectGear", "Main Species Harvested (comma-separated):", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SelectGear", "Gear Types Used:", None, QtGui.QApplication.UnicodeUTF8))
        self.gear_hook_line.setText(QtGui.QApplication.translate("SelectGear", "Hook and Line", None, QtGui.QApplication.UnicodeUTF8))
        self.gear_gillnet.setText(QtGui.QApplication.translate("SelectGear", "Gillnet", None, QtGui.QApplication.UnicodeUTF8))
        self.gear_traps.setText(QtGui.QApplication.translate("SelectGear", "Traps", None, QtGui.QApplication.UnicodeUTF8))
        self.gear_trawling.setText(QtGui.QApplication.translate("SelectGear", "Trawling", None, QtGui.QApplication.UnicodeUTF8))
        self.gear_purse_seine.setText(QtGui.QApplication.translate("SelectGear", "Purse Seine", None, QtGui.QApplication.UnicodeUTF8))
        self.gear_hooka.setText(QtGui.QApplication.translate("SelectGear", "Hooka (compressor)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SelectGear", "Other Gear #1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SelectGear", "Other Gear #2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SelectGear", "Other Gear #3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SelectGear", "Other Gear #4:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnStartShapes.setText(QtGui.QApplication.translate("SelectGear", "Start Drawing Shapes", None, QtGui.QApplication.UnicodeUTF8))

