# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nextpolygon.ui'
#
# Created: Wed Mar 04 11:37:28 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NextPolygon(object):
    def setupUi(self, NextPolygon):
        NextPolygon.setObjectName("NextPolygon")
        NextPolygon.resize(493, 166)
        self.hboxlayout = QtGui.QHBoxLayout(NextPolygon)
        self.hboxlayout.setObjectName("hboxlayout")
        self.groupBox = QtGui.QGroupBox(NextPolygon)
        self.groupBox.setObjectName("groupBox")
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 104, 455, 51))
        self.widget.setObjectName("widget")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.pbnShapeFinished = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnShapeFinished.setFont(font)
        self.pbnShapeFinished.setObjectName("pbnShapeFinished")
        self.hboxlayout1.addWidget(self.pbnShapeFinished)
        self.pbnShapeDiscard = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnShapeDiscard.setFont(font)
        self.pbnShapeDiscard.setObjectName("pbnShapeDiscard")
        self.hboxlayout1.addWidget(self.pbnShapeDiscard)
        self.pbnMoreShapes = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnMoreShapes.setFont(font)
        self.pbnMoreShapes.setObjectName("pbnMoreShapes")
        self.hboxlayout1.addWidget(self.pbnMoreShapes)
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(12, 3, 261, 94))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_1 = QtGui.QLabel(self.widget1)
        self.label_1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.hboxlayout2.addWidget(self.label_1)
        self.line_1 = QtGui.QLineEdit(self.widget1)
        self.line_1.setEnabled(True)
        self.line_1.setMinimumSize(QtCore.QSize(100, 0))
        self.line_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_1.setFont(font)
        self.line_1.setObjectName("line_1")
        self.hboxlayout2.addWidget(self.line_1)
        self.pl_label = QtGui.QLabel(self.widget1)
        self.pl_label.setMinimumSize(QtCore.QSize(50, 0))
        self.pl_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pl_label.setObjectName("pl_label")
        self.hboxlayout2.addWidget(self.pl_label)
        self.verticalLayout.addLayout(self.hboxlayout2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.habitat_combo_label = QtGui.QLabel(self.widget1)
        self.habitat_combo_label.setMinimumSize(QtCore.QSize(100, 0))
        self.habitat_combo_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.habitat_combo_label.setFont(font)
        self.habitat_combo_label.setObjectName("habitat_combo_label")
        self.horizontalLayout.addWidget(self.habitat_combo_label)
        self.habitat_combo = QtGui.QComboBox(self.widget1)
        self.habitat_combo.setMinimumSize(QtCore.QSize(100, 0))
        self.habitat_combo.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.habitat_combo.setFont(font)
        self.habitat_combo.setObjectName("habitat_combo")
        self.habitat_combo.addItem(QtCore.QString())
        self.habitat_combo.addItem(QtCore.QString())
        self.habitat_combo.addItem(QtCore.QString())
        self.habitat_combo.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.habitat_combo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hboxlayout.addWidget(self.groupBox)

        self.retranslateUi(NextPolygon)
        QtCore.QMetaObject.connectSlotsByName(NextPolygon)

    def retranslateUi(self, NextPolygon):
        NextPolygon.setWindowTitle(QtGui.QApplication.translate("NextPolygon", "OpenOceanMap - Next Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnShapeFinished.setText(QtGui.QApplication.translate("NextPolygon", "Finished With Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnShapeDiscard.setText(QtGui.QApplication.translate("NextPolygon", "Discard Last Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnMoreShapes.setText(QtGui.QApplication.translate("NextPolygon", "More Shapes This Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("NextPolygon", "Pennies:", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo_label.setText(QtGui.QApplication.translate("NextPolygon", "Habitat Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.setItemText(0, QtGui.QApplication.translate("NextPolygon", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.setItemText(1, QtGui.QApplication.translate("NextPolygon", "Hard Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.setItemText(2, QtGui.QApplication.translate("NextPolygon", "Soft Sandy", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.setItemText(3, QtGui.QApplication.translate("NextPolygon", "Mixed", None, QtGui.QApplication.UnicodeUTF8))

