# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rec_cpfv.ui'
#
# Created: Sat Nov 07 12:59:34 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RecCpfv(object):
    def setupUi(self, RecCpfv):
        RecCpfv.setObjectName("RecCpfv")
        RecCpfv.setWindowModality(QtCore.Qt.WindowModal)
        RecCpfv.resize(696, 623)
        self.vboxlayout = QtGui.QVBoxLayout(RecCpfv)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.vessel_info_2 = QtGui.QGroupBox(RecCpfv)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vessel_info_2.setFont(font)
        self.vessel_info_2.setObjectName("vessel_info_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ves_license_4 = QtGui.QWidget(self.vessel_info_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license_4.setFont(font)
        self.ves_license_4.setObjectName("ves_license_4")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.ves_license_4)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(4)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.federal_vessel_id_text_3 = QtGui.QLabel(self.ves_license_4)
        self.federal_vessel_id_text_3.setMinimumSize(QtCore.QSize(150, 0))
        self.federal_vessel_id_text_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.federal_vessel_id_text_3.setFont(font)
        self.federal_vessel_id_text_3.setWordWrap(True)
        self.federal_vessel_id_text_3.setObjectName("federal_vessel_id_text_3")
        self.hboxlayout1.addWidget(self.federal_vessel_id_text_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.cpfv_num_own_line = QtGui.QLineEdit(self.ves_license_4)
        self.cpfv_num_own_line.setEnabled(True)
        self.cpfv_num_own_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_num_own_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_num_own_line.setFont(font)
        self.cpfv_num_own_line.setObjectName("cpfv_num_own_line")
        self.hboxlayout1.addWidget(self.cpfv_num_own_line)
        self.verticalLayout.addWidget(self.ves_license_4)
        self.ves_license_5 = QtGui.QWidget(self.vessel_info_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license_5.setFont(font)
        self.ves_license_5.setObjectName("ves_license_5")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.ves_license_5)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.federal_vessel_id_text_4 = QtGui.QLabel(self.ves_license_5)
        self.federal_vessel_id_text_4.setMinimumSize(QtCore.QSize(200, 0))
        self.federal_vessel_id_text_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.federal_vessel_id_text_4.setFont(font)
        self.federal_vessel_id_text_4.setWordWrap(True)
        self.federal_vessel_id_text_4.setObjectName("federal_vessel_id_text_4")
        self.hboxlayout2.addWidget(self.federal_vessel_id_text_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem1)
        self.cpfv_yr_own_line = QtGui.QLineEdit(self.ves_license_5)
        self.cpfv_yr_own_line.setEnabled(True)
        self.cpfv_yr_own_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_yr_own_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_yr_own_line.setFont(font)
        self.cpfv_yr_own_line.setObjectName("cpfv_yr_own_line")
        self.hboxlayout2.addWidget(self.cpfv_yr_own_line)
        self.verticalLayout.addWidget(self.ves_license_5)
        self.widget_2 = QtGui.QWidget(self.vessel_info_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setMargin(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cpfv_revenue_line = QtGui.QLineEdit(self.widget_2)
        self.cpfv_revenue_line.setObjectName("cpfv_revenue_line")
        self.horizontalLayout_2.addWidget(self.cpfv_revenue_line)
        self.verticalLayout.addWidget(self.widget_2)
        self.home_port_24 = QtGui.QWidget(self.vessel_info_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_24.setFont(font)
        self.home_port_24.setObjectName("home_port_24")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.home_port_24)
        self.hboxlayout3.setSpacing(4)
        self.hboxlayout3.setMargin(4)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.landing_port_text_10 = QtGui.QLabel(self.home_port_24)
        self.landing_port_text_10.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_text_10.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_10.setFont(font)
        self.landing_port_text_10.setWordWrap(True)
        self.landing_port_text_10.setObjectName("landing_port_text_10")
        self.hboxlayout3.addWidget(self.landing_port_text_10)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem3)
        self.cpfv_labor_cost_line = QtGui.QLineEdit(self.home_port_24)
        self.cpfv_labor_cost_line.setEnabled(True)
        self.cpfv_labor_cost_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_labor_cost_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_labor_cost_line.setFont(font)
        self.cpfv_labor_cost_line.setObjectName("cpfv_labor_cost_line")
        self.hboxlayout3.addWidget(self.cpfv_labor_cost_line)
        self.verticalLayout.addWidget(self.home_port_24)
        self.home_port_25 = QtGui.QWidget(self.vessel_info_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_25.setFont(font)
        self.home_port_25.setObjectName("home_port_25")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.home_port_25)
        self.hboxlayout4.setSpacing(4)
        self.hboxlayout4.setMargin(4)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.landing_port_text_11 = QtGui.QLabel(self.home_port_25)
        self.landing_port_text_11.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_text_11.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_11.setFont(font)
        self.landing_port_text_11.setWordWrap(True)
        self.landing_port_text_11.setObjectName("landing_port_text_11")
        self.hboxlayout4.addWidget(self.landing_port_text_11)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem4)
        self.cpfv_fuel_cost_line = QtGui.QLineEdit(self.home_port_25)
        self.cpfv_fuel_cost_line.setEnabled(True)
        self.cpfv_fuel_cost_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_fuel_cost_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_fuel_cost_line.setFont(font)
        self.cpfv_fuel_cost_line.setObjectName("cpfv_fuel_cost_line")
        self.hboxlayout4.addWidget(self.cpfv_fuel_cost_line)
        self.verticalLayout.addWidget(self.home_port_25)
        self.home_port_23 = QtGui.QWidget(self.vessel_info_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_23.setFont(font)
        self.home_port_23.setObjectName("home_port_23")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.home_port_23)
        self.hboxlayout5.setSpacing(4)
        self.hboxlayout5.setMargin(4)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.landing_port_text_9 = QtGui.QLabel(self.home_port_23)
        self.landing_port_text_9.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_text_9.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_9.setFont(font)
        self.landing_port_text_9.setWordWrap(True)
        self.landing_port_text_9.setObjectName("landing_port_text_9")
        self.hboxlayout5.addWidget(self.landing_port_text_9)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem5)
        self.cpfv_operating_cost_line = QtGui.QLineEdit(self.home_port_23)
        self.cpfv_operating_cost_line.setEnabled(True)
        self.cpfv_operating_cost_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_operating_cost_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_operating_cost_line.setFont(font)
        self.cpfv_operating_cost_line.setObjectName("cpfv_operating_cost_line")
        self.hboxlayout5.addWidget(self.cpfv_operating_cost_line)
        self.verticalLayout.addWidget(self.home_port_23)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.vboxlayout1.addWidget(self.vessel_info_2)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.vessel_info = QtGui.QGroupBox(RecCpfv)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_3 = QtGui.QWidget(self.vessel_info)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setMargin(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.cpfv_percent_income_line = QtGui.QLineEdit(self.widget_3)
        self.cpfv_percent_income_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_percent_income_line.setFont(font)
        self.cpfv_percent_income_line.setObjectName("cpfv_percent_income_line")
        self.horizontalLayout_3.addWidget(self.cpfv_percent_income_line)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.home_port_13 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_13.setFont(font)
        self.home_port_13.setObjectName("home_port_13")
        self.hboxlayout6 = QtGui.QHBoxLayout(self.home_port_13)
        self.hboxlayout6.setSpacing(4)
        self.hboxlayout6.setMargin(4)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.type_of_charter_text_5 = QtGui.QLabel(self.home_port_13)
        self.type_of_charter_text_5.setMinimumSize(QtCore.QSize(150, 0))
        self.type_of_charter_text_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.type_of_charter_text_5.setFont(font)
        self.type_of_charter_text_5.setWordWrap(True)
        self.type_of_charter_text_5.setObjectName("type_of_charter_text_5")
        self.hboxlayout6.addWidget(self.type_of_charter_text_5)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem8)
        self.cpfv_type_combo = QtGui.QComboBox(self.home_port_13)
        self.cpfv_type_combo.setObjectName("cpfv_type_combo")
        self.cpfv_type_combo.addItem(QtCore.QString())
        self.cpfv_type_combo.setItemText(0, "")
        self.cpfv_type_combo.addItem(QtCore.QString())
        self.cpfv_type_combo.addItem(QtCore.QString())
        self.cpfv_type_combo.addItem(QtCore.QString())
        self.hboxlayout6.addWidget(self.cpfv_type_combo)
        self.verticalLayout_7.addWidget(self.home_port_13)
        self.ves_license_6 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license_6.setFont(font)
        self.ves_license_6.setObjectName("ves_license_6")
        self._2 = QtGui.QHBoxLayout(self.ves_license_6)
        self._2.setSpacing(4)
        self._2.setMargin(4)
        self._2.setObjectName("_2")
        self.federal_vessel_id_text_5 = QtGui.QLabel(self.ves_license_6)
        self.federal_vessel_id_text_5.setMinimumSize(QtCore.QSize(150, 0))
        self.federal_vessel_id_text_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.federal_vessel_id_text_5.setFont(font)
        self.federal_vessel_id_text_5.setWordWrap(True)
        self.federal_vessel_id_text_5.setObjectName("federal_vessel_id_text_5")
        self._2.addWidget(self.federal_vessel_id_text_5)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem9)
        self.cpfv_lic_line = QtGui.QLineEdit(self.ves_license_6)
        self.cpfv_lic_line.setEnabled(True)
        self.cpfv_lic_line.setMinimumSize(QtCore.QSize(100, 0))
        self.cpfv_lic_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_lic_line.setFont(font)
        self.cpfv_lic_line.setObjectName("cpfv_lic_line")
        self._2.addWidget(self.cpfv_lic_line)
        self.verticalLayout_7.addWidget(self.ves_license_6)
        self.vessel_length_5 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_5.setFont(font)
        self.vessel_length_5.setObjectName("vessel_length_5")
        self.hboxlayout7 = QtGui.QHBoxLayout(self.vessel_length_5)
        self.hboxlayout7.setSpacing(4)
        self.hboxlayout7.setMargin(4)
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.vessel_length_text_3 = QtGui.QLabel(self.vessel_length_5)
        self.vessel_length_text_3.setMinimumSize(QtCore.QSize(100, 0))
        self.vessel_length_text_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_text_3.setFont(font)
        self.vessel_length_text_3.setWordWrap(True)
        self.vessel_length_text_3.setObjectName("vessel_length_text_3")
        self.hboxlayout7.addWidget(self.vessel_length_text_3)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem10)
        self.cpfv_name_line = QtGui.QLineEdit(self.vessel_length_5)
        self.cpfv_name_line.setEnabled(True)
        self.cpfv_name_line.setMinimumSize(QtCore.QSize(200, 0))
        self.cpfv_name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_name_line.setFont(font)
        self.cpfv_name_line.setObjectName("cpfv_name_line")
        self.hboxlayout7.addWidget(self.cpfv_name_line)
        self.verticalLayout_7.addWidget(self.vessel_length_5)
        self.vessel_length_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_4.setFont(font)
        self.vessel_length_4.setObjectName("vessel_length_4")
        self.hboxlayout8 = QtGui.QHBoxLayout(self.vessel_length_4)
        self.hboxlayout8.setSpacing(4)
        self.hboxlayout8.setMargin(4)
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.vessel_length_text_2 = QtGui.QLabel(self.vessel_length_4)
        self.vessel_length_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_length_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_text_2.setFont(font)
        self.vessel_length_text_2.setWordWrap(True)
        self.vessel_length_text_2.setObjectName("vessel_length_text_2")
        self.hboxlayout8.addWidget(self.vessel_length_text_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem11)
        self.cpfv_len_line = QtGui.QLineEdit(self.vessel_length_4)
        self.cpfv_len_line.setEnabled(True)
        self.cpfv_len_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_len_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_len_line.setFont(font)
        self.cpfv_len_line.setObjectName("cpfv_len_line")
        self.hboxlayout8.addWidget(self.cpfv_len_line)
        self.verticalLayout_7.addWidget(self.vessel_length_4)
        self.home_port_12 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_12.setFont(font)
        self.home_port_12.setObjectName("home_port_12")
        self.hboxlayout9 = QtGui.QHBoxLayout(self.home_port_12)
        self.hboxlayout9.setSpacing(4)
        self.hboxlayout9.setMargin(4)
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.home_port_text_2 = QtGui.QLabel(self.home_port_12)
        self.home_port_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.home_port_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_text_2.setFont(font)
        self.home_port_text_2.setWordWrap(True)
        self.home_port_text_2.setObjectName("home_port_text_2")
        self.hboxlayout9.addWidget(self.home_port_text_2)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout9.addItem(spacerItem12)
        self.cpfv_home_port_line = QtGui.QLineEdit(self.home_port_12)
        self.cpfv_home_port_line.setEnabled(True)
        self.cpfv_home_port_line.setMinimumSize(QtCore.QSize(150, 0))
        self.cpfv_home_port_line.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_home_port_line.setFont(font)
        self.cpfv_home_port_line.setObjectName("cpfv_home_port_line")
        self.hboxlayout9.addWidget(self.cpfv_home_port_line)
        self.verticalLayout_7.addWidget(self.home_port_12)
        self.widget = QtGui.QWidget(self.vessel_info)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setMargin(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem13 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.cpfv_num_op_line = QtGui.QLineEdit(self.widget)
        self.cpfv_num_op_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_num_op_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_num_op_line.setFont(font)
        self.cpfv_num_op_line.setObjectName("cpfv_num_op_line")
        self.horizontalLayout.addWidget(self.cpfv_num_op_line)
        self.verticalLayout_7.addWidget(self.widget)
        self.home_port_11 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_11.setFont(font)
        self.home_port_11.setObjectName("home_port_11")
        self.hboxlayout10 = QtGui.QHBoxLayout(self.home_port_11)
        self.hboxlayout10.setSpacing(4)
        self.hboxlayout10.setMargin(4)
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.years_text_4 = QtGui.QLabel(self.home_port_11)
        self.years_text_4.setMinimumSize(QtCore.QSize(250, 0))
        self.years_text_4.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_text_4.setFont(font)
        self.years_text_4.setWordWrap(True)
        self.years_text_4.setObjectName("years_text_4")
        self.hboxlayout10.addWidget(self.years_text_4)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout10.addItem(spacerItem14)
        self.cpfv_yr_op_line = QtGui.QLineEdit(self.home_port_11)
        self.cpfv_yr_op_line.setEnabled(True)
        self.cpfv_yr_op_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_yr_op_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_yr_op_line.setFont(font)
        self.cpfv_yr_op_line.setObjectName("cpfv_yr_op_line")
        self.hboxlayout10.addWidget(self.cpfv_yr_op_line)
        self.verticalLayout_7.addWidget(self.home_port_11)
        self.home_port_14 = QtGui.QWidget(self.vessel_info)
        self.home_port_14.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_14.setFont(font)
        self.home_port_14.setObjectName("home_port_14")
        self.hboxlayout11 = QtGui.QHBoxLayout(self.home_port_14)
        self.hboxlayout11.setSpacing(4)
        self.hboxlayout11.setMargin(4)
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.landing_port_text_6 = QtGui.QLabel(self.home_port_14)
        self.landing_port_text_6.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_text_6.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_6.setFont(font)
        self.landing_port_text_6.setWordWrap(True)
        self.landing_port_text_6.setObjectName("landing_port_text_6")
        self.hboxlayout11.addWidget(self.landing_port_text_6)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout11.addItem(spacerItem15)
        self.cpfv_num_days_line = QtGui.QLineEdit(self.home_port_14)
        self.cpfv_num_days_line.setEnabled(True)
        self.cpfv_num_days_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_num_days_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_num_days_line.setFont(font)
        self.cpfv_num_days_line.setObjectName("cpfv_num_days_line")
        self.hboxlayout11.addWidget(self.cpfv_num_days_line)
        self.verticalLayout_7.addWidget(self.home_port_14)
        self.home_port_15 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_15.setFont(font)
        self.home_port_15.setObjectName("home_port_15")
        self.hboxlayout12 = QtGui.QHBoxLayout(self.home_port_15)
        self.hboxlayout12.setSpacing(4)
        self.hboxlayout12.setMargin(4)
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.landing_port_text_7 = QtGui.QLabel(self.home_port_15)
        self.landing_port_text_7.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_text_7.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_7.setFont(font)
        self.landing_port_text_7.setWordWrap(True)
        self.landing_port_text_7.setObjectName("landing_port_text_7")
        self.hboxlayout12.addWidget(self.landing_port_text_7)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout12.addItem(spacerItem16)
        self.cpfv_num_pass_line = QtGui.QLineEdit(self.home_port_15)
        self.cpfv_num_pass_line.setEnabled(True)
        self.cpfv_num_pass_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_num_pass_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_num_pass_line.setFont(font)
        self.cpfv_num_pass_line.setObjectName("cpfv_num_pass_line")
        self.hboxlayout12.addWidget(self.cpfv_num_pass_line)
        self.verticalLayout_7.addWidget(self.home_port_15)
        self.home_port_18 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_18.setFont(font)
        self.home_port_18.setObjectName("home_port_18")
        self.hboxlayout13 = QtGui.QHBoxLayout(self.home_port_18)
        self.hboxlayout13.setSpacing(4)
        self.hboxlayout13.setMargin(4)
        self.hboxlayout13.setObjectName("hboxlayout13")
        self.landing_port_text_12 = QtGui.QLabel(self.home_port_18)
        self.landing_port_text_12.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_text_12.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_12.setFont(font)
        self.landing_port_text_12.setWordWrap(True)
        self.landing_port_text_12.setObjectName("landing_port_text_12")
        self.hboxlayout13.addWidget(self.landing_port_text_12)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout13.addItem(spacerItem17)
        self.cpfv_num_out_state_line = QtGui.QLineEdit(self.home_port_18)
        self.cpfv_num_out_state_line.setEnabled(True)
        self.cpfv_num_out_state_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_num_out_state_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_num_out_state_line.setFont(font)
        self.cpfv_num_out_state_line.setObjectName("cpfv_num_out_state_line")
        self.hboxlayout13.addWidget(self.cpfv_num_out_state_line)
        self.verticalLayout_7.addWidget(self.home_port_18)
        self.home_port_16 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_16.setFont(font)
        self.home_port_16.setObjectName("home_port_16")
        self.hboxlayout14 = QtGui.QHBoxLayout(self.home_port_16)
        self.hboxlayout14.setSpacing(4)
        self.hboxlayout14.setMargin(4)
        self.hboxlayout14.setObjectName("hboxlayout14")
        self.landing_port_text_8 = QtGui.QLabel(self.home_port_16)
        self.landing_port_text_8.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_text_8.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_8.setFont(font)
        self.landing_port_text_8.setWordWrap(True)
        self.landing_port_text_8.setObjectName("landing_port_text_8")
        self.hboxlayout14.addWidget(self.landing_port_text_8)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout14.addItem(spacerItem18)
        self.cpfv_num_crew_line = QtGui.QLineEdit(self.home_port_16)
        self.cpfv_num_crew_line.setEnabled(True)
        self.cpfv_num_crew_line.setMinimumSize(QtCore.QSize(50, 0))
        self.cpfv_num_crew_line.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cpfv_num_crew_line.setFont(font)
        self.cpfv_num_crew_line.setObjectName("cpfv_num_crew_line")
        self.hboxlayout14.addWidget(self.cpfv_num_crew_line)
        self.verticalLayout_7.addWidget(self.home_port_16)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        self.hboxlayout.addWidget(self.vessel_info)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.hboxlayout.addLayout(self.vboxlayout2)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.button_box = QtGui.QWidget(RecCpfv)
        self.button_box.setObjectName("button_box")
        self.hboxlayout15 = QtGui.QHBoxLayout(self.button_box)
        self.hboxlayout15.setSpacing(2)
        self.hboxlayout15.setMargin(2)
        self.hboxlayout15.setObjectName("hboxlayout15")
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout15.addItem(spacerItem20)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self.hboxlayout15.addWidget(self.pbnCancel)
        self.pbnFinished = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFinished.setFont(font)
        self.pbnFinished.setObjectName("pbnFinished")
        self.hboxlayout15.addWidget(self.pbnFinished)
        self.vboxlayout.addWidget(self.button_box)

        self.retranslateUi(RecCpfv)
        QtCore.QMetaObject.connectSlotsByName(RecCpfv)
        RecCpfv.setTabOrder(self.cpfv_num_own_line, self.cpfv_yr_own_line)
        RecCpfv.setTabOrder(self.cpfv_yr_own_line, self.cpfv_revenue_line)
        RecCpfv.setTabOrder(self.cpfv_revenue_line, self.cpfv_labor_cost_line)
        RecCpfv.setTabOrder(self.cpfv_labor_cost_line, self.cpfv_fuel_cost_line)
        RecCpfv.setTabOrder(self.cpfv_fuel_cost_line, self.cpfv_operating_cost_line)
        RecCpfv.setTabOrder(self.cpfv_operating_cost_line, self.cpfv_percent_income_line)
        RecCpfv.setTabOrder(self.cpfv_percent_income_line, self.cpfv_type_combo)
        RecCpfv.setTabOrder(self.cpfv_type_combo, self.cpfv_lic_line)
        RecCpfv.setTabOrder(self.cpfv_lic_line, self.cpfv_name_line)
        RecCpfv.setTabOrder(self.cpfv_name_line, self.cpfv_len_line)
        RecCpfv.setTabOrder(self.cpfv_len_line, self.cpfv_home_port_line)
        RecCpfv.setTabOrder(self.cpfv_home_port_line, self.cpfv_num_op_line)
        RecCpfv.setTabOrder(self.cpfv_num_op_line, self.cpfv_yr_op_line)
        RecCpfv.setTabOrder(self.cpfv_yr_op_line, self.cpfv_num_days_line)
        RecCpfv.setTabOrder(self.cpfv_num_days_line, self.cpfv_num_pass_line)
        RecCpfv.setTabOrder(self.cpfv_num_pass_line, self.cpfv_num_out_state_line)
        RecCpfv.setTabOrder(self.cpfv_num_out_state_line, self.cpfv_num_crew_line)
        RecCpfv.setTabOrder(self.cpfv_num_crew_line, self.pbnFinished)
        RecCpfv.setTabOrder(self.pbnFinished, self.pbnCancel)

    def retranslateUi(self, RecCpfv):
        RecCpfv.setWindowTitle(QtGui.QApplication.translate("RecCpfv", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info_2.setTitle(QtGui.QApplication.translate("RecCpfv", "If a Charter Boat Owner:", None, QtGui.QApplication.UnicodeUTF8))
        self.federal_vessel_id_text_3.setText(QtGui.QApplication.translate("RecCpfv", "How many charter boats do you own?", None, QtGui.QApplication.UnicodeUTF8))
        self.federal_vessel_id_text_4.setText(QtGui.QApplication.translate("RecCpfv", "Years owning charter boats?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RecCpfv", "What is your annual gross revenue?", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_10.setText(QtGui.QApplication.translate("RecCpfv", "What percentage of GER goes to crew/labor costs?", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_11.setText(QtGui.QApplication.translate("RecCpfv", "What percentage of GER goes to fuel costs?", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_9.setText(QtGui.QApplication.translate("RecCpfv", "What percentage of GER goes to all other operating costs?", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("RecCpfv", "Charter Boat Owner or Operator:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RecCpfv", "% income from charter boat operating:", None, QtGui.QApplication.UnicodeUTF8))
        self.type_of_charter_text_5.setText(QtGui.QApplication.translate("RecCpfv", "Type of trip:", None, QtGui.QApplication.UnicodeUTF8))
        self.cpfv_type_combo.setItemText(1, QtGui.QApplication.translate("RecCpfv", "Charter", None, QtGui.QApplication.UnicodeUTF8))
        self.cpfv_type_combo.setItemText(2, QtGui.QApplication.translate("RecCpfv", "Six-pack", None, QtGui.QApplication.UnicodeUTF8))
        self.cpfv_type_combo.setItemText(3, QtGui.QApplication.translate("RecCpfv", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.federal_vessel_id_text_5.setText(QtGui.QApplication.translate("RecCpfv", "Vessel Document Number", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text_3.setText(QtGui.QApplication.translate("RecCpfv", "Vessel Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text_2.setText(QtGui.QApplication.translate("RecCpfv", "Vessel Length :", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text_2.setText(QtGui.QApplication.translate("RecCpfv", "Homeport of boat:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RecCpfv", "# charter boats operated:", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text_4.setText(QtGui.QApplication.translate("RecCpfv", "Years operating charter boats:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_6.setText(QtGui.QApplication.translate("RecCpfv", "Average # of days charter boat fishing per year:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_7.setText(QtGui.QApplication.translate("RecCpfv", "Average number of passengers on boat per trip:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_12.setText(QtGui.QApplication.translate("RecCpfv", "Percentage of passengers from out of state:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_8.setText(QtGui.QApplication.translate("RecCpfv", "Number of crew, not counting owner/operator:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("RecCpfv", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFinished.setText(QtGui.QApplication.translate("RecCpfv", "Continue", None, QtGui.QApplication.UnicodeUTF8))

