# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectfishery.ui'
#
# Created: Wed Mar 04 13:28:25 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SelectFishery(object):
    def setupUi(self, SelectFishery):
        SelectFishery.setObjectName("SelectFishery")
        SelectFishery.resize(460, 168)
        self.verticalLayout_5 = QtGui.QVBoxLayout(SelectFishery)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtGui.QWidget(SelectFishery)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setContentsMargins(9, 9, 9, 0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.fishery_text = QtGui.QLabel(self.widget)
        self.fishery_text.setMinimumSize(QtCore.QSize(160, 0))
        self.fishery_text.setMaximumSize(QtCore.QSize(160, 16777215))
        self.fishery_text.setObjectName("fishery_text")
        self.hboxlayout.addWidget(self.fishery_text)
        self.fishery_comboBox = QtGui.QComboBox(self.widget)
        self.fishery_comboBox.setObjectName("fishery_comboBox")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.setItemText(0, "")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.hboxlayout.addWidget(self.fishery_comboBox)
        self.horizontalLayout_3.addWidget(self.widget)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtGui.QWidget(SelectFishery)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(160, 0))
        self.label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.fish_perc_income = QtGui.QLineEdit(self.widget_3)
        self.fish_perc_income.setMinimumSize(QtCore.QSize(40, 0))
        self.fish_perc_income.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fish_perc_income.setObjectName("fish_perc_income")
        self.horizontalLayout_4.addWidget(self.fish_perc_income)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtGui.QWidget(SelectFishery)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget_2)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(9)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem2)
        self.pbnFisheryFinished = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFisheryFinished.setFont(font)
        self.pbnFisheryFinished.setObjectName("pbnFisheryFinished")
        self.hboxlayout1.addWidget(self.pbnFisheryFinished)
        self.pbnStartShapes = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnStartShapes.setFont(font)
        self.pbnStartShapes.setObjectName("pbnStartShapes")
        self.hboxlayout1.addWidget(self.pbnStartShapes)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SelectFishery)
        QtCore.QMetaObject.connectSlotsByName(SelectFishery)

    def retranslateUi(self, SelectFishery):
        SelectFishery.setWindowTitle(QtGui.QApplication.translate("SelectFishery", "OpenOceanMap - Select Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_text.setText(QtGui.QApplication.translate("SelectFishery", "Select Fishery :", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(1, QtGui.QApplication.translate("SelectFishery", "California Halibut (Hook & Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(2, QtGui.QApplication.translate("SelectFishery", "California Halibut (Set Gill Net)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(3, QtGui.QApplication.translate("SelectFishery", "Coastal Pelagics (Seine)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(4, QtGui.QApplication.translate("SelectFishery", "Deep Nearshore Rockfish (Hook & Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(5, QtGui.QApplication.translate("SelectFishery", "Lobster (Trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(6, QtGui.QApplication.translate("SelectFishery", "Nearshore Rockfish (Hook & Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(7, QtGui.QApplication.translate("SelectFishery", "Nearshore Rockfish (Trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(8, QtGui.QApplication.translate("SelectFishery", "Pacific Bonito (Seine)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(9, QtGui.QApplication.translate("SelectFishery", "Rock Crab (Trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(10, QtGui.QApplication.translate("SelectFishery", "Sablefish (Hook & Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(11, QtGui.QApplication.translate("SelectFishery", "Sablefish (Trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(12, QtGui.QApplication.translate("SelectFishery", "Sea Cucumber (Diving)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(13, QtGui.QApplication.translate("SelectFishery", "Shark (Drift Gill Net)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(14, QtGui.QApplication.translate("SelectFishery", "Shark (Set Gill Net)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(15, QtGui.QApplication.translate("SelectFishery", "Spot Prawn (Trap)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(16, QtGui.QApplication.translate("SelectFishery", "Squid (Seine)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(17, QtGui.QApplication.translate("SelectFishery", "Swordfish (Drift Gill Net)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(18, QtGui.QApplication.translate("SelectFishery", "Swordfish (Harpoon or Spear)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(19, QtGui.QApplication.translate("SelectFishery", "Swordfish (Hook & Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(20, QtGui.QApplication.translate("SelectFishery", "Thornyhead (Hook & Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(21, QtGui.QApplication.translate("SelectFishery", "Tuna (Hook & Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(22, QtGui.QApplication.translate("SelectFishery", "Tuna (Seine)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(23, QtGui.QApplication.translate("SelectFishery", "Urchin (Diving)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(24, QtGui.QApplication.translate("SelectFishery", "White Seabass (Hook-Line)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(25, QtGui.QApplication.translate("SelectFishery", "White Seabass (Gillnet)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(26, QtGui.QApplication.translate("SelectFishery", "Other (Note the species)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SelectFishery", "Percent income from this fishery:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFisheryFinished.setText(QtGui.QApplication.translate("SelectFishery", "Finished With Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnStartShapes.setText(QtGui.QApplication.translate("SelectFishery", "Start Drawing Shapes", None, QtGui.QApplication.UnicodeUTF8))

