# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interviewstart.ui'
#
# Created: Sat Nov 07 09:59:46 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_InterviewStart(object):
    def setupUi(self, InterviewStart):
        InterviewStart.setObjectName("InterviewStart")
        InterviewStart.resize(778, 501)
        self.verticalLayout_3 = QtGui.QVBoxLayout(InterviewStart)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.interviewee = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.interviewee.setFont(font)
        self.interviewee.setObjectName("interviewee")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.interviewee)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.interviewee_first_name = QtGui.QWidget(self.interviewee)
        self.interviewee_first_name.setObjectName("interviewee_first_name")
        self.hboxlayout = QtGui.QHBoxLayout(self.interviewee_first_name)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(4)
        self.hboxlayout.setObjectName("hboxlayout")
        self.interviewee_first_name_text = QtGui.QLabel(self.interviewee_first_name)
        self.interviewee_first_name_text.setMinimumSize(QtCore.QSize(100, 0))
        self.interviewee_first_name_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.interviewee_first_name_text.setObjectName("interviewee_first_name_text")
        self.hboxlayout.addWidget(self.interviewee_first_name_text)
        self.interviewee_first_name_line = QtGui.QLineEdit(self.interviewee_first_name)
        self.interviewee_first_name_line.setEnabled(True)
        self.interviewee_first_name_line.setMinimumSize(QtCore.QSize(200, 0))
        self.interviewee_first_name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.interviewee_first_name_line.setObjectName("interviewee_first_name_line")
        self.hboxlayout.addWidget(self.interviewee_first_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name)
        self.interviewee_last_name = QtGui.QWidget(self.interviewee)
        self.interviewee_last_name.setObjectName("interviewee_last_name")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.interviewee_last_name)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(4)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.interviewee_last_name_text = QtGui.QLabel(self.interviewee_last_name)
        self.interviewee_last_name_text.setMinimumSize(QtCore.QSize(100, 0))
        self.interviewee_last_name_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.interviewee_last_name_text.setObjectName("interviewee_last_name_text")
        self.hboxlayout1.addWidget(self.interviewee_last_name_text)
        self.interviewee_last_name_line = QtGui.QLineEdit(self.interviewee_last_name)
        self.interviewee_last_name_line.setEnabled(True)
        self.interviewee_last_name_line.setMinimumSize(QtCore.QSize(200, 0))
        self.interviewee_last_name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.interviewee_last_name_line.setObjectName("interviewee_last_name_line")
        self.hboxlayout1.addWidget(self.interviewee_last_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_last_name)
        self.age = QtGui.QWidget(self.interviewee)
        self.age.setObjectName("age")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.age)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.age_text = QtGui.QLabel(self.age)
        self.age_text.setMinimumSize(QtCore.QSize(100, 0))
        self.age_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.age_text.setObjectName("age_text")
        self.hboxlayout2.addWidget(self.age_text)
        self.age_line = QtGui.QLineEdit(self.age)
        self.age_line.setEnabled(True)
        self.age_line.setMinimumSize(QtCore.QSize(200, 0))
        self.age_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.age_line.setObjectName("age_line")
        self.hboxlayout2.addWidget(self.age_line)
        self.verticalLayout_2.addWidget(self.age)
        self.gender = QtGui.QWidget(self.interviewee)
        self.gender.setObjectName("gender")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.gender)
        self.hboxlayout3.setSpacing(4)
        self.hboxlayout3.setMargin(4)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.gender_text = QtGui.QLabel(self.gender)
        self.gender_text.setMinimumSize(QtCore.QSize(100, 0))
        self.gender_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gender_text.setObjectName("gender_text")
        self.hboxlayout3.addWidget(self.gender_text)
        self.gender_comboBox = QtGui.QComboBox(self.gender)
        self.gender_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.gender_comboBox.addItem(QtCore.QString())
        self.gender_comboBox.setItemText(0, "")
        self.gender_comboBox.addItem(QtCore.QString())
        self.gender_comboBox.addItem(QtCore.QString())
        self.hboxlayout3.addWidget(self.gender_comboBox)
        self.verticalLayout_2.addWidget(self.gender)
        self.age_2 = QtGui.QWidget(self.interviewee)
        self.age_2.setObjectName("age_2")
        self._2 = QtGui.QHBoxLayout(self.age_2)
        self._2.setSpacing(4)
        self._2.setMargin(4)
        self._2.setObjectName("_2")
        self.city_text = QtGui.QLabel(self.age_2)
        self.city_text.setMinimumSize(QtCore.QSize(100, 0))
        self.city_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.city_text.setObjectName("city_text")
        self._2.addWidget(self.city_text)
        self.city_line = QtGui.QLineEdit(self.age_2)
        self.city_line.setEnabled(True)
        self.city_line.setMinimumSize(QtCore.QSize(200, 0))
        self.city_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.city_line.setObjectName("city_line")
        self._2.addWidget(self.city_line)
        self.verticalLayout_2.addWidget(self.age_2)
        self.verticalLayout_4.addWidget(self.interviewee)
        self.interviewee_2 = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.interviewee_2.setFont(font)
        self.interviewee_2.setObjectName("interviewee_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.interviewee_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.interviewee_first_name_2 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_2.setObjectName("interviewee_first_name_2")
        self._3 = QtGui.QHBoxLayout(self.interviewee_first_name_2)
        self._3.setSpacing(4)
        self._3.setMargin(4)
        self._3.setObjectName("_3")
        self.date_text = QtGui.QLabel(self.interviewee_first_name_2)
        self.date_text.setMinimumSize(QtCore.QSize(180, 0))
        self.date_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.date_text.setObjectName("date_text")
        self._3.addWidget(self.date_text)
        self.date_line = QtGui.QLineEdit(self.interviewee_first_name_2)
        self.date_line.setEnabled(True)
        self.date_line.setMinimumSize(QtCore.QSize(150, 0))
        self.date_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.date_line.setObjectName("date_line")
        self._3.addWidget(self.date_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_2)
        self.interviewee_first_name_3 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_3.setObjectName("interviewee_first_name_3")
        self._8 = QtGui.QHBoxLayout(self.interviewee_first_name_3)
        self._8.setSpacing(4)
        self._8.setMargin(4)
        self._8.setObjectName("_8")
        self.interviewer1_first_name_text = QtGui.QLabel(self.interviewee_first_name_3)
        self.interviewer1_first_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_first_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_first_name_text.setObjectName("interviewer1_first_name_text")
        self._8.addWidget(self.interviewer1_first_name_text)
        self.interviewer1_first_name_line = QtGui.QLineEdit(self.interviewee_first_name_3)
        self.interviewer1_first_name_line.setEnabled(True)
        self.interviewer1_first_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_first_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer1_first_name_line.setObjectName("interviewer1_first_name_line")
        self._8.addWidget(self.interviewer1_first_name_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_3)
        self.interviewee_first_name_4 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_4.setObjectName("interviewee_first_name_4")
        self._9 = QtGui.QHBoxLayout(self.interviewee_first_name_4)
        self._9.setSpacing(4)
        self._9.setMargin(4)
        self._9.setObjectName("_9")
        self.interviewer1_last_name_text = QtGui.QLabel(self.interviewee_first_name_4)
        self.interviewer1_last_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_last_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.interviewer1_last_name_text.setObjectName("interviewer1_last_name_text")
        self._9.addWidget(self.interviewer1_last_name_text)
        self.interviewer1_last_name_line = QtGui.QLineEdit(self.interviewee_first_name_4)
        self.interviewer1_last_name_line.setEnabled(True)
        self.interviewer1_last_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_last_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.interviewer1_last_name_line.setObjectName("interviewer1_last_name_line")
        self._9.addWidget(self.interviewer1_last_name_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_4)
        self.interviewee_first_name_5 = QtGui.QWidget(self.interviewee_2)
        self.interviewee_first_name_5.setObjectName("interviewee_first_name_5")
        self._10 = QtGui.QHBoxLayout(self.interviewee_first_name_5)
        self._10.setSpacing(4)
        self._10.setMargin(4)
        self._10.setObjectName("_10")
        self.mood_text = QtGui.QLabel(self.interviewee_first_name_5)
        self.mood_text.setMinimumSize(QtCore.QSize(180, 0))
        self.mood_text.setMaximumSize(QtCore.QSize(180, 16777215))
        self.mood_text.setObjectName("mood_text")
        self._10.addWidget(self.mood_text)
        self.mood_line = QtGui.QLineEdit(self.interviewee_first_name_5)
        self.mood_line.setEnabled(True)
        self.mood_line.setMinimumSize(QtCore.QSize(150, 0))
        self.mood_line.setMaximumSize(QtCore.QSize(150, 16777215))
        self.mood_line.setObjectName("mood_line")
        self._10.addWidget(self.mood_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_5)
        self.verticalLayout_4.addWidget(self.interviewee_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.vessel_info = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_port_5 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_5.setFont(font)
        self.home_port_5.setObjectName("home_port_5")
        self._11 = QtGui.QHBoxLayout(self.home_port_5)
        self._11.setSpacing(4)
        self._11.setMargin(4)
        self._11.setObjectName("_11")
        self.years_text = QtGui.QLabel(self.home_port_5)
        self.years_text.setMinimumSize(QtCore.QSize(150, 0))
        self.years_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_text.setFont(font)
        self.years_text.setObjectName("years_text")
        self._11.addWidget(self.years_text)
        self.years_line = QtGui.QLineEdit(self.home_port_5)
        self.years_line.setEnabled(True)
        self.years_line.setMinimumSize(QtCore.QSize(100, 0))
        self.years_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.years_line.setFont(font)
        self.years_line.setObjectName("years_line")
        self._11.addWidget(self.years_line)
        self.verticalLayout.addWidget(self.home_port_5)
        self.home_port_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_2.setFont(font)
        self.home_port_2.setObjectName("home_port_2")
        self._4 = QtGui.QHBoxLayout(self.home_port_2)
        self._4.setSpacing(4)
        self._4.setMargin(4)
        self._4.setObjectName("_4")
        self.perc_income_text = QtGui.QLabel(self.home_port_2)
        self.perc_income_text.setMinimumSize(QtCore.QSize(150, 0))
        self.perc_income_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perc_income_text.setFont(font)
        self.perc_income_text.setObjectName("perc_income_text")
        self._4.addWidget(self.perc_income_text)
        self.perc_income_line = QtGui.QLineEdit(self.home_port_2)
        self.perc_income_line.setEnabled(True)
        self.perc_income_line.setMinimumSize(QtCore.QSize(100, 0))
        self.perc_income_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.perc_income_line.setFont(font)
        self.perc_income_line.setObjectName("perc_income_line")
        self._4.addWidget(self.perc_income_line)
        self.verticalLayout.addWidget(self.home_port_2)
        self.ves_license = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license.setFont(font)
        self.ves_license.setObjectName("ves_license")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.ves_license)
        self.hboxlayout4.setSpacing(4)
        self.hboxlayout4.setMargin(4)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.federal_vessel_id_text = QtGui.QLabel(self.ves_license)
        self.federal_vessel_id_text.setMinimumSize(QtCore.QSize(150, 0))
        self.federal_vessel_id_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.federal_vessel_id_text.setFont(font)
        self.federal_vessel_id_text.setObjectName("federal_vessel_id_text")
        self.hboxlayout4.addWidget(self.federal_vessel_id_text)
        self.federal_vessel_id_line = QtGui.QLineEdit(self.ves_license)
        self.federal_vessel_id_line.setEnabled(True)
        self.federal_vessel_id_line.setMinimumSize(QtCore.QSize(200, 0))
        self.federal_vessel_id_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.federal_vessel_id_line.setFont(font)
        self.federal_vessel_id_line.setObjectName("federal_vessel_id_line")
        self.hboxlayout4.addWidget(self.federal_vessel_id_line)
        self.verticalLayout.addWidget(self.ves_license)
        self.ves_license_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ves_license_2.setFont(font)
        self.ves_license_2.setObjectName("ves_license_2")
        self._13 = QtGui.QHBoxLayout(self.ves_license_2)
        self._13.setSpacing(4)
        self._13.setMargin(4)
        self._13.setObjectName("_13")
        self.state_vessel_id_text = QtGui.QLabel(self.ves_license_2)
        self.state_vessel_id_text.setMinimumSize(QtCore.QSize(150, 0))
        self.state_vessel_id_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.state_vessel_id_text.setFont(font)
        self.state_vessel_id_text.setObjectName("state_vessel_id_text")
        self._13.addWidget(self.state_vessel_id_text)
        self.state_vessel_id_line = QtGui.QLineEdit(self.ves_license_2)
        self.state_vessel_id_line.setEnabled(True)
        self.state_vessel_id_line.setMinimumSize(QtCore.QSize(200, 0))
        self.state_vessel_id_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.state_vessel_id_line.setFont(font)
        self.state_vessel_id_line.setObjectName("state_vessel_id_line")
        self._13.addWidget(self.state_vessel_id_line)
        self.verticalLayout.addWidget(self.ves_license_2)
        self.vessel_length = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length.setFont(font)
        self.vessel_length.setObjectName("vessel_length")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.vessel_length)
        self.hboxlayout5.setSpacing(4)
        self.hboxlayout5.setMargin(4)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.vessel_length_text = QtGui.QLabel(self.vessel_length)
        self.vessel_length_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_length_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_text.setFont(font)
        self.vessel_length_text.setObjectName("vessel_length_text")
        self.hboxlayout5.addWidget(self.vessel_length_text)
        self.vessel_length_line = QtGui.QLineEdit(self.vessel_length)
        self.vessel_length_line.setEnabled(True)
        self.vessel_length_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_length_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_line.setFont(font)
        self.vessel_length_line.setObjectName("vessel_length_line")
        self.hboxlayout5.addWidget(self.vessel_length_line)
        self.verticalLayout.addWidget(self.vessel_length)
        self.vessel_length_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_2.setFont(font)
        self.vessel_length_2.setObjectName("vessel_length_2")
        self._14 = QtGui.QHBoxLayout(self.vessel_length_2)
        self._14.setSpacing(4)
        self._14.setMargin(4)
        self._14.setObjectName("_14")
        self.vessel_motor_text = QtGui.QLabel(self.vessel_length_2)
        self.vessel_motor_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_motor_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_text.setFont(font)
        self.vessel_motor_text.setObjectName("vessel_motor_text")
        self._14.addWidget(self.vessel_motor_text)
        self.vessel_motor_line = QtGui.QLineEdit(self.vessel_length_2)
        self.vessel_motor_line.setEnabled(True)
        self.vessel_motor_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_motor_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_motor_line.setFont(font)
        self.vessel_motor_line.setObjectName("vessel_motor_line")
        self._14.addWidget(self.vessel_motor_line)
        self.verticalLayout.addWidget(self.vessel_length_2)
        self.vessel_length_3 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vessel_length_3.setFont(font)
        self.vessel_length_3.setObjectName("vessel_length_3")
        self._15 = QtGui.QHBoxLayout(self.vessel_length_3)
        self._15.setSpacing(4)
        self._15.setMargin(4)
        self._15.setObjectName("_15")
        self.haul_capacity_text = QtGui.QLabel(self.vessel_length_3)
        self.haul_capacity_text.setMinimumSize(QtCore.QSize(150, 0))
        self.haul_capacity_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_text.setFont(font)
        self.haul_capacity_text.setObjectName("haul_capacity_text")
        self._15.addWidget(self.haul_capacity_text)
        self.haul_capacity_line = QtGui.QLineEdit(self.vessel_length_3)
        self.haul_capacity_line.setEnabled(True)
        self.haul_capacity_line.setMinimumSize(QtCore.QSize(200, 0))
        self.haul_capacity_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.haul_capacity_line.setFont(font)
        self.haul_capacity_line.setObjectName("haul_capacity_line")
        self._15.addWidget(self.haul_capacity_line)
        self.verticalLayout.addWidget(self.vessel_length_3)
        self.home_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port.setFont(font)
        self.home_port.setObjectName("home_port")
        self.hboxlayout6 = QtGui.QHBoxLayout(self.home_port)
        self.hboxlayout6.setSpacing(4)
        self.hboxlayout6.setMargin(4)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.home_port_text = QtGui.QLabel(self.home_port)
        self.home_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.home_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_text.setFont(font)
        self.home_port_text.setObjectName("home_port_text")
        self.hboxlayout6.addWidget(self.home_port_text)
        self.home_port_line = QtGui.QLineEdit(self.home_port)
        self.home_port_line.setEnabled(True)
        self.home_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.home_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_line.setFont(font)
        self.home_port_line.setObjectName("home_port_line")
        self.hboxlayout6.addWidget(self.home_port_line)
        self.verticalLayout.addWidget(self.home_port)
        self.home_port_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_4.setFont(font)
        self.home_port_4.setObjectName("home_port_4")
        self._7 = QtGui.QHBoxLayout(self.home_port_4)
        self._7.setSpacing(4)
        self._7.setMargin(4)
        self._7.setObjectName("_7")
        self.landing_port_text = QtGui.QLabel(self.home_port_4)
        self.landing_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text.setFont(font)
        self.landing_port_text.setObjectName("landing_port_text")
        self._7.addWidget(self.landing_port_text)
        self.landing_port_line = QtGui.QLineEdit(self.home_port_4)
        self.landing_port_line.setEnabled(True)
        self.landing_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line.setFont(font)
        self.landing_port_line.setObjectName("landing_port_line")
        self._7.addWidget(self.landing_port_line)
        self.verticalLayout.addWidget(self.home_port_4)
        self.home_port_7 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_7.setFont(font)
        self.home_port_7.setObjectName("home_port_7")
        self._16 = QtGui.QHBoxLayout(self.home_port_7)
        self._16.setSpacing(4)
        self._16.setMargin(4)
        self._16.setObjectName("_16")
        self.landing_port_text_2 = QtGui.QLabel(self.home_port_7)
        self.landing_port_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_2.setFont(font)
        self.landing_port_text_2.setObjectName("landing_port_text_2")
        self._16.addWidget(self.landing_port_text_2)
        self.landing_port_line_2 = QtGui.QLineEdit(self.home_port_7)
        self.landing_port_line_2.setEnabled(True)
        self.landing_port_line_2.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_2.setFont(font)
        self.landing_port_line_2.setObjectName("landing_port_line_2")
        self._16.addWidget(self.landing_port_line_2)
        self.verticalLayout.addWidget(self.home_port_7)
        self.home_port_8 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_8.setFont(font)
        self.home_port_8.setObjectName("home_port_8")
        self._17 = QtGui.QHBoxLayout(self.home_port_8)
        self._17.setSpacing(4)
        self._17.setMargin(4)
        self._17.setObjectName("_17")
        self.landing_port_text_3 = QtGui.QLabel(self.home_port_8)
        self.landing_port_text_3.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_3.setFont(font)
        self.landing_port_text_3.setObjectName("landing_port_text_3")
        self._17.addWidget(self.landing_port_text_3)
        self.landing_port_line_3 = QtGui.QLineEdit(self.home_port_8)
        self.landing_port_line_3.setEnabled(True)
        self.landing_port_line_3.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_3.setFont(font)
        self.landing_port_line_3.setObjectName("landing_port_line_3")
        self._17.addWidget(self.landing_port_line_3)
        self.verticalLayout.addWidget(self.home_port_8)
        self.home_port_9 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_port_9.setFont(font)
        self.home_port_9.setObjectName("home_port_9")
        self._18 = QtGui.QHBoxLayout(self.home_port_9)
        self._18.setSpacing(4)
        self._18.setMargin(4)
        self._18.setObjectName("_18")
        self.landing_port_text_4 = QtGui.QLabel(self.home_port_9)
        self.landing_port_text_4.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_text_4.setFont(font)
        self.landing_port_text_4.setObjectName("landing_port_text_4")
        self._18.addWidget(self.landing_port_text_4)
        self.landing_port_line_4 = QtGui.QLineEdit(self.home_port_9)
        self.landing_port_line_4.setEnabled(True)
        self.landing_port_line_4.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.landing_port_line_4.setFont(font)
        self.landing_port_line_4.setObjectName("landing_port_line_4")
        self._18.addWidget(self.landing_port_line_4)
        self.verticalLayout.addWidget(self.home_port_9)
        self.horizontalLayout.addWidget(self.vessel_info)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.button_box = QtGui.QWidget(InterviewStart)
        self.button_box.setObjectName("button_box")
        self._19 = QtGui.QHBoxLayout(self.button_box)
        self._19.setSpacing(2)
        self._19.setMargin(2)
        self._19.setObjectName("_19")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._19.addItem(spacerItem1)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self._19.addWidget(self.pbnCancel)
        self.pbnSelectFishery = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnSelectFishery.setFont(font)
        self.pbnSelectFishery.setObjectName("pbnSelectFishery")
        self._19.addWidget(self.pbnSelectFishery)
        self.verticalLayout_3.addWidget(self.button_box)

        self.retranslateUi(InterviewStart)
        QtCore.QMetaObject.connectSlotsByName(InterviewStart)

    def retranslateUi(self, InterviewStart):
        InterviewStart.setWindowTitle(QtGui.QApplication.translate("InterviewStart", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee.setTitle(QtGui.QApplication.translate("InterviewStart", "Interviewee", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_first_name_text.setText(QtGui.QApplication.translate("InterviewStart", "First Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_last_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Last Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.age_text.setText(QtGui.QApplication.translate("InterviewStart", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_text.setText(QtGui.QApplication.translate("InterviewStart", "Gender:", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_comboBox.setItemText(1, QtGui.QApplication.translate("InterviewStart", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_comboBox.setItemText(2, QtGui.QApplication.translate("InterviewStart", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.city_text.setText(QtGui.QApplication.translate("InterviewStart", "City of residence:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_2.setTitle(QtGui.QApplication.translate("InterviewStart", "Interviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.date_text.setText(QtGui.QApplication.translate("InterviewStart", "Interview Date (mm/dd/yyyy):", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_first_name_text.setText(QtGui.QApplication.translate("InterviewStart", "First Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_last_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Last Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.mood_text.setText(QtGui.QApplication.translate("InterviewStart", "Interviewer Mood:", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("InterviewStart", "Commercial Fishing Information", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text.setText(QtGui.QApplication.translate("InterviewStart", "Years experience:", None, QtGui.QApplication.UnicodeUTF8))
        self.perc_income_text.setText(QtGui.QApplication.translate("InterviewStart", "% income from fishing:", None, QtGui.QApplication.UnicodeUTF8))
        self.federal_vessel_id_text.setText(QtGui.QApplication.translate("InterviewStart", "Federal Vessel ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.state_vessel_id_text.setText(QtGui.QApplication.translate("InterviewStart", "State vessel ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text.setText(QtGui.QApplication.translate("InterviewStart", "Vessel length :", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_text.setText(QtGui.QApplication.translate("InterviewStart", "Vessel motor (HP):", None, QtGui.QApplication.UnicodeUTF8))
        self.haul_capacity_text.setText(QtGui.QApplication.translate("InterviewStart", "Haul Capacity (Kg):", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text.setText(QtGui.QApplication.translate("InterviewStart", "Home Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_2.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_3.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_4.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("InterviewStart", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectFishery.setText(QtGui.QApplication.translate("InterviewStart", "Select Fishery", None, QtGui.QApplication.UnicodeUTF8))

