# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectfishery.ui'
#
# Created: Sat Nov 07 09:58:49 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SelectFishery(object):
    def setupUi(self, SelectFishery):
        SelectFishery.setObjectName("SelectFishery")
        SelectFishery.resize(460, 361)
        self.verticalLayout = QtGui.QVBoxLayout(SelectFishery)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtGui.QWidget(SelectFishery)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setContentsMargins(9, 9, 9, 0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.fishery_text = QtGui.QLabel(self.widget)
        self.fishery_text.setMinimumSize(QtCore.QSize(100, 0))
        self.fishery_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fishery_text.setObjectName("fishery_text")
        self.hboxlayout.addWidget(self.fishery_text)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.fishery_comboBox = QtGui.QComboBox(self.widget)
        self.fishery_comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.fishery_comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fishery_comboBox.setObjectName("fishery_comboBox")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.setItemText(0, "")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.hboxlayout.addWidget(self.fishery_comboBox)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtGui.QWidget(SelectFishery)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(160, 0))
        self.label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.fish_perc_income = QtGui.QLineEdit(self.widget_3)
        self.fish_perc_income.setMinimumSize(QtCore.QSize(40, 0))
        self.fish_perc_income.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fish_perc_income.setObjectName("fish_perc_income")
        self.horizontalLayout_4.addWidget(self.fish_perc_income)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_4 = QtGui.QWidget(SelectFishery)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.fish_yrs_partic = QtGui.QLineEdit(self.widget_4)
        self.fish_yrs_partic.setMinimumSize(QtCore.QSize(40, 0))
        self.fish_yrs_partic.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fish_yrs_partic.setObjectName("fish_yrs_partic")
        self.horizontalLayout_8.addWidget(self.fish_yrs_partic)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_7 = QtGui.QWidget(SelectFishery)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtGui.QLabel(self.widget_7)
        self.label_6.setMinimumSize(QtCore.QSize(300, 0))
        self.label_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.fish_num_gear = QtGui.QLineEdit(self.widget_7)
        self.fish_num_gear.setMinimumSize(QtCore.QSize(40, 0))
        self.fish_num_gear.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fish_num_gear.setObjectName("fish_num_gear")
        self.horizontalLayout_14.addWidget(self.fish_num_gear)
        self.horizontalLayout_13.addWidget(self.widget_7)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_5 = QtGui.QWidget(SelectFishery)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtGui.QLabel(self.widget_5)
        self.label_4.setMinimumSize(QtCore.QSize(160, 0))
        self.label_4.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.fish_months = QtGui.QLineEdit(self.widget_5)
        self.fish_months.setMinimumSize(QtCore.QSize(220, 0))
        self.fish_months.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fish_months.setObjectName("fish_months")
        self.horizontalLayout_10.addWidget(self.fish_months)
        self.horizontalLayout_9.addWidget(self.widget_5)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_6 = QtGui.QWidget(SelectFishery)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtGui.QLabel(self.widget_6)
        self.label_5.setMinimumSize(QtCore.QSize(160, 0))
        self.label_5.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.fish_avg_days = QtGui.QLineEdit(self.widget_6)
        self.fish_avg_days.setMinimumSize(QtCore.QSize(40, 0))
        self.fish_avg_days.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fish_avg_days.setObjectName("fish_avg_days")
        self.horizontalLayout_12.addWidget(self.fish_avg_days)
        self.horizontalLayout_11.addWidget(self.widget_6)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtGui.QWidget(SelectFishery)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget_2)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(9)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem6)
        self.pbnFisheryFinished = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnFisheryFinished.setFont(font)
        self.pbnFisheryFinished.setObjectName("pbnFisheryFinished")
        self.hboxlayout1.addWidget(self.pbnFisheryFinished)
        self.pbnStartShapes = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnStartShapes.setFont(font)
        self.pbnStartShapes.setObjectName("pbnStartShapes")
        self.hboxlayout1.addWidget(self.pbnStartShapes)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SelectFishery)
        QtCore.QMetaObject.connectSlotsByName(SelectFishery)

    def retranslateUi(self, SelectFishery):
        SelectFishery.setWindowTitle(QtGui.QApplication.translate("SelectFishery", "OpenOceanMap - Select Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_text.setText(QtGui.QApplication.translate("SelectFishery", "Select Fishery :", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(1, QtGui.QApplication.translate("SelectFishery", "Albacore Tuna - Troll (Jig)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(2, QtGui.QApplication.translate("SelectFishery", "Dungeness Crab - Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(3, QtGui.QApplication.translate("SelectFishery", "Flatfish – Hook and Line", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(4, QtGui.QApplication.translate("SelectFishery", "Groundfish - Midwater Trawl Pre RCA", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(5, QtGui.QApplication.translate("SelectFishery", "Groundfish - Midwater Trawl Post RCA", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(6, QtGui.QApplication.translate("SelectFishery", "Groundfish - Bottom Trawl Pre RCA", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(7, QtGui.QApplication.translate("SelectFishery", "Groundfish - Bottom Trawl Post RCA", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(8, QtGui.QApplication.translate("SelectFishery", "Groundfish - Longline Pre RCA (LE)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(9, QtGui.QApplication.translate("SelectFishery", "Groundfish - Longline Post RCA (LE)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(10, QtGui.QApplication.translate("SelectFishery", "Groundfish - Hook and Line Pre RCA (LE)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(11, QtGui.QApplication.translate("SelectFishery", "Groundfish - Hook and Line Post RCA (LE)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(12, QtGui.QApplication.translate("SelectFishery", "Groundfish - Trap Pre RCA (LE)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(13, QtGui.QApplication.translate("SelectFishery", "Groundfish - Trap Post RCA (LE)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(14, QtGui.QApplication.translate("SelectFishery", "Groundfish - Longline Pre RCA (OA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(15, QtGui.QApplication.translate("SelectFishery", "Groundfish - Longline Post RCA (OA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(16, QtGui.QApplication.translate("SelectFishery", "Groundfish - Hook and Line Pre RCA (OA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(17, QtGui.QApplication.translate("SelectFishery", "Groundfish - Hook and Line Post RCA (OA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(18, QtGui.QApplication.translate("SelectFishery", "Groundfish - Trap Pre RCA (OA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(19, QtGui.QApplication.translate("SelectFishery", "Groundfish - Trap Post RCA (OA)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(20, QtGui.QApplication.translate("SelectFishery", "Hagfish – Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(21, QtGui.QApplication.translate("SelectFishery", "Halibut – Longline", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(22, QtGui.QApplication.translate("SelectFishery", "Pink Shrimp – Trawl", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(23, QtGui.QApplication.translate("SelectFishery", "Salmon – Troll", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(24, QtGui.QApplication.translate("SelectFishery", "Sardine - Net (Seine)", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(25, QtGui.QApplication.translate("SelectFishery", "Shrimp/Prawn – Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(26, QtGui.QApplication.translate("SelectFishery", "Urchin - Dive", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(27, QtGui.QApplication.translate("SelectFishery", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SelectFishery", "Percent income from this fishery:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SelectFishery", "Years participating in this fishery:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SelectFishery", "# traps owned/hooks used per day/avg net tows per day:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SelectFishery", "Months of fishing effort:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SelectFishery", "Avg # days fishing per year", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFisheryFinished.setText(QtGui.QApplication.translate("SelectFishery", "Finished With Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnStartShapes.setText(QtGui.QApplication.translate("SelectFishery", "Start Drawing Shapes", None, QtGui.QApplication.UnicodeUTF8))

