# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interviewstart.ui'
#
# Created: Fri Feb 26 14:49:44 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_InterviewStart(object):
    def setupUi(self, InterviewStart):
        InterviewStart.setObjectName("InterviewStart")
        InterviewStart.resize(778, 494)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        InterviewStart.setFont(font)
        self.verticalLayout_3 = QtGui.QVBoxLayout(InterviewStart)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.interviewee = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee.setFont(font)
        self.interviewee.setObjectName("interviewee")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.interviewee)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.interviewee_first_name = QtGui.QWidget(self.interviewee)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_first_name.setFont(font)
        self.interviewee_first_name.setObjectName("interviewee_first_name")
        self.hboxlayout = QtGui.QHBoxLayout(self.interviewee_first_name)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(4)
        self.hboxlayout.setObjectName("hboxlayout")
        self.interviewee_first_name_text = QtGui.QLabel(self.interviewee_first_name)
        self.interviewee_first_name_text.setMinimumSize(QtCore.QSize(130, 0))
        self.interviewee_first_name_text.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_first_name_text.setFont(font)
        self.interviewee_first_name_text.setObjectName("interviewee_first_name_text")
        self.hboxlayout.addWidget(self.interviewee_first_name_text)
        self.interviewee_first_name_line = QtGui.QLineEdit(self.interviewee_first_name)
        self.interviewee_first_name_line.setEnabled(True)
        self.interviewee_first_name_line.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewee_first_name_line.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.interviewee_first_name_line.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_first_name_line.setFont(font)
        self.interviewee_first_name_line.setObjectName("interviewee_first_name_line")
        self.hboxlayout.addWidget(self.interviewee_first_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_first_name)
        self.interviewee_last_name = QtGui.QWidget(self.interviewee)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_last_name.setFont(font)
        self.interviewee_last_name.setObjectName("interviewee_last_name")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.interviewee_last_name)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(4)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.interviewee_last_name_text = QtGui.QLabel(self.interviewee_last_name)
        self.interviewee_last_name_text.setMinimumSize(QtCore.QSize(130, 0))
        self.interviewee_last_name_text.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_last_name_text.setFont(font)
        self.interviewee_last_name_text.setObjectName("interviewee_last_name_text")
        self.hboxlayout1.addWidget(self.interviewee_last_name_text)
        self.interviewee_last_name_line = QtGui.QLineEdit(self.interviewee_last_name)
        self.interviewee_last_name_line.setEnabled(True)
        self.interviewee_last_name_line.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewee_last_name_line.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.interviewee_last_name_line.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_last_name_line.setFont(font)
        self.interviewee_last_name_line.setObjectName("interviewee_last_name_line")
        self.hboxlayout1.addWidget(self.interviewee_last_name_line)
        self.verticalLayout_2.addWidget(self.interviewee_last_name)
        self.age = QtGui.QWidget(self.interviewee)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.age)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(4)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.age_text = QtGui.QLabel(self.age)
        self.age_text.setMinimumSize(QtCore.QSize(130, 0))
        self.age_text.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.age_text.setFont(font)
        self.age_text.setObjectName("age_text")
        self.hboxlayout2.addWidget(self.age_text)
        self.age_line = QtGui.QLineEdit(self.age)
        self.age_line.setEnabled(True)
        self.age_line.setMinimumSize(QtCore.QSize(180, 0))
        self.age_line.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.age_line.setFont(font)
        self.age_line.setObjectName("age_line")
        self.hboxlayout2.addWidget(self.age_line)
        self.verticalLayout_2.addWidget(self.age)
        self.gender = QtGui.QWidget(self.interviewee)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.gender)
        self.hboxlayout3.setSpacing(4)
        self.hboxlayout3.setMargin(4)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.gender_text = QtGui.QLabel(self.gender)
        self.gender_text.setMinimumSize(QtCore.QSize(130, 0))
        self.gender_text.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gender_text.setFont(font)
        self.gender_text.setObjectName("gender_text")
        self.hboxlayout3.addWidget(self.gender_text)
        self.gender_comboBox = QtGui.QComboBox(self.gender)
        self.gender_comboBox.setMinimumSize(QtCore.QSize(180, 0))
        self.gender_comboBox.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gender_comboBox.setFont(font)
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.gender_comboBox.addItem(QtCore.QString())
        self.gender_comboBox.setItemText(0, "")
        self.gender_comboBox.addItem(QtCore.QString())
        self.gender_comboBox.addItem(QtCore.QString())
        self.hboxlayout3.addWidget(self.gender_comboBox)
        self.verticalLayout_2.addWidget(self.gender)
        self.age_2 = QtGui.QWidget(self.interviewee)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.age_2.setFont(font)
        self.age_2.setObjectName("age_2")
        self._2 = QtGui.QHBoxLayout(self.age_2)
        self._2.setSpacing(4)
        self._2.setMargin(4)
        self._2.setObjectName("_2")
        self.city_text = QtGui.QLabel(self.age_2)
        self.city_text.setMinimumSize(QtCore.QSize(130, 0))
        self.city_text.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.city_text.setFont(font)
        self.city_text.setObjectName("city_text")
        self._2.addWidget(self.city_text)
        self.city_line = QtGui.QLineEdit(self.age_2)
        self.city_line.setEnabled(True)
        self.city_line.setMinimumSize(QtCore.QSize(180, 0))
        self.city_line.setMaximumSize(QtCore.QSize(180, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.city_line.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.city_line.setFont(font)
        self.city_line.setObjectName("city_line")
        self._2.addWidget(self.city_line)
        self.verticalLayout_2.addWidget(self.age_2)
        self.data_sharing = QtGui.QWidget(self.interviewee)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.data_sharing.setFont(font)
        self.data_sharing.setObjectName("data_sharing")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.data_sharing)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.data_sharing_text = QtGui.QLabel(self.data_sharing)
        self.data_sharing_text.setMinimumSize(QtCore.QSize(100, 0))
        self.data_sharing_text.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.data_sharing_text.setFont(font)
        self.data_sharing_text.setObjectName("data_sharing_text")
        self.verticalLayout_7.addWidget(self.data_sharing_text)
        self.data_sharing_comboBox = QtGui.QComboBox(self.data_sharing)
        self.data_sharing_comboBox.setMaximumSize(QtCore.QSize(320, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.data_sharing_comboBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.data_sharing_comboBox.setFont(font)
        self.data_sharing_comboBox.setObjectName("data_sharing_comboBox")
        self.data_sharing_comboBox.addItem(QtCore.QString())
        self.data_sharing_comboBox.setItemText(0, "")
        self.data_sharing_comboBox.addItem(QtCore.QString())
        self.data_sharing_comboBox.addItem(QtCore.QString())
        self.data_sharing_comboBox.addItem(QtCore.QString())
        self.data_sharing_comboBox.addItem(QtCore.QString())
        self.verticalLayout_7.addWidget(self.data_sharing_comboBox)
        self.verticalLayout_2.addWidget(self.data_sharing)
        self.verticalLayout_4.addWidget(self.interviewee)
        self.interviewee_2 = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_2.setFont(font)
        self.interviewee_2.setObjectName("interviewee_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.interviewee_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.interviewee_first_name_2 = QtGui.QWidget(self.interviewee_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_first_name_2.setFont(font)
        self.interviewee_first_name_2.setObjectName("interviewee_first_name_2")
        self._3 = QtGui.QHBoxLayout(self.interviewee_first_name_2)
        self._3.setSpacing(4)
        self._3.setMargin(4)
        self._3.setObjectName("_3")
        self.date_text = QtGui.QLabel(self.interviewee_first_name_2)
        self.date_text.setMinimumSize(QtCore.QSize(180, 0))
        self.date_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.date_text.setFont(font)
        self.date_text.setObjectName("date_text")
        self._3.addWidget(self.date_text)
        self.InterviewDate = QtGui.QDateEdit(self.interviewee_first_name_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.InterviewDate.setPalette(palette)
        self.InterviewDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.InterviewDate.setTime(QtCore.QTime(0, 0, 0))
        self.InterviewDate.setCalendarPopup(True)
        self.InterviewDate.setCurrentSectionIndex(0)
        self.InterviewDate.setObjectName("InterviewDate")
        self._3.addWidget(self.InterviewDate)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_2)
        self.interviewee_first_name_3 = QtGui.QWidget(self.interviewee_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_first_name_3.setFont(font)
        self.interviewee_first_name_3.setObjectName("interviewee_first_name_3")
        self._8 = QtGui.QHBoxLayout(self.interviewee_first_name_3)
        self._8.setSpacing(4)
        self._8.setMargin(4)
        self._8.setObjectName("_8")
        self.interviewer1_first_name_text = QtGui.QLabel(self.interviewee_first_name_3)
        self.interviewer1_first_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_first_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewer1_first_name_text.setFont(font)
        self.interviewer1_first_name_text.setObjectName("interviewer1_first_name_text")
        self._8.addWidget(self.interviewer1_first_name_text)
        self.interviewer1_first_name_line = QtGui.QLineEdit(self.interviewee_first_name_3)
        self.interviewer1_first_name_line.setEnabled(True)
        self.interviewer1_first_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_first_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.interviewer1_first_name_line.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewer1_first_name_line.setFont(font)
        self.interviewer1_first_name_line.setObjectName("interviewer1_first_name_line")
        self._8.addWidget(self.interviewer1_first_name_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_3)
        self.interviewee_first_name_4 = QtGui.QWidget(self.interviewee_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_first_name_4.setFont(font)
        self.interviewee_first_name_4.setObjectName("interviewee_first_name_4")
        self._9 = QtGui.QHBoxLayout(self.interviewee_first_name_4)
        self._9.setSpacing(4)
        self._9.setMargin(4)
        self._9.setObjectName("_9")
        self.interviewer1_last_name_text = QtGui.QLabel(self.interviewee_first_name_4)
        self.interviewer1_last_name_text.setMinimumSize(QtCore.QSize(180, 0))
        self.interviewer1_last_name_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewer1_last_name_text.setFont(font)
        self.interviewer1_last_name_text.setObjectName("interviewer1_last_name_text")
        self._9.addWidget(self.interviewer1_last_name_text)
        self.interviewer1_last_name_line = QtGui.QLineEdit(self.interviewee_first_name_4)
        self.interviewer1_last_name_line.setEnabled(True)
        self.interviewer1_last_name_line.setMinimumSize(QtCore.QSize(150, 0))
        self.interviewer1_last_name_line.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.interviewer1_last_name_line.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewer1_last_name_line.setFont(font)
        self.interviewer1_last_name_line.setObjectName("interviewer1_last_name_line")
        self._9.addWidget(self.interviewer1_last_name_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_4)
        self.interviewee_first_name_5 = QtGui.QWidget(self.interviewee_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.interviewee_first_name_5.setFont(font)
        self.interviewee_first_name_5.setObjectName("interviewee_first_name_5")
        self._10 = QtGui.QHBoxLayout(self.interviewee_first_name_5)
        self._10.setSpacing(4)
        self._10.setMargin(4)
        self._10.setObjectName("_10")
        self.mood_text = QtGui.QLabel(self.interviewee_first_name_5)
        self.mood_text.setMinimumSize(QtCore.QSize(180, 0))
        self.mood_text.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mood_text.setFont(font)
        self.mood_text.setObjectName("mood_text")
        self._10.addWidget(self.mood_text)
        self.mood_line = QtGui.QLineEdit(self.interviewee_first_name_5)
        self.mood_line.setEnabled(True)
        self.mood_line.setMinimumSize(QtCore.QSize(150, 0))
        self.mood_line.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mood_line.setFont(font)
        self.mood_line.setObjectName("mood_line")
        self._10.addWidget(self.mood_line)
        self.verticalLayout_5.addWidget(self.interviewee_first_name_5)
        self.verticalLayout_4.addWidget(self.interviewee_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.vessel_info = QtGui.QGroupBox(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_info.setFont(font)
        self.vessel_info.setObjectName("vessel_info")
        self.verticalLayout = QtGui.QVBoxLayout(self.vessel_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.home_port.setFont(font)
        self.home_port.setObjectName("home_port")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.home_port)
        self.hboxlayout4.setSpacing(4)
        self.hboxlayout4.setMargin(4)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.home_port_text = QtGui.QLabel(self.home_port)
        self.home_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.home_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.home_port_text.setFont(font)
        self.home_port_text.setObjectName("home_port_text")
        self.hboxlayout4.addWidget(self.home_port_text)
        self.home_port_line = QtGui.QLineEdit(self.home_port)
        self.home_port_line.setEnabled(True)
        self.home_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.home_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.home_port_line.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.home_port_line.setFont(font)
        self.home_port_line.setObjectName("home_port_line")
        self.hboxlayout4.addWidget(self.home_port_line)
        self.verticalLayout.addWidget(self.home_port)
        self.years_experience = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.years_experience.setFont(font)
        self.years_experience.setObjectName("years_experience")
        self._11 = QtGui.QHBoxLayout(self.years_experience)
        self._11.setSpacing(4)
        self._11.setMargin(4)
        self._11.setObjectName("_11")
        self.years_text = QtGui.QLabel(self.years_experience)
        self.years_text.setMinimumSize(QtCore.QSize(150, 0))
        self.years_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.years_text.setFont(font)
        self.years_text.setObjectName("years_text")
        self._11.addWidget(self.years_text)
        self.years_line = QtGui.QLineEdit(self.years_experience)
        self.years_line.setEnabled(True)
        self.years_line.setMinimumSize(QtCore.QSize(100, 0))
        self.years_line.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 255, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.years_line.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.years_line.setFont(font)
        self.years_line.setObjectName("years_line")
        self._11.addWidget(self.years_line)
        self.verticalLayout.addWidget(self.years_experience)
        self.perc_income = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.perc_income.setFont(font)
        self.perc_income.setObjectName("perc_income")
        self._4 = QtGui.QHBoxLayout(self.perc_income)
        self._4.setSpacing(4)
        self._4.setMargin(4)
        self._4.setObjectName("_4")
        self.perc_income_text = QtGui.QLabel(self.perc_income)
        self.perc_income_text.setMinimumSize(QtCore.QSize(150, 0))
        self.perc_income_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.perc_income_text.setFont(font)
        self.perc_income_text.setObjectName("perc_income_text")
        self._4.addWidget(self.perc_income_text)
        self.perc_income_line = QtGui.QLineEdit(self.perc_income)
        self.perc_income_line.setEnabled(True)
        self.perc_income_line.setMinimumSize(QtCore.QSize(100, 0))
        self.perc_income_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.perc_income_line.setFont(font)
        self.perc_income_line.setObjectName("perc_income_line")
        self._4.addWidget(self.perc_income_line)
        self.verticalLayout.addWidget(self.perc_income)
        self.vessel_name = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_name.setFont(font)
        self.vessel_name.setObjectName("vessel_name")
        self._6 = QtGui.QHBoxLayout(self.vessel_name)
        self._6.setSpacing(4)
        self._6.setMargin(4)
        self._6.setObjectName("_6")
        self.vessel_name_text = QtGui.QLabel(self.vessel_name)
        self.vessel_name_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_name_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_name_text.setFont(font)
        self.vessel_name_text.setObjectName("vessel_name_text")
        self._6.addWidget(self.vessel_name_text)
        self.vessel_name_line = QtGui.QLineEdit(self.vessel_name)
        self.vessel_name_line.setEnabled(True)
        self.vessel_name_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_name_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_name_line.setFont(font)
        self.vessel_name_line.setObjectName("vessel_name_line")
        self._6.addWidget(self.vessel_name_line)
        self.verticalLayout.addWidget(self.vessel_name)
        self.vessel_length = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_length.setFont(font)
        self.vessel_length.setObjectName("vessel_length")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.vessel_length)
        self.hboxlayout5.setSpacing(4)
        self.hboxlayout5.setMargin(4)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.vessel_length_text = QtGui.QLabel(self.vessel_length)
        self.vessel_length_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_length_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_length_text.setFont(font)
        self.vessel_length_text.setObjectName("vessel_length_text")
        self.hboxlayout5.addWidget(self.vessel_length_text)
        self.vessel_length_line = QtGui.QLineEdit(self.vessel_length)
        self.vessel_length_line.setEnabled(True)
        self.vessel_length_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_length_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_length_line.setFont(font)
        self.vessel_length_line.setObjectName("vessel_length_line")
        self.hboxlayout5.addWidget(self.vessel_length_line)
        self.verticalLayout.addWidget(self.vessel_length)
        self.vessel_motor = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_motor.setFont(font)
        self.vessel_motor.setObjectName("vessel_motor")
        self._14 = QtGui.QHBoxLayout(self.vessel_motor)
        self._14.setSpacing(4)
        self._14.setMargin(4)
        self._14.setObjectName("_14")
        self.vessel_motor_text = QtGui.QLabel(self.vessel_motor)
        self.vessel_motor_text.setMinimumSize(QtCore.QSize(150, 0))
        self.vessel_motor_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_motor_text.setFont(font)
        self.vessel_motor_text.setObjectName("vessel_motor_text")
        self._14.addWidget(self.vessel_motor_text)
        self.vessel_motor_line = QtGui.QLineEdit(self.vessel_motor)
        self.vessel_motor_line.setEnabled(True)
        self.vessel_motor_line.setMinimumSize(QtCore.QSize(200, 0))
        self.vessel_motor_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_motor_line.setFont(font)
        self.vessel_motor_line.setObjectName("vessel_motor_line")
        self._14.addWidget(self.vessel_motor_line)
        self.verticalLayout.addWidget(self.vessel_motor)
        self.vessel_hole_capacity = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vessel_hole_capacity.setFont(font)
        self.vessel_hole_capacity.setObjectName("vessel_hole_capacity")
        self._15 = QtGui.QHBoxLayout(self.vessel_hole_capacity)
        self._15.setSpacing(4)
        self._15.setMargin(4)
        self._15.setObjectName("_15")
        self.hole_capacity_text = QtGui.QLabel(self.vessel_hole_capacity)
        self.hole_capacity_text.setMinimumSize(QtCore.QSize(150, 0))
        self.hole_capacity_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hole_capacity_text.setFont(font)
        self.hole_capacity_text.setObjectName("hole_capacity_text")
        self._15.addWidget(self.hole_capacity_text)
        self.hole_capacity_line = QtGui.QLineEdit(self.vessel_hole_capacity)
        self.hole_capacity_line.setEnabled(True)
        self.hole_capacity_line.setMinimumSize(QtCore.QSize(200, 0))
        self.hole_capacity_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hole_capacity_line.setFont(font)
        self.hole_capacity_line.setObjectName("hole_capacity_line")
        self._15.addWidget(self.hole_capacity_line)
        self.verticalLayout.addWidget(self.vessel_hole_capacity)
        self.landing_port = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port.setFont(font)
        self.landing_port.setObjectName("landing_port")
        self._7 = QtGui.QHBoxLayout(self.landing_port)
        self._7.setSpacing(4)
        self._7.setMargin(4)
        self._7.setObjectName("_7")
        self.landing_port_text = QtGui.QLabel(self.landing_port)
        self.landing_port_text.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_text.setFont(font)
        self.landing_port_text.setObjectName("landing_port_text")
        self._7.addWidget(self.landing_port_text)
        self.landing_port_line = QtGui.QLineEdit(self.landing_port)
        self.landing_port_line.setEnabled(True)
        self.landing_port_line.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_line.setFont(font)
        self.landing_port_line.setObjectName("landing_port_line")
        self._7.addWidget(self.landing_port_line)
        self.verticalLayout.addWidget(self.landing_port)
        self.landing_port_2 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_2.setFont(font)
        self.landing_port_2.setObjectName("landing_port_2")
        self._16 = QtGui.QHBoxLayout(self.landing_port_2)
        self._16.setSpacing(4)
        self._16.setMargin(4)
        self._16.setObjectName("_16")
        self.landing_port_text_2 = QtGui.QLabel(self.landing_port_2)
        self.landing_port_text_2.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_text_2.setFont(font)
        self.landing_port_text_2.setObjectName("landing_port_text_2")
        self._16.addWidget(self.landing_port_text_2)
        self.landing_port_line_2 = QtGui.QLineEdit(self.landing_port_2)
        self.landing_port_line_2.setEnabled(True)
        self.landing_port_line_2.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_line_2.setFont(font)
        self.landing_port_line_2.setObjectName("landing_port_line_2")
        self._16.addWidget(self.landing_port_line_2)
        self.verticalLayout.addWidget(self.landing_port_2)
        self.landing_port_3 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_3.setFont(font)
        self.landing_port_3.setObjectName("landing_port_3")
        self._17 = QtGui.QHBoxLayout(self.landing_port_3)
        self._17.setSpacing(4)
        self._17.setMargin(4)
        self._17.setObjectName("_17")
        self.landing_port_text_3 = QtGui.QLabel(self.landing_port_3)
        self.landing_port_text_3.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_text_3.setFont(font)
        self.landing_port_text_3.setObjectName("landing_port_text_3")
        self._17.addWidget(self.landing_port_text_3)
        self.landing_port_line_3 = QtGui.QLineEdit(self.landing_port_3)
        self.landing_port_line_3.setEnabled(True)
        self.landing_port_line_3.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_line_3.setFont(font)
        self.landing_port_line_3.setObjectName("landing_port_line_3")
        self._17.addWidget(self.landing_port_line_3)
        self.verticalLayout.addWidget(self.landing_port_3)
        self.landing_port_4 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_4.setFont(font)
        self.landing_port_4.setObjectName("landing_port_4")
        self._18 = QtGui.QHBoxLayout(self.landing_port_4)
        self._18.setSpacing(4)
        self._18.setMargin(4)
        self._18.setObjectName("_18")
        self.landing_port_text_4 = QtGui.QLabel(self.landing_port_4)
        self.landing_port_text_4.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_text_4.setFont(font)
        self.landing_port_text_4.setObjectName("landing_port_text_4")
        self._18.addWidget(self.landing_port_text_4)
        self.landing_port_line_4 = QtGui.QLineEdit(self.landing_port_4)
        self.landing_port_line_4.setEnabled(True)
        self.landing_port_line_4.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_line_4.setFont(font)
        self.landing_port_line_4.setObjectName("landing_port_line_4")
        self._18.addWidget(self.landing_port_line_4)
        self.verticalLayout.addWidget(self.landing_port_4)
        self.landing_port_5 = QtGui.QWidget(self.vessel_info)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_5.setFont(font)
        self.landing_port_5.setObjectName("landing_port_5")
        self._13 = QtGui.QHBoxLayout(self.landing_port_5)
        self._13.setSpacing(4)
        self._13.setMargin(4)
        self._13.setObjectName("_13")
        self.landing_port_text_5 = QtGui.QLabel(self.landing_port_5)
        self.landing_port_text_5.setMinimumSize(QtCore.QSize(150, 0))
        self.landing_port_text_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_text_5.setFont(font)
        self.landing_port_text_5.setObjectName("landing_port_text_5")
        self._13.addWidget(self.landing_port_text_5)
        self.landing_port_line_5 = QtGui.QLineEdit(self.landing_port_5)
        self.landing_port_line_5.setEnabled(True)
        self.landing_port_line_5.setMinimumSize(QtCore.QSize(200, 0))
        self.landing_port_line_5.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.landing_port_line_5.setFont(font)
        self.landing_port_line_5.setObjectName("landing_port_line_5")
        self._13.addWidget(self.landing_port_line_5)
        self.verticalLayout.addWidget(self.landing_port_5)
        self.horizontalLayout.addWidget(self.vessel_info)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.button_box = QtGui.QWidget(InterviewStart)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_box.setFont(font)
        self.button_box.setObjectName("button_box")
        self._19 = QtGui.QHBoxLayout(self.button_box)
        self._19.setSpacing(2)
        self._19.setMargin(2)
        self._19.setObjectName("_19")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._19.addItem(spacerItem1)
        self.pbnSelectFishery = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbnSelectFishery.setFont(font)
        self.pbnSelectFishery.setObjectName("pbnSelectFishery")
        self._19.addWidget(self.pbnSelectFishery)
        self.pbnCancel = QtGui.QPushButton(self.button_box)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pbnCancel.setFont(font)
        self.pbnCancel.setObjectName("pbnCancel")
        self._19.addWidget(self.pbnCancel)
        self.verticalLayout_3.addWidget(self.button_box)

        self.retranslateUi(InterviewStart)
        self.gender_comboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(InterviewStart)
        InterviewStart.setTabOrder(self.interviewee_first_name_line, self.interviewee_last_name_line)
        InterviewStart.setTabOrder(self.interviewee_last_name_line, self.age_line)
        InterviewStart.setTabOrder(self.age_line, self.gender_comboBox)
        InterviewStart.setTabOrder(self.gender_comboBox, self.city_line)
        InterviewStart.setTabOrder(self.city_line, self.data_sharing_comboBox)
        InterviewStart.setTabOrder(self.data_sharing_comboBox, self.InterviewDate)
        InterviewStart.setTabOrder(self.InterviewDate, self.interviewer1_first_name_line)
        InterviewStart.setTabOrder(self.interviewer1_first_name_line, self.interviewer1_last_name_line)
        InterviewStart.setTabOrder(self.interviewer1_last_name_line, self.mood_line)
        InterviewStart.setTabOrder(self.mood_line, self.home_port_line)
        InterviewStart.setTabOrder(self.home_port_line, self.years_line)
        InterviewStart.setTabOrder(self.years_line, self.perc_income_line)
        InterviewStart.setTabOrder(self.perc_income_line, self.vessel_name_line)
        InterviewStart.setTabOrder(self.vessel_name_line, self.vessel_length_line)
        InterviewStart.setTabOrder(self.vessel_length_line, self.vessel_motor_line)
        InterviewStart.setTabOrder(self.vessel_motor_line, self.hole_capacity_line)
        InterviewStart.setTabOrder(self.hole_capacity_line, self.landing_port_line)
        InterviewStart.setTabOrder(self.landing_port_line, self.landing_port_line_2)
        InterviewStart.setTabOrder(self.landing_port_line_2, self.landing_port_line_3)
        InterviewStart.setTabOrder(self.landing_port_line_3, self.landing_port_line_4)
        InterviewStart.setTabOrder(self.landing_port_line_4, self.landing_port_line_5)
        InterviewStart.setTabOrder(self.landing_port_line_5, self.pbnSelectFishery)
        InterviewStart.setTabOrder(self.pbnSelectFishery, self.pbnCancel)

    def retranslateUi(self, InterviewStart):
        InterviewStart.setWindowTitle(QtGui.QApplication.translate("InterviewStart", "OpenOceanMap - Interview", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee.setTitle(QtGui.QApplication.translate("InterviewStart", "Interviewee", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_first_name_text.setText(QtGui.QApplication.translate("InterviewStart", "First Name *:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_first_name_line.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_last_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Last Name *:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_last_name_line.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.age_text.setText(QtGui.QApplication.translate("InterviewStart", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_text.setText(QtGui.QApplication.translate("InterviewStart", "Gender:", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_comboBox.setItemText(1, QtGui.QApplication.translate("InterviewStart", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.gender_comboBox.setItemText(2, QtGui.QApplication.translate("InterviewStart", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.city_text.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.city_text.setText(QtGui.QApplication.translate("InterviewStart", "Community of Residence *:", None, QtGui.QApplication.UnicodeUTF8))
        self.city_line.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.data_sharing_text.setText(QtGui.QApplication.translate("InterviewStart", "Data Sharing *:", None, QtGui.QApplication.UnicodeUTF8))
        self.data_sharing_comboBox.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.data_sharing_comboBox.setItemText(1, QtGui.QApplication.translate("InterviewStart", "Private (not available in public form, private usage only)", None, QtGui.QApplication.UnicodeUTF8))
        self.data_sharing_comboBox.setItemText(2, QtGui.QApplication.translate("InterviewStart", "Amalgamated (only shown publically when combined with other fishers data)", None, QtGui.QApplication.UnicodeUTF8))
        self.data_sharing_comboBox.setItemText(3, QtGui.QApplication.translate("InterviewStart", "Complete (can be shown publically as a stand alone dataset)", None, QtGui.QApplication.UnicodeUTF8))
        self.data_sharing_comboBox.setItemText(4, QtGui.QApplication.translate("InterviewStart", "Limited (none of the above, individual data sharing agreement)", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewee_2.setTitle(QtGui.QApplication.translate("InterviewStart", "Interviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.date_text.setText(QtGui.QApplication.translate("InterviewStart", "Interview Date *:", None, QtGui.QApplication.UnicodeUTF8))
        self.InterviewDate.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_first_name_text.setText(QtGui.QApplication.translate("InterviewStart", "First Name *:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_first_name_line.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_last_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Last Name *:", None, QtGui.QApplication.UnicodeUTF8))
        self.interviewer1_last_name_line.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.mood_text.setText(QtGui.QApplication.translate("InterviewStart", "Interviewee\'s Outlook:", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_info.setTitle(QtGui.QApplication.translate("InterviewStart", "Commercial Fishing Information", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_text.setText(QtGui.QApplication.translate("InterviewStart", "Home Port *:", None, QtGui.QApplication.UnicodeUTF8))
        self.home_port_line.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.years_text.setText(QtGui.QApplication.translate("InterviewStart", "Years of experience *:", None, QtGui.QApplication.UnicodeUTF8))
        self.years_line.setToolTip(QtGui.QApplication.translate("InterviewStart", "Required Field", None, QtGui.QApplication.UnicodeUTF8))
        self.perc_income_text.setText(QtGui.QApplication.translate("InterviewStart", "% of income from fishing:", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_name_text.setText(QtGui.QApplication.translate("InterviewStart", "Fish Vessel Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_length_text.setText(QtGui.QApplication.translate("InterviewStart", "Length of Vessel (ft):", None, QtGui.QApplication.UnicodeUTF8))
        self.vessel_motor_text.setText(QtGui.QApplication.translate("InterviewStart", "Vessel Motor (HP):", None, QtGui.QApplication.UnicodeUTF8))
        self.hole_capacity_text.setText(QtGui.QApplication.translate("InterviewStart", "Hole Capacity (lb):", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_2.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_3.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_4.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.landing_port_text_5.setText(QtGui.QApplication.translate("InterviewStart", "Landing Port 5:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnSelectFishery.setText(QtGui.QApplication.translate("InterviewStart", "Select Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("InterviewStart", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

