# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nextclippedpolygon.ui'
#
# Created: Thu Sep 24 15:34:22 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NextClippedPolygon(object):
    def setupUi(self, NextClippedPolygon):
        NextClippedPolygon.setObjectName("NextClippedPolygon")
        NextClippedPolygon.setWindowModality(QtCore.Qt.NonModal)
        NextClippedPolygon.resize(550, 173)
        self.verticalLayout = QtGui.QVBoxLayout(NextClippedPolygon)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.widget = QtGui.QWidget(NextClippedPolygon)
        self.widget.setObjectName("widget")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setContentsMargins(9, 9, 9, 0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.fishery_text = QtGui.QLabel(self.widget)
        self.fishery_text.setMinimumSize(QtCore.QSize(300, 0))
        self.fishery_text.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fishery_text.setObjectName("fishery_text")
        self.hboxlayout1.addWidget(self.fishery_text)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.fishery_line = QtGui.QLineEdit(self.widget)
        self.fishery_line.setMinimumSize(QtCore.QSize(200, 0))
        self.fishery_line.setObjectName("fishery_line")
        self.hboxlayout1.addWidget(self.fishery_line)
        self.hboxlayout.addWidget(self.widget)
        self.verticalLayout.addLayout(self.hboxlayout)
        self._4 = QtGui.QHBoxLayout()
        self._4.setMargin(9)
        self._4.setObjectName("_4")
        self.shapeNum_label = QtGui.QLabel(NextClippedPolygon)
        self.shapeNum_label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shapeNum_label.setFont(font)
        self.shapeNum_label.setObjectName("shapeNum_label")
        self._4.addWidget(self.shapeNum_label)
        spacerItem1 = QtGui.QSpacerItem(88, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._4.addItem(spacerItem1)
        self.label_1 = QtGui.QLabel(NextClippedPolygon)
        self.label_1.setMinimumSize(QtCore.QSize(100, 0))
        self.label_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self._4.addWidget(self.label_1)
        self.line_1 = QtGui.QLineEdit(NextClippedPolygon)
        self.line_1.setEnabled(True)
        self.line_1.setMinimumSize(QtCore.QSize(100, 0))
        self.line_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_1.setFont(font)
        self.line_1.setObjectName("line_1")
        self._4.addWidget(self.line_1)
        self.pl_label = QtGui.QLabel(NextClippedPolygon)
        self.pl_label.setMinimumSize(QtCore.QSize(50, 0))
        self.pl_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pl_label.setObjectName("pl_label")
        self._4.addWidget(self.pl_label)
        self.verticalLayout.addLayout(self._4)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.widget_2 = QtGui.QWidget(NextClippedPolygon)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.widget_2)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setMargin(9)
        self.hboxlayout3.setObjectName("hboxlayout3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem2)
        self.pbnNextShape = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnNextShape.setFont(font)
        self.pbnNextShape.setObjectName("pbnNextShape")
        self.hboxlayout3.addWidget(self.pbnNextShape)
        self.hboxlayout2.addWidget(self.widget_2)
        self.verticalLayout.addLayout(self.hboxlayout2)

        self.retranslateUi(NextClippedPolygon)
        QtCore.QMetaObject.connectSlotsByName(NextClippedPolygon)

    def retranslateUi(self, NextClippedPolygon):
        NextClippedPolygon.setWindowTitle(QtGui.QApplication.translate("NextClippedPolygon", "OpenOceanMap - Next Clipped Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_text.setText(QtGui.QApplication.translate("NextClippedPolygon", "Current Fishery :", None, QtGui.QApplication.UnicodeUTF8))
        self.shapeNum_label.setText(QtGui.QApplication.translate("NextClippedPolygon", "Shape #", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("NextClippedPolygon", "Pennies:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnNextShape.setText(QtGui.QApplication.translate("NextClippedPolygon", "Next Shape", None, QtGui.QApplication.UnicodeUTF8))

