# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectfishery.ui'
#
# Created: Thu Nov 05 16:52:59 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SelectFishery(object):
    def setupUi(self, SelectFishery):
        SelectFishery.setObjectName("SelectFishery")
        SelectFishery.resize(622, 379)
        self.gridLayout = QtGui.QGridLayout(SelectFishery)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setContentsMargins(9, 9, 9, 0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.fishery_text = QtGui.QLabel(self.widget)
        self.fishery_text.setMinimumSize(QtCore.QSize(90, 0))
        self.fishery_text.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_text.setFont(font)
        self.fishery_text.setObjectName("fishery_text")
        self.hboxlayout.addWidget(self.fishery_text)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.fishery_comboBox = QtGui.QComboBox(self.widget)
        self.fishery_comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.fishery_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_comboBox.setFont(font)
        self.fishery_comboBox.setObjectName("fishery_comboBox")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.setItemText(0, "")
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.fishery_comboBox.addItem(QtCore.QString())
        self.hboxlayout.addWidget(self.fishery_comboBox)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.widget_13 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_13.setFont(font)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.widget_13)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_14 = QtGui.QLabel(self.widget_13)
        self.label_14.setMinimumSize(QtCore.QSize(90, 0))
        self.label_14.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_26.addWidget(self.label_14)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem1)
        self.fishery_vessel_name = QtGui.QLineEdit(self.widget_13)
        self.fishery_vessel_name.setMinimumSize(QtCore.QSize(200, 0))
        self.fishery_vessel_name.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_vessel_name.setFont(font)
        self.fishery_vessel_name.setObjectName("fishery_vessel_name")
        self.horizontalLayout_26.addWidget(self.fishery_vessel_name)
        self.horizontalLayout_25.addWidget(self.widget_13)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.widget_14 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_14.setFont(font)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.widget_14)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_15 = QtGui.QLabel(self.widget_14)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        self.label_15.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_28.addWidget(self.label_15)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem2)
        self.fishery_vessel_length = QtGui.QLineEdit(self.widget_14)
        self.fishery_vessel_length.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_vessel_length.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_vessel_length.setFont(font)
        self.fishery_vessel_length.setObjectName("fishery_vessel_length")
        self.horizontalLayout_28.addWidget(self.fishery_vessel_length)
        self.horizontalLayout_27.addWidget(self.widget_14)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_6 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_6.setFont(font)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtGui.QLabel(self.widget_6)
        self.label_9.setMinimumSize(QtCore.QSize(200, 0))
        self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.fishery_perc_income = QtGui.QLineEdit(self.widget_6)
        self.fishery_perc_income.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_perc_income.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_perc_income.setFont(font)
        self.fishery_perc_income.setObjectName("fishery_perc_income")
        self.horizontalLayout_16.addWidget(self.fishery_perc_income)
        self.horizontalLayout_15.addWidget(self.widget_6)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_12 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_12.setFont(font)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtGui.QLabel(self.widget_12)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.fishery_start_year = QtGui.QLineEdit(self.widget_12)
        self.fishery_start_year.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_start_year.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_start_year.setFont(font)
        self.fishery_start_year.setObjectName("fishery_start_year")
        self.horizontalLayout_10.addWidget(self.fishery_start_year)
        self.horizontalLayout_9.addWidget(self.widget_12)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_11 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_11.setFont(font)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtGui.QLabel(self.widget_11)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.fishery_end_year = QtGui.QLineEdit(self.widget_11)
        self.fishery_end_year.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_end_year.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_end_year.setFont(font)
        self.fishery_end_year.setObjectName("fishery_end_year")
        self.horizontalLayout_8.addWidget(self.fishery_end_year)
        self.horizontalLayout_7.addWidget(self.widget_11)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_4 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtGui.QLabel(self.widget_4)
        self.label_7.setMinimumSize(QtCore.QSize(200, 0))
        self.label_7.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.fishery_yrs_exp = QtGui.QLineEdit(self.widget_4)
        self.fishery_yrs_exp.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_yrs_exp.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_yrs_exp.setFont(font)
        self.fishery_yrs_exp.setObjectName("fishery_yrs_exp")
        self.horizontalLayout_12.addWidget(self.fishery_yrs_exp)
        self.horizontalLayout_11.addWidget(self.widget_4)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.widget_8 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_8.setFont(font)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_11 = QtGui.QLabel(self.widget_8)
        self.label_11.setMinimumSize(QtCore.QSize(200, 0))
        self.label_11.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.fishery_effort_month_per_year = QtGui.QLineEdit(self.widget_8)
        self.fishery_effort_month_per_year.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_effort_month_per_year.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_effort_month_per_year.setFont(font)
        self.fishery_effort_month_per_year.setObjectName("fishery_effort_month_per_year")
        self.horizontalLayout_20.addWidget(self.fishery_effort_month_per_year)
        self.horizontalLayout_19.addWidget(self.widget_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.widget_9 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_9.setFont(font)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_12 = QtGui.QLabel(self.widget_9)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_22.addWidget(self.label_12)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.fishery_effort_days = QtGui.QLineEdit(self.widget_9)
        self.fishery_effort_days.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_effort_days.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_effort_days.setFont(font)
        self.fishery_effort_days.setObjectName("fishery_effort_days")
        self.horizontalLayout_22.addWidget(self.fishery_effort_days)
        self.horizontalLayout_21.addWidget(self.widget_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_7 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_7.setFont(font)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtGui.QLabel(self.widget_7)
        self.label_10.setMinimumSize(QtCore.QSize(200, 0))
        self.label_10.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.fishery_traps_hooks = QtGui.QLineEdit(self.widget_7)
        self.fishery_traps_hooks.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_traps_hooks.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_traps_hooks.setFont(font)
        self.fishery_traps_hooks.setObjectName("fishery_traps_hooks")
        self.horizontalLayout_18.addWidget(self.fishery_traps_hooks)
        self.horizontalLayout_17.addWidget(self.widget_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.widget_10 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_10.setFont(font)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_13 = QtGui.QLabel(self.widget_10)
        self.label_13.setMinimumSize(QtCore.QSize(200, 0))
        self.label_13.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_24.addWidget(self.label_13)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem10)
        self.fishery_avg_pounds_per_trip = QtGui.QLineEdit(self.widget_10)
        self.fishery_avg_pounds_per_trip.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_avg_pounds_per_trip.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_avg_pounds_per_trip.setFont(font)
        self.fishery_avg_pounds_per_trip.setObjectName("fishery_avg_pounds_per_trip")
        self.horizontalLayout_24.addWidget(self.fishery_avg_pounds_per_trip)
        self.horizontalLayout_23.addWidget(self.widget_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_5 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_5.setFont(font)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtGui.QLabel(self.widget_5)
        self.label_8.setMinimumSize(QtCore.QSize(200, 0))
        self.label_8.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.fishery_avg_price_per_pound = QtGui.QLineEdit(self.widget_5)
        self.fishery_avg_price_per_pound.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_avg_price_per_pound.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_avg_price_per_pound.setFont(font)
        self.fishery_avg_price_per_pound.setObjectName("fishery_avg_price_per_pound")
        self.horizontalLayout_14.addWidget(self.fishery_avg_price_per_pound)
        self.horizontalLayout_13.addWidget(self.widget_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.fishery_hist_avg_price = QtGui.QLineEdit(self.widget_3)
        self.fishery_hist_avg_price.setMinimumSize(QtCore.QSize(40, 0))
        self.fishery_hist_avg_price.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.fishery_hist_avg_price.setFont(font)
        self.fishery_hist_avg_price.setObjectName("fishery_hist_avg_price")
        self.horizontalLayout_4.addWidget(self.fishery_hist_avg_price)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtGui.QWidget(SelectFishery)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget_2)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(9)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem13)
        self.pbnStartShapes = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.pbnStartShapes.setFont(font)
        self.pbnStartShapes.setObjectName("pbnStartShapes")
        self.hboxlayout1.addWidget(self.pbnStartShapes)
        self.pbnFisheryFinished = QtGui.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        self.pbnFisheryFinished.setFont(font)
        self.pbnFisheryFinished.setObjectName("pbnFisheryFinished")
        self.hboxlayout1.addWidget(self.pbnFisheryFinished)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)

        self.retranslateUi(SelectFishery)
        QtCore.QMetaObject.connectSlotsByName(SelectFishery)
        SelectFishery.setTabOrder(self.fishery_comboBox, self.fishery_vessel_name)
        SelectFishery.setTabOrder(self.fishery_vessel_name, self.fishery_vessel_length)
        SelectFishery.setTabOrder(self.fishery_vessel_length, self.fishery_perc_income)
        SelectFishery.setTabOrder(self.fishery_perc_income, self.fishery_start_year)
        SelectFishery.setTabOrder(self.fishery_start_year, self.fishery_end_year)
        SelectFishery.setTabOrder(self.fishery_end_year, self.fishery_yrs_exp)
        SelectFishery.setTabOrder(self.fishery_yrs_exp, self.fishery_effort_month_per_year)
        SelectFishery.setTabOrder(self.fishery_effort_month_per_year, self.fishery_effort_days)
        SelectFishery.setTabOrder(self.fishery_effort_days, self.fishery_traps_hooks)
        SelectFishery.setTabOrder(self.fishery_traps_hooks, self.fishery_avg_price_per_pound)
        SelectFishery.setTabOrder(self.fishery_avg_price_per_pound, self.fishery_avg_pounds_per_trip)
        SelectFishery.setTabOrder(self.fishery_avg_pounds_per_trip, self.fishery_hist_avg_price)
        SelectFishery.setTabOrder(self.fishery_hist_avg_price, self.pbnStartShapes)
        SelectFishery.setTabOrder(self.pbnStartShapes, self.pbnFisheryFinished)

    def retranslateUi(self, SelectFishery):
        SelectFishery.setWindowTitle(QtGui.QApplication.translate("SelectFishery", "OpenOceanMap - Select Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_text.setText(QtGui.QApplication.translate("SelectFishery", "Select Fishery:", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(1, QtGui.QApplication.translate("SelectFishery", "Clam", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(2, QtGui.QApplication.translate("SelectFishery", "Cod", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(3, QtGui.QApplication.translate("SelectFishery", "Crab", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(4, QtGui.QApplication.translate("SelectFishery", "Eulachon", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(5, QtGui.QApplication.translate("SelectFishery", "Dogfish", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(6, QtGui.QApplication.translate("SelectFishery", "Green Urchin", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(7, QtGui.QApplication.translate("SelectFishery", "Groundfish H&L", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(8, QtGui.QApplication.translate("SelectFishery", "Groundfish Trawl", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(9, QtGui.QApplication.translate("SelectFishery", "Halibut", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(10, QtGui.QApplication.translate("SelectFishery", "Herring Gillnet", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(11, QtGui.QApplication.translate("SelectFishery", "Herring Seine", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(12, QtGui.QApplication.translate("SelectFishery", "Octopus", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(13, QtGui.QApplication.translate("SelectFishery", "Prawn", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(14, QtGui.QApplication.translate("SelectFishery", "Red Urchin", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(15, QtGui.QApplication.translate("SelectFishery", "Rockfish", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(16, QtGui.QApplication.translate("SelectFishery", "Sablefish", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(17, QtGui.QApplication.translate("SelectFishery", "Salmon Gillnet", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(18, QtGui.QApplication.translate("SelectFishery", "Salmon Seine", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(19, QtGui.QApplication.translate("SelectFishery", "Salmon Troll", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(20, QtGui.QApplication.translate("SelectFishery", "Sardine", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(21, QtGui.QApplication.translate("SelectFishery", "Scallop", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(22, QtGui.QApplication.translate("SelectFishery", "Seaweed", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(23, QtGui.QApplication.translate("SelectFishery", "Shrimp Trap", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(24, QtGui.QApplication.translate("SelectFishery", "Shrimp Trawl", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(25, QtGui.QApplication.translate("SelectFishery", "Tuna", None, QtGui.QApplication.UnicodeUTF8))
        self.fishery_comboBox.setItemText(26, QtGui.QApplication.translate("SelectFishery", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("SelectFishery", "Fish Vessel name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("SelectFishery", "Length of Vessel (ft):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("SelectFishery", "Percent income:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SelectFishery", "Fishery Start Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SelectFishery", "Fishery End Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SelectFishery", "Years experience in fishery:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("SelectFishery", "Month per year of fishing effort:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("SelectFishery", "Days per week in these months:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("SelectFishery", "Num traps/hooks/tows/sets used per trip:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("SelectFishery", "Average pounds per trip:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("SelectFishery", "Average price per pound:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SelectFishery", "Historic average price:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnStartShapes.setText(QtGui.QApplication.translate("SelectFishery", "Start Drawing Shapes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnFisheryFinished.setText(QtGui.QApplication.translate("SelectFishery", "Finished With Interview", None, QtGui.QApplication.UnicodeUTF8))

