# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nextpolygon.ui'
#
# Created: Sat Jun 21 22:25:25 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NextPolygon(object):
    def setupUi(self, NextPolygon):
        NextPolygon.setObjectName("NextPolygon")
        NextPolygon.resize(550,165)
        self.horizontalLayout_5 = QtGui.QHBoxLayout(NextPolygon)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtGui.QGroupBox(NextPolygon)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(-1,0,-1,0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(-1,-1,-1,6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_1 = QtGui.QLabel(self.groupBox)
        self.label_1.setMinimumSize(QtCore.QSize(100,0))
        self.label_1.setMaximumSize(QtCore.QSize(100,16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_2.addWidget(self.label_1)
        self.line_1 = QtGui.QLineEdit(self.groupBox)
        self.line_1.setEnabled(True)
        self.line_1.setMinimumSize(QtCore.QSize(100,0))
        self.line_1.setMaximumSize(QtCore.QSize(100,16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_1.setFont(font)
        self.line_1.setObjectName("line_1")
        self.horizontalLayout_2.addWidget(self.line_1)
        self.pl_label = QtGui.QLabel(self.groupBox)
        self.pl_label.setMinimumSize(QtCore.QSize(50,0))
        self.pl_label.setMaximumSize(QtCore.QSize(50,16777215))
        self.pl_label.setObjectName("pl_label")
        self.horizontalLayout_2.addWidget(self.pl_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.habitat_combo_label = QtGui.QLabel(self.groupBox)
        self.habitat_combo_label.setMinimumSize(QtCore.QSize(100,0))
        self.habitat_combo_label.setMaximumSize(QtCore.QSize(100,16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.habitat_combo_label.setFont(font)
        self.habitat_combo_label.setObjectName("habitat_combo_label")
        self.horizontalLayout.addWidget(self.habitat_combo_label)
        self.habitat_combo = QtGui.QComboBox(self.groupBox)
        self.habitat_combo.setMinimumSize(QtCore.QSize(100,0))
        self.habitat_combo.setMaximumSize(QtCore.QSize(100,16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.habitat_combo.setFont(font)
        self.habitat_combo.setObjectName("habitat_combo")
        self.horizontalLayout.addWidget(self.habitat_combo)
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(88,89,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pbnShapeFinished = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnShapeFinished.setFont(font)
        self.pbnShapeFinished.setObjectName("pbnShapeFinished")
        self.hboxlayout.addWidget(self.pbnShapeFinished)
        self.pbnShapeDiscard = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnShapeDiscard.setFont(font)
        self.pbnShapeDiscard.setObjectName("pbnShapeDiscard")
        self.hboxlayout.addWidget(self.pbnShapeDiscard)
        self.pbnMoreShapes = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbnMoreShapes.setFont(font)
        self.pbnMoreShapes.setObjectName("pbnMoreShapes")
        self.hboxlayout.addWidget(self.pbnMoreShapes)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_5.addWidget(self.groupBox)

        self.retranslateUi(NextPolygon)
        QtCore.QMetaObject.connectSlotsByName(NextPolygon)

    def retranslateUi(self, NextPolygon):
        NextPolygon.setWindowTitle(QtGui.QApplication.translate("NextPolygon", "OpenOceanMap - Next Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("NextPolygon", "Pennies:", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo_label.setText(QtGui.QApplication.translate("NextPolygon", "Habitat Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.addItem(QtGui.QApplication.translate("NextPolygon", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.addItem(QtGui.QApplication.translate("NextPolygon", "Hard Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.addItem(QtGui.QApplication.translate("NextPolygon", "Soft Sandy", None, QtGui.QApplication.UnicodeUTF8))
        self.habitat_combo.addItem(QtGui.QApplication.translate("NextPolygon", "Mixed", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnShapeFinished.setText(QtGui.QApplication.translate("NextPolygon", "Finished With Fishery", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnShapeDiscard.setText(QtGui.QApplication.translate("NextPolygon", "Discard Last Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnMoreShapes.setText(QtGui.QApplication.translate("NextPolygon", "More Shapes This Fishery", None, QtGui.QApplication.UnicodeUTF8))

